In [ ]:
import os
import pandas as pd
import requests
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

# API 키 불러오기

In [ ]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료 : {API_KEY[:4]}...{API_KEY[-4:]}')
else:
    print('API 키를 설정하세요')

API 키 로드 완료 : 0f4c...0ab9

# API 연결 확인

In [13]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json', 'cityCode':22, 'nodeid':'DGB7011006700'})
response.raise_for_status()

In [14]:
response.status_code

200

In [22]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB4060003002',
      'routeno': '북구3',
      'routetp': '지선버스',
      'startnodenm': '노곡동'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000708002',
      'routeno': 708,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000805000',
      'routeno': 805,
      'routetp': '간선버스',
      'startnodenm': '달서아트센터앞'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000413001',
      'routeno': 413,
      'routetp': '간선버스',
      'startnodenm': '가창초등학교앞'},
     {'endnodenm': '동대구역',
      'routeid': 'DGB3001814000',
      'routeno': 8140,
      'routetp': '일반버스',
      'startnodenm': 'TBC건너'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB4060006000',
      'routeno': '북구6',
      'routetp': '지선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '동대구역(2번출구)건너',
      'routeid': 'DGB3000650005',
      'routeno': 650,
      'routetp': '간선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002100',
      'routeno': '순환2-1',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '진밭골(종점)2',
      'routeid': 'DGB3000814001',
      'routeno': 814,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000156000',
      'routeno': 156,
      'routetp': '간선버스',
      'startnodenm': '신덕마을입구건너'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 13}}}

In [42]:
# 환경 설정
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
CITY_CODE = 22
NODE_ID = 'DGB7011006700'
NODE_NAME = '동대구역'

In [47]:
# 경로 설정
BASE_DIR = os.getcwd()
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'bus_route.csv')

print(f'CSV 파일 저장 경로 : {OUTPUT_PATH}')

CSV 파일 저장 경로 : c:\Users\Administrator\bigdata2026\fastapi\bus_route_pipeline\output\bus_route.csv

In [41]:
# PostgreSQL 설정
DB_URL = 'postgresql://postgres:1234@localhost:5432/busapidb'
TABLE_NAME = 'route_by_stop'

# JSON 구조 확인

In [27]:
response = requests.get(BASE_URL,
                        params={
                            'serviceKey':API_KEY,
                            'pageNo':1,
                            'numOfRows':10,
                            '_type':'json',
                            'cityCode':CITY_CODE,
                            'nodeid':NODE_ID
                        })
response.status_code

200

In [28]:
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB4060003002',
      'routeno': '북구3',
      'routetp': '지선버스',
      'startnodenm': '노곡동'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000708002',
      'routeno': 708,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000805000',
      'routeno': 805,
      'routetp': '간선버스',
      'startnodenm': '달서아트센터앞'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000413001',
      'routeno': 413,
      'routetp': '간선버스',
      'startnodenm': '가창초등학교앞'},
     {'endnodenm': '동대구역',
      'routeid': 'DGB3001814000',
      'routeno': 8140,
      'routetp': '일반버스',
      'startnodenm': 'TBC건너'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB4060006000',
      'routeno': '북구6',
      'routetp': '지선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '동대구역(2번출구)건너',
      'routeid': 'DGB3000650005',
      'routeno': 650,
      'routetp': '간선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002100',
      'routeno': '순환2-1',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '진밭골(종점)2',
      'routeid': 'DGB3000814001',
      'routeno': 814,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000156000',
      'routeno': 156,
      'routetp': '간선버스',
      'startnodenm': '신덕마을입구건너'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 13}}}

# DataFrame 만들기

In [29]:
df_body = data['response']['body']
df_body

{'items': {'item': [{'endnodenm': '동호공영차고지건너',
    'routeid': 'DGB4060003002',
    'routeno': '북구3',
    'routetp': '지선버스',
    'startnodenm': '노곡동'},
   {'endnodenm': '동호공영차고지건너',
    'routeid': 'DGB3000708002',
    'routeno': 708,
    'routetp': '간선버스',
    'startnodenm': '북구 동호동(종점)1'},
   {'endnodenm': '반야월역(3번출구)',
    'routeid': 'DGB3000805000',
    'routeno': 805,
    'routetp': '간선버스',
    'startnodenm': '달서아트센터앞'},
   {'endnodenm': '유통단지회차지',
    'routeid': 'DGB3000413001',
    'routeno': 413,
    'routetp': '간선버스',
    'startnodenm': '가창초등학교앞'},
   {'endnodenm': '동대구역',
    'routeid': 'DGB3001814000',
    'routeno': 8140,
    'routetp': '일반버스',
    'startnodenm': 'TBC건너'},
   {'endnodenm': '성보교통건너',
    'routeid': 'DGB4060006000',
    'routeno': '북구6',
    'routetp': '지선버스',
    'startnodenm': '성보교통앞'},
   {'endnodenm': '동대구역(2번출구)건너',
    'routeid': 'DGB3000650005',
    'routeno': 650,
    'routetp': '간선버스',
    'startnodenm': '다산(종점)'},
   {'endnodenm': '성보교통건너',
    'routeid': 'DGB2000002100',
    'routeno': '순환2-1',
    'routetp': '순환버스',
    'startnodenm': '성보교통앞'},
   {'endnodenm': '진밭골(종점)2',
    'routeid': 'DGB3000814001',
    'routeno': 814,
    'routetp': '간선버스',
    'startnodenm': '대구대(정문1)'},
   {'endnodenm': '신흥버스',
    'routeid': 'DGB3000156000',
    'routeno': 156,
    'routetp': '간선버스',
    'startnodenm': '신덕마을입구건너'}]},
 'numOfRows': 10,
 'pageNo': 1,
 'totalCount': 13}

In [21]:
df_items = df_body['items']['item']
df_items

[{'endnodenm': '동호공영차고지건너',
  'routeid': 'DGB4060003002',
  'routeno': '북구3',
  'routetp': '지선버스',
  'startnodenm': '노곡동'},
 {'endnodenm': '동호공영차고지건너',
  'routeid': 'DGB3000708002',
  'routeno': 708,
  'routetp': '간선버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '반야월역(3번출구)',
  'routeid': 'DGB3000805000',
  'routeno': 805,
  'routetp': '간선버스',
  'startnodenm': '달서아트센터앞'},
 {'endnodenm': '유통단지회차지',
  'routeid': 'DGB3000413001',
  'routeno': 413,
  'routetp': '간선버스',
  'startnodenm': '가창초등학교앞'},
 {'endnodenm': '동대구역',
  'routeid': 'DGB3001814000',
  'routeno': 8140,
  'routetp': '일반버스',
  'startnodenm': 'TBC건너'},
 {'endnodenm': '성보교통건너',
  'routeid': 'DGB4060006000',
  'routeno': '북구6',
  'routetp': '지선버스',
  'startnodenm': '성보교통앞'},
 {'endnodenm': '동대구역(2번출구)건너',
  'routeid': 'DGB3000650005',
  'routeno': 650,
  'routetp': '간선버스',
  'startnodenm': '다산(종점)'},
 {'endnodenm': '성보교통건너',
  'routeid': 'DGB2000002100',
  'routeno': '순환2-1',
  'routetp': '순환버스',
  'startnodenm': '성보교통앞'},
 {'endnodenm': '진밭골(종점)2',
  'routeid': 'DGB3000814001',
  'routeno': 814,
  'routetp': '간선버스',
  'startnodenm': '대구대(정문1)'},
 {'endnodenm': '신흥버스',
  'routeid': 'DGB3000156000',
  'routeno': 156,
  'routetp': '간선버스',
  'startnodenm': '신덕마을입구건너'}]

In [32]:
df_raw = pd.DataFrame(df_items)
df_raw

      endnodenm        routeid routeno routetp  startnodenm
0     동호공영차고지건너  DGB4060003002     북구3    지선버스          노곡동
1     동호공영차고지건너  DGB3000708002     708    간선버스  북구 동호동(종점)1
2    반야월역(3번출구)  DGB3000805000     805    간선버스      달서아트센터앞
3       유통단지회차지  DGB3000413001     413    간선버스      가창초등학교앞
4          동대구역  DGB3001814000    8140    일반버스        TBC건너
5        성보교통건너  DGB4060006000     북구6    지선버스        성보교통앞
6  동대구역(2번출구)건너  DGB3000650005     650    간선버스       다산(종점)
7        성보교통건너  DGB2000002100   순환2-1    순환버스        성보교통앞
8      진밭골(종점)2  DGB3000814001     814    간선버스     대구대(정문1)
9          신흥버스  DGB3000156000     156    간선버스     신덕마을입구건너

## 컬럼 이름 바꾸기

In [37]:
COLUMN_NAME = {
    'endnodenm':'종점',
    'routeid':'노선ID',
    'routeno':'노선번호',
    'routetp':'노선유형',
    'startnodenm':'기점'
}
df = df_raw.rename(columns=COLUMN_NAME)
df

             종점           노선ID   노선번호  노선유형           기점
0     동호공영차고지건너  DGB4060003002    북구3  지선버스          노곡동
1     동호공영차고지건너  DGB3000708002    708  간선버스  북구 동호동(종점)1
2    반야월역(3번출구)  DGB3000805000    805  간선버스      달서아트센터앞
3       유통단지회차지  DGB3000413001    413  간선버스      가창초등학교앞
4          동대구역  DGB3001814000   8140  일반버스        TBC건너
5        성보교통건너  DGB4060006000    북구6  지선버스        성보교통앞
6  동대구역(2번출구)건너  DGB3000650005    650  간선버스       다산(종점)
7        성보교통건너  DGB2000002100  순환2-1  순환버스        성보교통앞
8      진밭골(종점)2  DGB3000814001    814  간선버스     대구대(정문1)
9          신흥버스  DGB3000156000    156  간선버스     신덕마을입구건너

## 노선 관련 컬럼 추출

In [38]:
df_route = df[['노선ID', '노선번호']]
df_route

            노선ID   노선번호
0  DGB4060003002    북구3
1  DGB3000708002    708
2  DGB3000805000    805
3  DGB3000413001    413
4  DGB3001814000   8140
5  DGB4060006000    북구6
6  DGB3000650005    650
7  DGB2000002100  순환2-1
8  DGB3000814001    814
9  DGB3000156000    156

## 파생컬럼 추가

In [40]:
df_route['정류소ID'] = NODE_ID
df_route

            노선ID   노선번호          정류소ID
0  DGB4060003002    북구3  DGB7011006700
1  DGB3000708002    708  DGB7011006700
2  DGB3000805000    805  DGB7011006700
3  DGB3000413001    413  DGB7011006700
4  DGB3001814000   8140  DGB7011006700
5  DGB4060006000    북구6  DGB7011006700
6  DGB3000650005    650  DGB7011006700
7  DGB2000002100  순환2-1  DGB7011006700
8  DGB3000814001    814  DGB7011006700
9  DGB3000156000    156  DGB7011006700

In [43]:
df_route['정류소명'] = NODE_NAME
df_route

            노선ID   노선번호          정류소ID  정류소명
0  DGB4060003002    북구3  DGB7011006700  동대구역
1  DGB3000708002    708  DGB7011006700  동대구역
2  DGB3000805000    805  DGB7011006700  동대구역
3  DGB3000413001    413  DGB7011006700  동대구역
4  DGB3001814000   8140  DGB7011006700  동대구역
5  DGB4060006000    북구6  DGB7011006700  동대구역
6  DGB3000650005    650  DGB7011006700  동대구역
7  DGB2000002100  순환2-1  DGB7011006700  동대구역
8  DGB3000814001    814  DGB7011006700  동대구역
9  DGB3000156000    156  DGB7011006700  동대구역

# DB 저장

In [44]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)
            
    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공')
        print(version[:80] + '...')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
    print(f'저장 완료 : {saved_count}행')
    print(f'DB : busapidb / table : {table_name}')

In [45]:
save_to_postgresql(df_route, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 : 10행
DB : busapidb / table : route_by_stop

# CSV 저장

In [48]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df_route.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('CSV 저장 완료')

CSV 저장 완료