In [122]:
import os, math, time
import pandas as pd
import requests
from datetime import date
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

# API 키 불러오기

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료 : {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('API 키를 설정하세요')

API 키 로드 완료 : 0f4cc2...0ab9

# API 연결 확인

In [3]:
BASE_URL = 'https://apis.data.go.kr/1613000/BusRouteInfoInqireService/getCtyCodeList'

response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json'})
response.raise_for_status

In [4]:
response.status_code

200

In [5]:
response.json()

{'response': {'header': {'resultCode': 99,
   'resultMsg': '가용한 세션이 존재하지 않습니다. (30/30)'},
  'body': ''}}

# 환경 설정

In [6]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusRouteInfoInqireService/getRouteNoList'
CITY_CODE = 22
ROWS_PER_PAGE = 100

In [7]:
BASE_DIR = os.getcwd()
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'bus.csv')

print(f'CSV 저장 경로 : {OUTPUT_PATH}')

CSV 저장 경로 : c:\Users\Administrator\bigdata2026\fastapi\bus_pipeline\output\bus.csv

In [8]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/bigdatatestdb'
TABLE_NAME = 'bus'

# 원본 데이터 확인

In [9]:
response = requests.get(BASE_URL,
                        params={
                            'serviceKey':API_KEY,
                            'pageNo':1,
                            'numOfRows':10,
                            '_type':'json',
                            'cityCode':22
                        })
response.status_code

200

In [18]:
data = response.json()
data['response']['body']

{'items': {'item': [{'endnodenm': '동명교통',
    'endvehicletime': 1433,
    'routeid': 'DGB4090003021',
    'routeno': '칠곡3[동명-칠곡시장-동명-기성-대구은행연수원-동명]',
    'routetp': '지선버스',
    'startnodenm': '동명교통',
    'startvehicletime': 1131},
   {'endnodenm': '동명교통',
    'endvehicletime': '0630',
    'routeid': 'DGB4090003023',
    'routeno': '칠곡3[하판-동명-기성-동명]',
    'routetp': '지선버스',
    'startnodenm': '송학교입구',
    'startvehicletime': '0630'},
   {'endnodenm': '도남동(종점)',
    'endvehicletime': 2114,
    'routeid': 'DGB4090005000',
    'routeno': '칠곡5',
    'routetp': '지선버스',
    'startnodenm': '도남동(종점)',
    'startvehicletime': '0809'},
   {'endnodenm': '도남동(종점)',
    'endvehicletime': 1704,
    'routeid': 'DGB4090005001',
    'routeno': '칠곡5[도남-팔거역-도남]',
    'routetp': '지선버스',
    'startnodenm': '도남동(종점)',
    'startvehicletime': '0530'},
   {'endnodenm': '동화시설집단지구(종점)2(대구시민안전테마파크)',
    'endvehicletime': 1849,
    'routeid': 'DGB4100001020',
    'routeno': '팔공1[동화사]',
    'routetp': '지선버스',
    'startnodenm': '칠성고가도로하단',
    'startvehicletime': '0948'},
   {'endnodenm': '팔공학생야영장앞',
    'endvehicletime': 2135,
    'routeid': 'DGB4100001021',
    'routeno': '팔공1[신무동]',
    'routetp': '지선버스',
    'startnodenm': '칠성고가도로하단',
    'startvehicletime': '0659'},
   {'endnodenm': '능성동(종점)2',
    'endvehicletime': 2007,
    'routeid': 'DGB4100001022',
    'routeno': '팔공1[능성동]',
    'routetp': '지선버스',
    'startnodenm': '칠성고가도로하단',
    'startvehicletime': '0638'},
   {'endnodenm': '평광종점',
    'endvehicletime': 2216,
    'routeid': 'DGB4100001023',
    'routeno': '팔공1[평광동]',
    'routetp': '지선버스',
    'startnodenm': '칠성고가도로하단',
    'startvehicletime': '0551'},
   {'endnodenm': '동화시설집단지구(종점)2(대구시민안전테마파크)',
    'endvehicletime': '0755',
    'routeid': 'DGB4100001024',
    'routeno': '팔공1[동화사(국가정보자원관리원경유,오전)]',
    'routetp': '지선버스',
    'startnodenm': '칠성고가도로하단',
    'startvehicletime': '0755'},
   {'endnodenm': '동화시설집단지구(종점)2(대구시민안전테마파크)',
    'endvehicletime': 1657,
    'routeid': 'DGB4100001025',
    'routeno': '팔공1[동화사(국가정보자원관리원경유, 오후)]',
    'routetp': '지선버스',
    'startnodenm': '칠성고가도로하단',
    'startvehicletime': 1657}]},
 'numOfRows': 10,
 'pageNo': 1,
 'totalCount': 232}

In [17]:
totalCount = data['response']['body']['totalCount']
totalPages = math.ceil(totalCount / ROWS_PER_PAGE)

print(f'데이터 총 개수 : {totalCount}개')
print(f'총 페이지 수 : {totalPages}페이지')

데이터 총 개수 : 232개
총 페이지 수 : 3페이지

In [ ]:
all_items = []
for page_no in range(1, totalPages+1):
    params = {
                'serviceKey':API_KEY,
                'pageNo':page_no,
                'numOfRows':ROWS_PER_PAGE,
                '_type':'json',
                'cityCode':22
    }

    response = requests.get(BASE_URL, params=params)
    response.raise_for_status

    page_body = response.json()['response']['body']
    if not page_body.get('items'):
        print(f'{page_no}/{totalPages}페이지 없음')
        continue

    page_item = page_body['items'].get('item', [])
    if isinstance(page_item, dict):
        page_item = [page_item]

    all_items.extend(page_item)

    print(f'{page_no}/{totalPages}페이지 수집 완료 : 누적 개수 {len(all_items)}개')
    time.sleep(0.2)

print(f'총 수집 개수 : {len(all_items)}개')

1/3페이지 수집 완료 : 누적 개수 100개
2/3페이지 수집 완료 : 누적 개수 200개
3/3페이지 수집 완료 : 누적 개수 232개
총 수집 개수 : 232개

# 데이터프레임 생성 및 구조 변환

In [127]:
df_raw = pd.DataFrame(all_items)
df_raw.head()

,endnodenm,endvehicletime,routeid,routeno,routetp,startnodenm,startvehicletime
0,동명교통,1433,DGB4090003021,칠곡3[동명-칠곡시장-동명-기성-대구은행연수원-동명],지선버스,동명교통,1131
1,동명교통,0630,DGB4090003023,칠곡3[하판-동명-기성-동명],지선버스,송학교입구,0630
2,도남동(종점),2114,DGB4090005000,칠곡5,지선버스,도남동(종점),0809
3,도남동(종점),1704,DGB4090005001,칠곡5[도남-팔거역-도남],지선버스,도남동(종점),0530
4,동화시설집단지구(종점)2(대구시민안전테마파크),1849,DGB4100001020,팔공1[동화사],지선버스,칠성고가도로하단,0948

In [128]:
df_raw.dtypes

endnodenm              str
endvehicletime      object
routeid                str
routeno             object
routetp                str
startnodenm            str
startvehicletime    object
dtype: object

In [129]:
COLUMNS = {
    'endnodenm':'종점',
    'endvehicletime':'막차시간',
    'routeid':'노선ID',
    'routeno':'노선번호',
    'routetp':'노선유형',
    'startnodenm':'기점',
    'startvehicletime':'첫차시간'
}
df = df_raw.rename(columns=COLUMNS)
df.head()

,종점,막차시간,노선ID,노선번호,노선유형,기점,첫차시간
0,동명교통,1433,DGB4090003021,칠곡3[동명-칠곡시장-동명-기성-대구은행연수원-동명],지선버스,동명교통,1131
1,동명교통,0630,DGB4090003023,칠곡3[하판-동명-기성-동명],지선버스,송학교입구,0630
2,도남동(종점),2114,DGB4090005000,칠곡5,지선버스,도남동(종점),0809
3,도남동(종점),1704,DGB4090005001,칠곡5[도남-팔거역-도남],지선버스,도남동(종점),0530
4,동화시설집단지구(종점)2(대구시민안전테마파크),1849,DGB4100001020,팔공1[동화사],지선버스,칠성고가도로하단,0948

In [130]:
df_route = df[['노선ID', '노선번호', '기점', '종점']]
df_route.head()

,노선ID,노선번호,기점,종점
0,DGB4090003021,칠곡3[동명-칠곡시장-동명-기성-대구은행연수원-동명],동명교통,동명교통
1,DGB4090003023,칠곡3[하판-동명-기성-동명],송학교입구,동명교통
2,DGB4090005000,칠곡5,도남동(종점),도남동(종점)
3,DGB4090005001,칠곡5[도남-팔거역-도남],도남동(종점),도남동(종점)
4,DGB4100001020,팔공1[동화사],칠성고가도로하단,동화시설집단지구(종점)2(대구시민안전테마파크)

# 파생컬럼 추가

In [134]:
date.today()

datetime.date(2026, 7, 3)

In [139]:
df_route['수집일시'] = str(date.today())
df_route

,노선ID,노선번호,기점,종점,수집일시
0,DGB4090003021,칠곡3[동명-칠곡시장-동명-기성-대구은행연수원-동명],동명교통,동명교통,2026-07-03
1,DGB4090003023,칠곡3[하판-동명-기성-동명],송학교입구,동명교통,2026-07-03
2,DGB4090005000,칠곡5,도남동(종점),도남동(종점),2026-07-03
3,DGB4090005001,칠곡5[도남-팔거역-도남],도남동(종점),도남동(종점),2026-07-03
4,DGB4100001020,팔공1[동화사],칠성고가도로하단,동화시설집단지구(종점)2(대구시민안전테마파크),2026-07-03
...,...,...,...,...,...
227,DGB4010002004,가창2[정대방면],칠성고가도로하단,칠성고가도로하단,2026-07-03
228,DGB4010002118,가창2[단산(냉천)방면],칠성고가도로하단,칠성고가도로하단,2026-07-03
229,DGB4030001000,달서1,대천공영차고지앞,매곡(종점),2026-07-03
230,DGB4030002002,달서2,남도버스1,앞산공원,2026-07-03
231,DGB4030003002,달서3,신흥버스,화원유원지(사문진주막촌),2026-07-03

# DB 저장

In [136]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(col):
            df_save[col] = df_save[col].astype(str)
    
    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print(version[:80] + '...')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
    print(f'저장 완료 : {saved_count}행')
    print(f'DB : databasetestdb / table : {table_name}')

In [137]:
save_to_postgresql(df_route, DB_URL, TABLE_NAME)

PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 : 232행
DB : databasetestdb / table : bus

In [138]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df_route.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('CSV 파일 저장 완료')

CSV 파일 저장 완료