# 대구 버스 정류소 데이터 수집 파이프라인 - 정류소별 경유노선 API

### 요구사항

1. 정류소ID 1개를 골라서 API를 1회 호출하고, 응답 JSON 구조를 직접 확인하시오.
2. 응답에서 노선 관련 정보만 담긴 리스트를 꺼내 DataFrame으로 만드시오.
3. DataFrame에서 **노선번호에 해당하는 컬럼**과 **노선ID에 해당하는 컬럼**만 선택하시오.

- 정확한 컬럼명은 2번에서 확인한 실제 응답을 보고 판단하시오.

1. 선택한 DataFrame에 **어떤 정류소를 조회했는지 알 수 있도록** `node_id` 컬럼을 추가하시오.
2. 선택한 데이터를 PostgreSQL `busapidb`에 `route_by_stop`이라는 이름의 테이블로 저장하시오.
3. 저장 후 pgAdmin에서 테이블과 데이터를 직접 확인하시오.

In [1]:
import math
import os
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env파일에 API키를 설정하세요.')

API 키 로드 완료: a38c7e...f975

In [6]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'

In [7]:
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json', 'nodeid':'정류소ID'})
response.raise_for_status()

In [8]:
print(response.status_code)

200

In [10]:
response = requests.get('http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getCtyCodeList',
                        params={'serviceKey':API_KEY, '_type':'json'})                  
response

In [11]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'citycode': 12, 'cityname': '세종특별시'},
     {'citycode': 21, 'cityname': '부산광역시'},
     {'citycode': 22, 'cityname': '대구광역시'},
     {'citycode': 23, 'cityname': '인천광역시'},
     {'citycode': 24, 'cityname': '광주광역시'},
     {'citycode': 25, 'cityname': '대전광역시/계룡시'},
     {'citycode': 26, 'cityname': '울산광역시'},
     {'citycode': 39, 'cityname': '제주도'},
     {'citycode': 31010, 'cityname': '수원시'},
     {'citycode': 31020, 'cityname': '성남시'},
     {'citycode': 31030, 'cityname': '의정부시'},
     {'citycode': 31040, 'cityname': '안양시'},
     {'citycode': 31050, 'cityname': '부천시'},
     {'citycode': 31060, 'cityname': '광명시'},
     {'citycode': 31070, 'cityname': '평택시'},
     {'citycode': 31080, 'cityname': '동두천시'},
     {'citycode': 31090, 'cityname': '안산시'},
     {'citycode': 31100, 'cityname': '고양시'},
     {'citycode': 31110, 'cityname': '과천시'},
     {'citycode': 31120, 'cityname': '구리시'},
     {'citycode': 31130, 'cityname': '남양주시'},
     {'citycode': 31140, 'cityname': '오산시'},
     {'citycode': 31150, 'cityname': '시흥시'},
     {'citycode': 31160, 'cityname': '군포시'},
     {'citycode': 31170, 'cityname': '의왕시'},
     {'citycode': 31180, 'cityname': '하남시'},
     {'citycode': 31190, 'cityname': '용인시'},
     {'citycode': 31200, 'cityname': '파주시'},
     {'citycode': 31210, 'cityname': '이천시'},
     {'citycode': 31220, 'cityname': '안성시'},
     {'citycode': 31230, 'cityname': '김포시'},
     {'citycode': 31240, 'cityname': '화성시'},
     {'citycode': 31250, 'cityname': '광주시'},
     {'citycode': 31260, 'cityname': '양주시'},
     {'citycode': 31270, 'cityname': '포천시'},
     {'citycode': 31320, 'cityname': '여주시'},
     {'citycode': 31350, 'cityname': '연천군'},
     {'citycode': 31370, 'cityname': '가평군'},
     {'citycode': 31380, 'cityname': '양평군'},
     {'citycode': 32010, 'cityname': '춘천시'},
     {'citycode': 32020, 'cityname': '원주시/횡성군'},
     {'citycode': 32050, 'cityname': '태백시'},
     {'citycode': 32310, 'cityname': '홍천군'},
     {'citycode': 32360, 'cityname': '철원군'},
     {'citycode': 32410, 'cityname': '양양군'},
     {'citycode': 33010, 'cityname': '청주시'},
     {'citycode': 33020, 'cityname': '충주시'},
     {'citycode': 33030, 'cityname': '제천시'},
     {'citycode': 33320, 'cityname': '보은군'},
     {'citycode': 33330, 'cityname': '옥천군'},
     {'citycode': 33340, 'cityname': '영동군'},
     {'citycode': 33350, 'cityname': '진천군'},
     {'citycode': 33360, 'cityname': '괴산군'},
     {'citycode': 33370, 'cityname': '음성군'},
     {'citycode': 33380, 'cityname': '단양군'},
     {'citycode': 34010, 'cityname': '천안시'},
     {'citycode': 34020, 'cityname': '공주시'},
     {'citycode': 34030, 'cityname': '보령시'},
     {'citycode': 34040, 'cityname': '아산시'},
     {'citycode': 34050, 'cityname': '서산시'},
     {'citycode': 34060, 'cityname': '논산시'},
     {'citycode': 34070, 'cityname': '계룡시'},
     {'citycode': 34310, 'cityname': '금산군'},
     {'citycode': 34330, 'cityname': '부여군'},
     {'citycode': 34340, 'cityname': '서천군'},
     {'citycode': 34350, 'cityname': '청양군'},
     {'citycode': 34380, 'cityname': '태안군'},
     {'citycode': 34390, 'cityname': '당진시'},
     {'citycode': 35010, 'cityname': '전주시'},
     {'citycode': 35020, 'cityname': '군산시'},
     {'citycode': 35030, 'cityname': '익산시'},
     {'citycode': 35040, 'cityname': '정읍시'},
     {'citycode': 35050, 'cityname': '남원시'},
     {'citycode': 35060, 'cityname': '김제시'},
     {'citycode': 35320, 'cityname': '진안군'},
     {'citycode': 35330, 'cityname': '무주군'},
     {'citycode': 35340, 'cityname': '장수군'},
     {'citycode': 35350, 'cityname': '임실군'},
     {'citycode': 35360, 'cityname': '순창군'},
     {'citycode': 35370, 'cityname': '고창군'},
     {'citycode': 35380, 'cityname': '부안군'},
     {'citycode': 36010, 'cityname': '목포시'},
     {'citycode': 36020, 'cityname': '여수시'},
     {'citycode': 36030, 'cityname': '순천시'},
     {'citycode': 36040, 'cityname': '나주시'},
     {'citycode': 36060, 'cityname': '광양시'},
     {'citycode': 36320, 'cityname': '곡성군'},
     {'citycode': 36330, 'cityname': '구례군'},
     {'citycode': 36350, 'cityname': '고흥군'},
     {'citycode': 36380, 'cityname': '장흥군'},
     {'citycode': 36400, 'cityname': '해남군'},
     {'citycode': 36410, 'cityname': '영암군'},
     {'citycode': 36420, 'cityname': '무안군'},
     {'citycode': 36430, 'cityname': '함평군'},
     {'citycode': 36450, 'cityname': '장성군'},
     {'citycode': 36460, 'cityname': '완도군'},
     {'citycode': 36470, 'cityname': '진도군'},
     {'citycode': 36480, 'cityname': '신안군'},
     {'citycode': 37010, 'cityname': '포항시'},
     {'citycode': 37020, 'cityname': '경주시'},
     {'citycode': 37030, 'cityname': '김천시'},
     {'citycode': 37040, 'cityname': '안동시'},
     {'citycode': 37050, 'cityname': '구미시'},
     {'citycode': 37060, 'cityname': '영주시'},
     {'citycode': 37070, 'cityname': '영천시'},
     {'citycode': 37080, 'cityname': '상주시'},
     {'citycode': 37090, 'cityname': '문경시'},
     {'citycode': 37100, 'cityname': '경산시'},
     {'citycode': 37320, 'cityname': '의성군'},
     {'citycode': 37330, 'cityname': '청송군'},
     {'citycode': 37340, 'cityname': '영양군'},
     {'citycode': 37350, 'cityname': '영덕군'},
     {'citycode': 37360, 'cityname': '청도군'},
     {'citycode': 37370, 'cityname': '고령군'},
     {'citycode': 37380, 'cityname': '성주군'},
     {'citycode': 37390, 'cityname': '칠곡군'},
     {'citycode': 37400, 'cityname': '예천군'},
     {'citycode': 37410, 'cityname': '봉화군'},
     {'citycode': 37420, 'cityname': '울진군'},
     {'citycode': 37430, 'cityname': '울릉군'},
     {'citycode': 38010, 'cityname': '창원시'},
     {'citycode': 38030, 'cityname': '진주시'},
     {'citycode': 38050, 'cityname': '통영시'},
     {'citycode': 38060, 'cityname': '사천시'},
     {'citycode': 38070, 'cityname': '김해시'},
     {'citycode': 38080, 'cityname': '밀양시'},
     {'citycode': 38090, 'cityname': '거제시'},
     {'citycode': 38100, 'cityname': '양산시'},
     {'citycode': 38310, 'cityname': '의령군'},
     {'citycode': 38320, 'cityname': '함안군'},
     {'citycode': 38330, 'cityname': '창녕군'},
     {'citycode': 38340, 'cityname': '고성군'},
     {'citycode': 38350, 'cityname': '남해군'},
     {'citycode': 38360, 'cityname': '하동군'},
     {'citycode': 38370, 'cityname': '산청군'},
     {'citycode': 38380, 'cityname': '함양군'},
     {'citycode': 38390, 'cityname': '거창군'},
     {'citycode': 38400, 'cityname': '합천군'}]}}}}

In [43]:
response = requests.get(BASE_URL, 
                        params={'serviceKey': API_KEY,
                                'pageNo': 1,
                                'numOfRows': 10,
                                '_type': 'json', # json형식
                                'cityCode': 22, # 대구가 22번
                                'nodeid':'TARGET_NODE_ID'}) #  정류소 ID
response

In [58]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
      'routeid': 'DGB1000001000',
      'routeno': '급행1',
      'routetp': '급행버스',
      'startnodenm': '동화시설집단지구(종점)1'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000002001',
      'routeno': '급행2',
      'routetp': '급행버스',
      'startnodenm': '냉천전원음식점지구'},
     {'endnodenm': '동명교통',
      'routeid': 'DGB1000003000',
      'routeno': '급행3',
      'routetp': '급행버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB1000005000',
      'routeno': '급행5',
      'routetp': '급행버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000007000',
      'routeno': '급행7',
      'routetp': '급행버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB1000008004',
      'routeno': '급행8',
      'routetp': '급행버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '진천역(2번출구)',
      'routeid': 'DGB1000008101',
      'routeno': '급행8-1',
      'routetp': '급행버스',
      'startnodenm': '유곡리공영차고지앞'},
     {'endnodenm': '군위군청',
      'routeid': 'DGB1000009002',
      'routeno': '급행9',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '우보버스정류장',
      'routeid': 'DGB1000009100',
      'routeno': '급행9-1',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '삼국유사면문화관',
      'routeid': 'DGB1000009200',
      'routeno': '급행9-2',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '소보시장',
      'routeid': 'DGB1000009300',
      'routeno': '급행9-3',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB1000010000',
      'routeno': '급행10',
      'routetp': '급행버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002000',
      'routeno': '순환2',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002100',
      'routeno': '순환2-1',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB2000003000',
      'routeno': '순환3',
      'routetp': '순환버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB2000003100',
      'routeno': '순환3-1',
      'routetp': '순환버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101011',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101012',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101013',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101016',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101017',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101018',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101019',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101020',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101110',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101111',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101112',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101113',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101114',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101115',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101116',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101117',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000156000',
      'routeno': 156,
      'routetp': '간선버스',
      'startnodenm': '신덕마을입구건너'},
     {'endnodenm': '금호지구종점(종점방향)',
      'routeid': 'DGB3000204000',
      'routeno': 204,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000232000',
      'routeno': 232,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '냉천전원음식점지구',
      'routeid': 'DGB3000240001',
      'routeno': 240,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000300000',
      'routeno': 300,
      'routetp': '간선버스',
      'startnodenm': '유통단지회차지2'},
     {'endnodenm': '가창초등학교건너',
      'routeid': 'DGB3000304001',
      'routeno': 304,
      'routetp': '간선버스',
      'startnodenm': '유통단지회차지2'},
     {'endnodenm': '대곡공원건너',
      'routeid': 'DGB3000306000',
      'routeno': 306,
      'routetp': '간선버스',
      'startnodenm': '유통단지회차지2'},
     {'endnodenm': '부적주공A 건너',
      'routeid': 'DGB3000309002',
      'routeno': 309,
      'routetp': '간선버스',
      'startnodenm': '서대구역(남측)1'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000320000',
      'routeno': 320,
      'routetp': '간선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000323101',
      'routeno': '232-1',
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000326000',
      'routeno': 326,
      'routetp': '간선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000349000',
      'routeno': 349,
      'routetp': '간선버스',
      'startnodenm': '덕원고등학교앞2'},
     {'endnodenm': '월광수변공원',
      'routeid': 'DGB3000356000',
      'routeno': 356,
      'routetp': '간선버스',
      'startnodenm': '조야동(종점)'},
     {'endnodenm': '갓바위',
      'routeid': 'DGB3000401000',
      'routeno': 401,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '갓바위',
      'routeid': 'DGB3000401078',
      'routeno': 401,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '갓바위',
      'routeid': 'DGB3000401079',
      'routeno': 401,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB3000402001',
      'routeno': 402,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '조야동(종점)',
      'routeid': 'DGB3000403001',
      'routeno': 403,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000405004',
      'routeno': 405,
      'routetp': '간선버스',
      'startnodenm': '삼산리(세왕교통1)'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000410000',
      'routeno': 410,
      'routetp': '간선버스',
      'startnodenm': '앞산공원'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000410100',
      'routeno': '410-1',
      'routetp': '간선버스',
      'startnodenm': '앞산공원'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000413001',
      'routeno': 413,
      'routetp': '간선버스',
      'startnodenm': '가창초등학교앞'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000425000',
      'routeno': 425,
      'routetp': '간선버스',
      'startnodenm': '황금고가교네거리'},
     {'endnodenm': '연경동종점1',
      'routeid': 'DGB3000501000',
      'routeno': 501,
      'routetp': '간선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000503001',
      'routeno': 503,
      'routetp': '간선버스',
      'startnodenm': '연경동종점2'},
     {'endnodenm': '두리봉터널종점',
      'routeid': 'DGB3000504000',
      'routeno': 504,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '소라아파트 건너',
      'routeid': 'DGB3000509002',
      'routeno': 509,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '안심역(4번출구)',
      'routeid': 'DGB3000518002',
      'routeno': 518,
      'routetp': '간선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000520000',
      'routeno': 520,
      'routetp': '간선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000523002',
      'routeno': 523,
      'routetp': '간선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '동명교통',
      'routeid': 'DGB3000527000',
      'routeno': 527,
      'routetp': '간선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB3000564000',
      'routeno': 564,
      'routetp': '간선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000609007',
      'routeno': 609,
      'routetp': '간선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000618003',
      'routeno': 618,
      'routetp': '간선버스',
      'startnodenm': '대곡주공8단지건너'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB3000623002',
      'routeno': 623,
      'routetp': '간선버스',
      'startnodenm': '달성군청건너'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000649000',
      'routeno': 649,
      'routetp': '간선버스',
      'startnodenm': '대곡공원앞'},
     {'endnodenm': '동대구역(2번출구)건너',
      'routeid': 'DGB3000650005',
      'routeno': 650,
      'routetp': '간선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000651000',
      'routeno': 651,
      'routetp': '간선버스',
      'startnodenm': '명곡미래빌1단지'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB3000653000',
      'routeno': 653,
      'routetp': '간선버스',
      'startnodenm': '설화리(종점)1'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000655000',
      'routeno': 655,
      'routetp': '간선버스',
      'startnodenm': '유곡리공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB3000665000',
      'routeno': 665,
      'routetp': '간선버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB3000665003',
      'routeno': 665,
      'routetp': '간선버스',
      'startnodenm': '대곡역(1번출구)'},
     {'endnodenm': '대곡주공8단지앞',
      'routeid': 'DGB3000706001',
      'routeno': 706,
      'routetp': '간선버스',
      'startnodenm': '관음변전소2'},
     {'endnodenm': '관음변전소4',
      'routeid': 'DGB3000707000',
      'routeno': 707,
      'routetp': '간선버스',
      'startnodenm': '관음변전소3'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000708002',
      'routeno': 708,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000719001',
      'routeno': 719,
      'routetp': '간선버스',
      'startnodenm': '칠곡우방타운건너(종점)'},
     {'endnodenm': '덕원고등학교건너',
      'routeid': 'DGB3000724000',
      'routeno': 724,
      'routetp': '간선버스',
      'startnodenm': '칠곡우방타운건너(종점)'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000725000',
      'routeno': 725,
      'routetp': '일반버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '대곡주공8단지앞',
      'routeid': 'DGB3000726000',
      'routeno': 726,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '대덕맨션앞',
      'routeid': 'DGB3000730002',
      'routeno': 730,
      'routetp': '간선버스',
      'startnodenm': '동명교통'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB3000802000',
      'routeno': 802,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000805000',
      'routeno': 805,
      'routetp': '간선버스',
      'startnodenm': '달서아트센터앞'},
     {'endnodenm': '진밭골(종점)2',
      'routeid': 'DGB3000814001',
      'routeno': 814,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '대천교',
      'routeid': 'DGB3000836001',
      'routeno': 836,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848000',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '금강동',
      'routeid': 'DGB3000848001',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848002',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'},
     {'endnodenm': '금강동',
      'routeid': 'DGB3000848003',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB3000894000',
      'routeno': 894,
      'routetp': '간선버스',
      'startnodenm': '경일대종점'},
     {'endnodenm': '관음변전소1',
      'routeid': 'DGB3000937000',
      'routeno': 937,
      'routetp': '간선버스',
      'startnodenm': '덕원고등학교앞2'},
     {'endnodenm': '모다아울렛앞',
      'routeid': 'DGB3001725000',
      'routeno': 7250,
      'routetp': '일반버스',
      'startnodenm': '태전역2'},
     {'endnodenm': '동대구역',
      'routeid': 'DGB3001814000',
      'routeno': 8140,
      'routetp': '일반버스',
      'startnodenm': 'TBC건너'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002001',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002003',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002004',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002118',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB4030001000',
      'routeno': '달서1',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB4030002002',
      'routeno': '달서2',
      'routetp': '지선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '화원유원지(사문진주막촌)',
      'routeid': 'DGB4030003002',
      'routeno': '달서3',
      'routetp': '지선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB4030005001',
      'routeno': '달서5',
      'routetp': '지선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '남도버스2',
      'routeid': 'DGB4030006000',
      'routeno': '달서6',
      'routetp': '지선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001006',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001007',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001008',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001009',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002044',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002045',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002046',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002047',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002048',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '현풍공영버스정류장1',
      'routeid': 'DGB4040003002',
      'routeno': '달성3',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '현풍공영버스정류장1',
      'routeid': 'DGB4040003003',
      'routeno': '달성3',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '구지119안전센터건너',
      'routeid': 'DGB4040004006',
      'routeno': '달성4',
      'routetp': '지선버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005000',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '유천교1',
      'routeid': 'DGB4040005001',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유가사(종점)'},
     {'endnodenm': '유천교1',
      'routeid': 'DGB4040005002',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유가사(종점)'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005003',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005070',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '유천교1',
      'routeid': 'DGB4040005071',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유가사(종점)'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005072',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '본말(종점)',
      'routeid': 'DGB4040006022',
      'routeno': '달성6',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '유산리',
      'routeid': 'DGB4040007011',
      'routeno': '달성7',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '조일고등학교(종점)',
      'routeid': 'DGB4050001001',
      'routeno': '동구1',
      'routetp': '지선버스',
      'startnodenm': '조일고등학교(종점)'},
     {'endnodenm': '조일고등학교(종점)',
      'routeid': 'DGB4050001101',
      'routeno': '동구1-1',
      'routetp': '지선버스',
      'startnodenm': '조일고등학교(종점)'},
     {'endnodenm': '부동(종점)',
      'routeid': 'DGB4050003000',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '경주최씨종가(종점)',
      'routeid': 'DGB4050003001',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': 'K2관사입구(종점)',
      'routeid': 'DGB4050003002',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '구둔산',
      'routeid': 'DGB4050003003',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': 'K2관사입구(종점)',
      'routeid': 'DGB4050003004',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB4050004000',
      'routeno': '동구4',
      'routetp': '지선버스',
      'startnodenm': '반야월역(4번출구)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB4050004100',
      'routeno': '동구4-1',
      'routetp': '지선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '매여동(동구)저탄장',
      'routeid': 'DGB4050005000',
      'routeno': '동구5',
      'routetp': '지선버스',
      'startnodenm': '매여동(동구)저탄장'},
     {'endnodenm': '용계삼거리1',
      'routeid': 'DGB4050005100',
      'routeno': '동구5',
      'routetp': '지선버스',
      'startnodenm': '매여동(동구)저탄장'},
     {'endnodenm': '안심역(5번출구)',
      'routeid': 'DGB4050006000',
      'routeno': '동구6',
      'routetp': '지선버스',
      'startnodenm': 'LH14단지아파트'},
     {'endnodenm': '안심역(5번출구)',

In [56]:
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
      'routeid': 'DGB1000001000',
      'routeno': '급행1',
      'routetp': '급행버스',
      'startnodenm': '동화시설집단지구(종점)1'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000002001',
      'routeno': '급행2',
      'routetp': '급행버스',
      'startnodenm': '냉천전원음식점지구'},
     {'endnodenm': '동명교통',
      'routeid': 'DGB1000003000',
      'routeno': '급행3',
      'routetp': '급행버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB1000005000',
      'routeno': '급행5',
      'routetp': '급행버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000007000',
      'routeno': '급행7',
      'routetp': '급행버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB1000008004',
      'routeno': '급행8',
      'routetp': '급행버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '진천역(2번출구)',
      'routeid': 'DGB1000008101',
      'routeno': '급행8-1',
      'routetp': '급행버스',
      'startnodenm': '유곡리공영차고지앞'},
     {'endnodenm': '군위군청',
      'routeid': 'DGB1000009002',
      'routeno': '급행9',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '우보버스정류장',
      'routeid': 'DGB1000009100',
      'routeno': '급행9-1',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '삼국유사면문화관',
      'routeid': 'DGB1000009200',
      'routeno': '급행9-2',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '소보시장',
      'routeid': 'DGB1000009300',
      'routeno': '급행9-3',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB1000010000',
      'routeno': '급행10',
      'routetp': '급행버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002000',
      'routeno': '순환2',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002100',
      'routeno': '순환2-1',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB2000003000',
      'routeno': '순환3',
      'routetp': '순환버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB2000003100',
      'routeno': '순환3-1',
      'routetp': '순환버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101011',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101012',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101013',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101016',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101017',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101018',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101019',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101020',
      'routeno': 101,
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101110',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101111',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101112',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101113',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101114',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101115',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101116',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '파계사(종점)',
      'routeid': 'DGB3000101117',
      'routeno': '101-1',
      'routetp': '간선버스',
      'startnodenm': '파계사(종점)'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000156000',
      'routeno': 156,
      'routetp': '간선버스',
      'startnodenm': '신덕마을입구건너'},
     {'endnodenm': '금호지구종점(종점방향)',
      'routeid': 'DGB3000204000',
      'routeno': 204,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000232000',
      'routeno': 232,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '냉천전원음식점지구',
      'routeid': 'DGB3000240001',
      'routeno': 240,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000300000',
      'routeno': 300,
      'routetp': '간선버스',
      'startnodenm': '유통단지회차지2'},
     {'endnodenm': '가창초등학교건너',
      'routeid': 'DGB3000304001',
      'routeno': 304,
      'routetp': '간선버스',
      'startnodenm': '유통단지회차지2'},
     {'endnodenm': '대곡공원건너',
      'routeid': 'DGB3000306000',
      'routeno': 306,
      'routetp': '간선버스',
      'startnodenm': '유통단지회차지2'},
     {'endnodenm': '부적주공A 건너',
      'routeid': 'DGB3000309002',
      'routeno': 309,
      'routetp': '간선버스',
      'startnodenm': '서대구역(남측)1'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000320000',
      'routeno': 320,
      'routetp': '간선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000323101',
      'routeno': '232-1',
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000326000',
      'routeno': 326,
      'routetp': '간선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000349000',
      'routeno': 349,
      'routetp': '간선버스',
      'startnodenm': '덕원고등학교앞2'},
     {'endnodenm': '월광수변공원',
      'routeid': 'DGB3000356000',
      'routeno': 356,
      'routetp': '간선버스',
      'startnodenm': '조야동(종점)'},
     {'endnodenm': '갓바위',
      'routeid': 'DGB3000401000',
      'routeno': 401,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '갓바위',
      'routeid': 'DGB3000401078',
      'routeno': 401,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '갓바위',
      'routeid': 'DGB3000401079',
      'routeno': 401,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB3000402001',
      'routeno': 402,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '조야동(종점)',
      'routeid': 'DGB3000403001',
      'routeno': 403,
      'routetp': '간선버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000405004',
      'routeno': 405,
      'routetp': '간선버스',
      'startnodenm': '삼산리(세왕교통1)'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000410000',
      'routeno': 410,
      'routetp': '간선버스',
      'startnodenm': '앞산공원'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB3000410100',
      'routeno': '410-1',
      'routetp': '간선버스',
      'startnodenm': '앞산공원'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000413001',
      'routeno': 413,
      'routetp': '간선버스',
      'startnodenm': '가창초등학교앞'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000425000',
      'routeno': 425,
      'routetp': '간선버스',
      'startnodenm': '황금고가교네거리'},
     {'endnodenm': '연경동종점1',
      'routeid': 'DGB3000501000',
      'routeno': 501,
      'routetp': '간선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000503001',
      'routeno': 503,
      'routetp': '간선버스',
      'startnodenm': '연경동종점2'},
     {'endnodenm': '두리봉터널종점',
      'routeid': 'DGB3000504000',
      'routeno': 504,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '소라아파트 건너',
      'routeid': 'DGB3000509002',
      'routeno': 509,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '안심역(4번출구)',
      'routeid': 'DGB3000518002',
      'routeno': 518,
      'routetp': '간선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000520000',
      'routeno': 520,
      'routetp': '간선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '방천리공영차고지',
      'routeid': 'DGB3000523002',
      'routeno': 523,
      'routetp': '간선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '동명교통',
      'routeid': 'DGB3000527000',
      'routeno': 527,
      'routetp': '간선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB3000564000',
      'routeno': 564,
      'routetp': '간선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000609007',
      'routeno': 609,
      'routetp': '간선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000618003',
      'routeno': 618,
      'routetp': '간선버스',
      'startnodenm': '대곡주공8단지건너'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB3000623002',
      'routeno': 623,
      'routetp': '간선버스',
      'startnodenm': '달성군청건너'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000649000',
      'routeno': 649,
      'routetp': '간선버스',
      'startnodenm': '대곡공원앞'},
     {'endnodenm': '동대구역(2번출구)건너',
      'routeid': 'DGB3000650005',
      'routeno': 650,
      'routetp': '간선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000651000',
      'routeno': 651,
      'routetp': '간선버스',
      'startnodenm': '명곡미래빌1단지'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB3000653000',
      'routeno': 653,
      'routetp': '간선버스',
      'startnodenm': '설화리(종점)1'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000655000',
      'routeno': 655,
      'routetp': '간선버스',
      'startnodenm': '유곡리공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB3000665000',
      'routeno': 665,
      'routetp': '간선버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB3000665003',
      'routeno': 665,
      'routetp': '간선버스',
      'startnodenm': '대곡역(1번출구)'},
     {'endnodenm': '대곡주공8단지앞',
      'routeid': 'DGB3000706001',
      'routeno': 706,
      'routetp': '간선버스',
      'startnodenm': '관음변전소2'},
     {'endnodenm': '관음변전소4',
      'routeid': 'DGB3000707000',
      'routeno': 707,
      'routetp': '간선버스',
      'startnodenm': '관음변전소3'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000708002',
      'routeno': 708,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000719001',
      'routeno': 719,
      'routetp': '간선버스',
      'startnodenm': '칠곡우방타운건너(종점)'},
     {'endnodenm': '덕원고등학교건너',
      'routeid': 'DGB3000724000',
      'routeno': 724,
      'routetp': '간선버스',
      'startnodenm': '칠곡우방타운건너(종점)'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB3000725000',
      'routeno': 725,
      'routetp': '일반버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '대곡주공8단지앞',
      'routeid': 'DGB3000726000',
      'routeno': 726,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '대덕맨션앞',
      'routeid': 'DGB3000730002',
      'routeno': 730,
      'routetp': '간선버스',
      'startnodenm': '동명교통'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB3000802000',
      'routeno': 802,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000805000',
      'routeno': 805,
      'routetp': '간선버스',
      'startnodenm': '달서아트센터앞'},
     {'endnodenm': '진밭골(종점)2',
      'routeid': 'DGB3000814001',
      'routeno': 814,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '대천교',
      'routeid': 'DGB3000836001',
      'routeno': 836,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848000',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '금강동',
      'routeid': 'DGB3000848001',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848002',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'},
     {'endnodenm': '금강동',
      'routeid': 'DGB3000848003',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '범물1동행정복지센터앞',
      'routeid': 'DGB3000894000',
      'routeno': 894,
      'routetp': '간선버스',
      'startnodenm': '경일대종점'},
     {'endnodenm': '관음변전소1',
      'routeid': 'DGB3000937000',
      'routeno': 937,
      'routetp': '간선버스',
      'startnodenm': '덕원고등학교앞2'},
     {'endnodenm': '모다아울렛앞',
      'routeid': 'DGB3001725000',
      'routeno': 7250,
      'routetp': '일반버스',
      'startnodenm': '태전역2'},
     {'endnodenm': '동대구역',
      'routeid': 'DGB3001814000',
      'routeno': 8140,
      'routetp': '일반버스',
      'startnodenm': 'TBC건너'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002001',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002003',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002004',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '칠성고가도로하단',
      'routeid': 'DGB4010002118',
      'routeno': '가창2',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB4030001000',
      'routeno': '달서1',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '앞산공원',
      'routeid': 'DGB4030002002',
      'routeno': '달서2',
      'routetp': '지선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '화원유원지(사문진주막촌)',
      'routeid': 'DGB4030003002',
      'routeno': '달서3',
      'routetp': '지선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB4030005001',
      'routeno': '달서5',
      'routetp': '지선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '남도버스2',
      'routeid': 'DGB4030006000',
      'routeno': '달서6',
      'routetp': '지선버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001006',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001007',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001008',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '다산(종점)',
      'routeid': 'DGB4040001009',
      'routeno': '달성1',
      'routetp': '지선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002044',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002045',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002046',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002047',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '대천교',
      'routeid': 'DGB4040002048',
      'routeno': '달성2',
      'routetp': '지선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '현풍공영버스정류장1',
      'routeid': 'DGB4040003002',
      'routeno': '달성3',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '현풍공영버스정류장1',
      'routeid': 'DGB4040003003',
      'routeno': '달성3',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '구지119안전센터건너',
      'routeid': 'DGB4040004006',
      'routeno': '달성4',
      'routetp': '지선버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005000',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '유천교1',
      'routeid': 'DGB4040005001',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유가사(종점)'},
     {'endnodenm': '유천교1',
      'routeid': 'DGB4040005002',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유가사(종점)'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005003',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005070',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '유천교1',
      'routeid': 'DGB4040005071',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유가사(종점)'},
     {'endnodenm': '유가사(종점)',
      'routeid': 'DGB4040005072',
      'routeno': '달성5',
      'routetp': '지선버스',
      'startnodenm': '유천교2'},
     {'endnodenm': '본말(종점)',
      'routeid': 'DGB4040006022',
      'routeno': '달성6',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '유산리',
      'routeid': 'DGB4040007011',
      'routeno': '달성7',
      'routetp': '지선버스',
      'startnodenm': '현풍공영버스정류장2'},
     {'endnodenm': '조일고등학교(종점)',
      'routeid': 'DGB4050001001',
      'routeno': '동구1',
      'routetp': '지선버스',
      'startnodenm': '조일고등학교(종점)'},
     {'endnodenm': '조일고등학교(종점)',
      'routeid': 'DGB4050001101',
      'routeno': '동구1-1',
      'routetp': '지선버스',
      'startnodenm': '조일고등학교(종점)'},
     {'endnodenm': '부동(종점)',
      'routeid': 'DGB4050003000',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '경주최씨종가(종점)',
      'routeid': 'DGB4050003001',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': 'K2관사입구(종점)',
      'routeid': 'DGB4050003002',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '구둔산',
      'routeid': 'DGB4050003003',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': 'K2관사입구(종점)',
      'routeid': 'DGB4050003004',
      'routeno': '동구3',
      'routetp': '지선버스',
      'startnodenm': '칠성고가도로하단'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB4050004000',
      'routeno': '동구4',
      'routetp': '지선버스',
      'startnodenm': '반야월역(4번출구)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB4050004100',
      'routeno': '동구4-1',
      'routetp': '지선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '매여동(동구)저탄장',
      'routeid': 'DGB4050005000',
      'routeno': '동구5',
      'routetp': '지선버스',
      'startnodenm': '매여동(동구)저탄장'},
     {'endnodenm': '용계삼거리1',
      'routeid': 'DGB4050005100',
      'routeno': '동구5',
      'routetp': '지선버스',
      'startnodenm': '매여동(동구)저탄장'},
     {'endnodenm': '안심역(5번출구)',
      'routeid': 'DGB4050006000',
      'routeno': '동구6',
      'routetp': '지선버스',
      'startnodenm': 'LH14단지아파트'},
     {'endnodenm': '안심역(5번출구)',

In [44]:
data['response']

{'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
 'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
     'routeid': 'DGB1000001000',
     'routeno': '급행1',
     'routetp': '급행버스',
     'startnodenm': '동화시설집단지구(종점)1'},
    {'endnodenm': '북구 동호동(종점)2(서리지입구)',
     'routeid': 'DGB1000002001',
     'routeno': '급행2',
     'routetp': '급행버스',
     'startnodenm': '냉천전원음식점지구'},
    {'endnodenm': '동명교통',
     'routeid': 'DGB1000003000',
     'routeno': '급행3',
     'routetp': '급행버스',
     'startnodenm': '범물1동행정복지센터건너'},
    {'endnodenm': '신흥버스',
     'routeid': 'DGB1000005000',
     'routeno': '급행5',
     'routetp': '급행버스',
     'startnodenm': '대구대(정문1)'},
    {'endnodenm': '북구 동호동(종점)2(서리지입구)',
     'routeid': 'DGB1000007000',
     'routeno': '급행7',
     'routetp': '급행버스',
     'startnodenm': '남도버스1'},
    {'endnodenm': '서대구역(남측)2',
     'routeid': 'DGB1000008004',
     'routeno': '급행8',
     'routetp': '급행버스',
     'startnodenm': '기업은행국가산단지점건너'},
    {'endnodenm': '진천역(2번출구)',
     'routeid': 'DGB1000008101',
     'routeno': '급행8-1',
     'routetp': '급행버스',
     'startnodenm': '유곡리공영차고지앞'},
    {'endnodenm': '군위군청',
     'routeid': 'DGB1000009002',
     'routeno': '급행9',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'},
    {'endnodenm': '우보버스정류장',
     'routeid': 'DGB1000009100',
     'routeno': '급행9-1',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'},
    {'endnodenm': '삼국유사면문화관',
     'routeid': 'DGB1000009200',
     'routeno': '급행9-2',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'}]},
  'numOfRows': 10,
  'pageNo': 1,
  'totalCount': 232}}

In [20]:
data['response']['body']

{'items': {'item': [{'endnodenm': '매곡(종점)',
    'routeid': 'DGB1000001000',
    'routeno': '급행1',
    'routetp': '급행버스',
    'startnodenm': '동화시설집단지구(종점)1'},
   {'endnodenm': '북구 동호동(종점)2(서리지입구)',
    'routeid': 'DGB1000002001',
    'routeno': '급행2',
    'routetp': '급행버스',
    'startnodenm': '냉천전원음식점지구'},
   {'endnodenm': '동명교통',
    'routeid': 'DGB1000003000',
    'routeno': '급행3',
    'routetp': '급행버스',
    'startnodenm': '범물1동행정복지센터건너'},
   {'endnodenm': '신흥버스',
    'routeid': 'DGB1000005000',
    'routeno': '급행5',
    'routetp': '급행버스',
    'startnodenm': '대구대(정문1)'},
   {'endnodenm': '북구 동호동(종점)2(서리지입구)',
    'routeid': 'DGB1000007000',
    'routeno': '급행7',
    'routetp': '급행버스',
    'startnodenm': '남도버스1'},
   {'endnodenm': '서대구역(남측)2',
    'routeid': 'DGB1000008004',
    'routeno': '급행8',
    'routetp': '급행버스',
    'startnodenm': '기업은행국가산단지점건너'},
   {'endnodenm': '진천역(2번출구)',
    'routeid': 'DGB1000008101',
    'routeno': '급행8-1',
    'routetp': '급행버스',
    'startnodenm': '유곡리공영차고지앞'},
   {'endnodenm': '군위군청',
    'routeid': 'DGB1000009002',
    'routeno': '급행9',
    'routetp': '급행버스',
    'startnodenm': '북구 동호동(종점)1'},
   {'endnodenm': '우보버스정류장',
    'routeid': 'DGB1000009100',
    'routeno': '급행9-1',
    'routetp': '급행버스',
    'startnodenm': '북구 동호동(종점)1'},
   {'endnodenm': '삼국유사면문화관',
    'routeid': 'DGB1000009200',
    'routeno': '급행9-2',
    'routetp': '급행버스',
    'startnodenm': '북구 동호동(종점)1'}]},
 'numOfRows': 10,
 'pageNo': 1,
 'totalCount': 232}

In [21]:
data['response']['body']['items']

{'item': [{'endnodenm': '매곡(종점)',
   'routeid': 'DGB1000001000',
   'routeno': '급행1',
   'routetp': '급행버스',
   'startnodenm': '동화시설집단지구(종점)1'},
  {'endnodenm': '북구 동호동(종점)2(서리지입구)',
   'routeid': 'DGB1000002001',
   'routeno': '급행2',
   'routetp': '급행버스',
   'startnodenm': '냉천전원음식점지구'},
  {'endnodenm': '동명교통',
   'routeid': 'DGB1000003000',
   'routeno': '급행3',
   'routetp': '급행버스',
   'startnodenm': '범물1동행정복지센터건너'},
  {'endnodenm': '신흥버스',
   'routeid': 'DGB1000005000',
   'routeno': '급행5',
   'routetp': '급행버스',
   'startnodenm': '대구대(정문1)'},
  {'endnodenm': '북구 동호동(종점)2(서리지입구)',
   'routeid': 'DGB1000007000',
   'routeno': '급행7',
   'routetp': '급행버스',
   'startnodenm': '남도버스1'},
  {'endnodenm': '서대구역(남측)2',
   'routeid': 'DGB1000008004',
   'routeno': '급행8',
   'routetp': '급행버스',
   'startnodenm': '기업은행국가산단지점건너'},
  {'endnodenm': '진천역(2번출구)',
   'routeid': 'DGB1000008101',
   'routeno': '급행8-1',
   'routetp': '급행버스',
   'startnodenm': '유곡리공영차고지앞'},
  {'endnodenm': '군위군청',
   'routeid': 'DGB1000009002',
   'routeno': '급행9',
   'routetp': '급행버스',
   'startnodenm': '북구 동호동(종점)1'},
  {'endnodenm': '우보버스정류장',
   'routeid': 'DGB1000009100',
   'routeno': '급행9-1',
   'routetp': '급행버스',
   'startnodenm': '북구 동호동(종점)1'},
  {'endnodenm': '삼국유사면문화관',
   'routeid': 'DGB1000009200',
   'routeno': '급행9-2',
   'routetp': '급행버스',
   'startnodenm': '북구 동호동(종점)1'}]}

In [22]:
data['response']['body']['items']['item']

[{'endnodenm': '매곡(종점)',
  'routeid': 'DGB1000001000',
  'routeno': '급행1',
  'routetp': '급행버스',
  'startnodenm': '동화시설집단지구(종점)1'},
 {'endnodenm': '북구 동호동(종점)2(서리지입구)',
  'routeid': 'DGB1000002001',
  'routeno': '급행2',
  'routetp': '급행버스',
  'startnodenm': '냉천전원음식점지구'},
 {'endnodenm': '동명교통',
  'routeid': 'DGB1000003000',
  'routeno': '급행3',
  'routetp': '급행버스',
  'startnodenm': '범물1동행정복지센터건너'},
 {'endnodenm': '신흥버스',
  'routeid': 'DGB1000005000',
  'routeno': '급행5',
  'routetp': '급행버스',
  'startnodenm': '대구대(정문1)'},
 {'endnodenm': '북구 동호동(종점)2(서리지입구)',
  'routeid': 'DGB1000007000',
  'routeno': '급행7',
  'routetp': '급행버스',
  'startnodenm': '남도버스1'},
 {'endnodenm': '서대구역(남측)2',
  'routeid': 'DGB1000008004',
  'routeno': '급행8',
  'routetp': '급행버스',
  'startnodenm': '기업은행국가산단지점건너'},
 {'endnodenm': '진천역(2번출구)',
  'routeid': 'DGB1000008101',
  'routeno': '급행8-1',
  'routetp': '급행버스',
  'startnodenm': '유곡리공영차고지앞'},
 {'endnodenm': '군위군청',
  'routeid': 'DGB1000009002',
  'routeno': '급행9',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '우보버스정류장',
  'routeid': 'DGB1000009100',
  'routeno': '급행9-1',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '삼국유사면문화관',
  'routeid': 'DGB1000009200',
  'routeno': '급행9-2',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'}]

In [ ]:
data['response']['body']['items']['item'][0]

{'endnodenm': '매곡(종점)',
 'routeid': 'DGB1000001000',
 'routeno': '급행1',
 'routetp': '급행버스',
 'startnodenm': '동화시설집단지구(종점)1'}

In [25]:
data['response']['body']['items']['item'][0]['endnodenm']

'매곡(종점)'

In [26]:
data['response']['body']['items']['item'][0]['routeno']

'급행1'

In [27]:
data['response']['body']['items']['item'][0]['routetp']

'급행버스'

In [29]:
BASE_URL= 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
CITY_CODE = 22
ROWS_PER_PAGE = 1000
REQUESTS_TIMEOUT = 10

In [30]:
BASE_DIR = os.getcwd()
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'bus_route.csv')

In [31]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/busapidb2'
TABLE_NAME = 'bus_route'

print(f'csv저장경로: {OUTPUT_PATH}')

csv저장경로: c:\Users\Administrator\bigdata2026\fastapi\04_bus_api_pipline2\output\bus_route.csv

In [32]:
data['response']['body']['totalCount']

232

In [33]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count / ROWS_PER_PAGE)

print(f'전체 건수 : {total_count:}개')
print(f'페이지당 건수 : {ROWS_PER_PAGE:}개')
print(f'총 페이지 수 : {total_pages:}페이지')

전체 건수 : 232개
페이지당 건수 : 1000개
총 페이지 수 : 1페이지

In [78]:
all_items = []

for page_no in range(1, total_pages+1):
    params={
        'serviceKey': API_KEY,
        'pageNo': page_no,
        'numOfRows': ROWS_PER_PAGE,
        'cityCode': CITY_CODE,
        '_type': 'json',
        'node_id':''
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUESTS_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']
    
    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지: 페이지 없음')
        continue 
    
    page_items = page_body['items'].get('item', [])

    if isinstance(page_items, dict):
        page_items = [page_items]

    all_items.extend(page_items)

    print(f'{page_no} / {total_pages} 페이지 수집 완료 -> 누적 {len(all_items):}건')

    time.sleep(0.2)

    print(f'전체 수집 완료: {len(all_items):}건')

1 / 1 페이지 수집 완료 -> 누적 232건
전체 수집 완료: 232건

In [68]:
df_raw = pd.DataFrame(all_items)

print(f'데이터프레임의 크기: {df_raw.shape}')
print(f'컬럼 목록: {df_raw.columns.tolist()}')

데이터프레임의 크기: (232, 5)
컬럼 목록: ['endnodenm', 'routeid', 'routeno', 'routetp', 'startnodenm']

- endnodenm=종점, routeid=노선ID, routeno=노선번호, routetp=노선유형, startnodenm=기점

In [ ]:
df_select = df_raw[['routeno', 'routeid']].copy()
df_select['node_id'] = TARGET_NODE_ID

df_select

    routeno        routeid        node_id
0       급행1  DGB1000001000  DGB1000001000
1       급행2  DGB1000002001  DGB1000001000
2       급행3  DGB1000003000  DGB1000001000
3       급행5  DGB1000005000  DGB1000001000
4       급행7  DGB1000007000  DGB1000001000
..      ...            ...            ...
227    군위10  DGB7361110013  DGB1000001000
228    군위10  DGB7361110014  DGB1000001000
229    군위10  DGB7361110015  DGB1000001000
230    군위10  DGB7361110016  DGB1000001000
231    군위11  DGB7361111009  DGB1000001000

[232 rows x 3 columns]

In [89]:
df_select['node_id'] = TARGET_NODE_ID

df_select.head()

  routeno        routeid        node_id
0     급행1  DGB1000001000  DGB1000001000
1     급행2  DGB1000002001  DGB1000001000
2     급행3  DGB1000003000  DGB1000001000
3     급행5  DGB1000005000  DGB1000001000
4     급행7  DGB1000007000  DGB1000001000

In [90]:
df_select = df_select.rename(columns={
    'routeno': '노선번호',
    'routeid': '노선ID',
    'node_id': '정류소ID'
})

df_select.head()

  노선번호           노선ID          정류소ID
0  급행1  DGB1000001000  DGB1000001000
1  급행2  DGB1000002001  DGB1000001000
2  급행3  DGB1000003000  DGB1000001000
3  급행5  DGB1000005000  DGB1000001000
4  급행7  DGB1000007000  DGB1000001000

In [100]:
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장하는 함수"""
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # DataFrame을 DB테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료: {saved_count:}행')
    print(f'DB: busapidb2 / table: {table_name}')

In [101]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료: 232행
DB: busapidb2 / table: bus_route

In [102]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료')

CSV 저장 완료

In [ ]:
print('=' * 80)
print('대구 버스 정류소 API 수집 파이프라인 결과')
print('=' * 80)
print('수집 방식 : 공공데이터포털 - TAGO REST API ')
print(f'도시 코드 : {CITY_CODE}(대구)')
print(f'정류소ID  : {TARGET_NODE_ID}') 
print(f'수집 건수 : {len(df_select)}건 ')
print(f'컬럼 수   : {len(df_select.columns)}개 ')
print(f'CSV 저장 위치 : {OUTPUT_PATH}')
print(f'DB 저장 위치  : busapidb.{TABLE_NAME}')
print('=' * 80)

================================================================================
대구 버스 정류소 API 수집 파이프라인 결과
================================================================================
수집 방식 : 공공데이터포털 - TAGO REST API
도시 코드 : 22(대구)
정류소ID  : DGB1000001000
수집 건수 : 232건
컬럼 수   : 3개
CSV 저장 위치 : c:\Users\Administrator\bigdata2026\fastapi\04_bus_api_pipline2\output\bus_route.csv
DB 저장 위치  : busapidb.bus_route
================================================================================