In [1]:
import math
import os 
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

In [3]:
BASE_URL = 'https://apis.data.go.kr/B551178/airport-congestion/v2'

In [4]:
# 1번
response = requests.get(BASE_URL, params={
                        'serviceKey': API_KEY,
                        'pageNo': 1,
                        'numOfRows': 10,
                        'type': 'json',
                        })
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 5,
   'items': {'item': [{'IATA_APCD': 'GMP',
      'PRC_HR': '10:45',
      'CGDR_A_LVL': 1.0,
      'CGDR_B_LVL': 2.0,
      'CGDR_C_LVL': 1.0,
      'CGDR_ALL_LVL': 1.0},
     {'IATA_APCD': 'PUS',
      'PRC_HR': '10:45',
      'CGDR_A_LVL': 1.0,
      'CGDR_B_LVL': 1.0,
      'CGDR_C_LVL': 1.0,
      'CGDR_ALL_LVL': 1.0},
     {'IATA_APCD': 'TAE',
      'PRC_HR': '10:45',
      'CGDR_A_LVL': 1.0,
      'CGDR_B_LVL': 2.0,
      'CGDR_C_LVL': 1.0,
      'CGDR_ALL_LVL': 1.0},
     {'IATA_APCD': 'CJJ',
      'PRC_HR': '10:45',
      'CGDR_A_LVL': 1.0,
      'CGDR_B_LVL': 3.0,
      'CGDR_C_LVL': 1.0,
      'CGDR_ALL_LVL': 2.0},
     {'IATA_APCD': 'CJU',
      'PRC_HR': '10:45',
      'CGDR_A_LVL': 1.0,
      'CGDR_B_LVL': 1.0,
      'CGDR_C_LVL': 1.0,
      'CGDR_ALL_LVL': 1.0}]}}}}

In [5]:
# 2번
# GMP : 김포, PUS : 김해, TAE : 대구, CJJ : 청주, CJU : 제주
raw_items = data['response']['body']['items']['item']
df = pd.DataFrame(raw_items)
df

  IATA_APCD PRC_HR  CGDR_A_LVL  CGDR_B_LVL  CGDR_C_LVL  CGDR_ALL_LVL
0       GMP  10:45         1.0         2.0         1.0           1.0
1       PUS  10:45         1.0         1.0         1.0           1.0
2       TAE  10:45         1.0         2.0         1.0           1.0
3       CJJ  10:45         1.0         3.0         1.0           2.0
4       CJU  10:45         1.0         1.0         1.0           1.0

In [6]:
# 컬럼명 변경
df = df.rename(columns={
    'IATA_APCD': '공항코드',
    'PRC_HR': '수집시간',
    'CGDR_A_LVL': 'A구역_혼잡도',
    'CGDR_B_LVL': 'B구역_혼잡도',
    'CGDR_C_LVL': 'C구역_혼잡도',
    'CGDR_ALL_LVL': '전체_혼잡도'
})
df

  공항코드   수집시간  A구역_혼잡도  B구역_혼잡도  C구역_혼잡도  전체_혼잡도
0  GMP  10:45      1.0      2.0      1.0     1.0
1  PUS  10:45      1.0      1.0      1.0     1.0
2  TAE  10:45      1.0      2.0      1.0     1.0
3  CJJ  10:45      1.0      3.0      1.0     2.0
4  CJU  10:45      1.0      1.0      1.0     1.0

In [7]:
# 3번
df['수집일시'] = str(date.today())
혼잡도_컬럼 = ['A구역_혼잡도', 'B구역_혼잡도', 'C구역_혼잡도', '전체_혼잡도']
df[혼잡도_컬럼] = df[혼잡도_컬럼].apply(pd.to_numeric)

def 혼잡여부(혼잡도):
    if 혼잡도 == 1:
        return '원활'
    elif 혼잡도 == 2:
        return '보통'
    else:
        return '혼잡'
    
df['혼잡여부'] = df['전체_혼잡도'].apply(혼잡여부)

df

  공항코드   수집시간  A구역_혼잡도  B구역_혼잡도  C구역_혼잡도  전체_혼잡도        수집일시 혼잡여부
0  GMP  10:45      1.0      2.0      1.0     1.0  2026-07-03   원활
1  PUS  10:45      1.0      1.0      1.0     1.0  2026-07-03   원활
2  TAE  10:45      1.0      2.0      1.0     1.0  2026-07-03   원활
3  CJJ  10:45      1.0      3.0      1.0     2.0  2026-07-03   보통
4  CJU  10:45      1.0      1.0      1.0     1.0  2026-07-03   원활

In [8]:
# 4번
def check_data(data_frame):
    rows = len(data_frame)
    print(f"데이터의 전체 행 개수는 {rows}개")
    
    nulls = data_frame.isnull().sum().sum()
    if nulls == 0:
        print("결측치 검증 결과: 누락된 데이터 없이 모두 정상")
    else:
        print(f"결측치 검증 결과: 현재 총 {nulls}개의 누락된 값이 존재")
        print(data_frame.isnull().sum())

check_data(df)

데이터의 전체 행 개수는 5개
결측치 검증 결과: 누락된 데이터 없이 모두 정상

In [9]:
# 5번
DB_URL = 'postgresql://postgres:1234@localhost:5432/bigdatatestdb'
TABLE_NAME = 'airport_congestion'

def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

In [10]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

In [11]:
BASE_DIR = os.getcwd()  # 현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'airport_congestion.csv')

In [12]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('csv 저장 완료')

csv 저장 완료