In [1]:
import os
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
load_dotenv()
API_KEY = os.getenv("API_KEY")

if API_KEY:
    print(f"API 키 로드 완료 : {API_KEY[:6]}...{API_KEY[-4:]}")
else:
    print("API 키 없음")

API 키 로드 완료 : feaa64...99a7

In [3]:
BASE_URL = "https://apis.data.go.kr/6270000/openData/WtrQuality" # 대구광역시_수질정보 조회 서비스_GW
BASE_DIR = os.getcwd()
AREA_PATH = os.path.join(BASE_DIR, "input", "area.csv") # 정수장과 행정구역을 연결하기 위한 자료
WATER_OUTPUT_PATH = os.path.join(BASE_DIR, "output", "water.csv") # 정수장 별 수질검사 기록 저장
AREA_OUTPUT_PATH = os.path.join(BASE_DIR, "output", "area.csv") # 정수장별 급수구역을 행정구역 기준으로 정리
YEAR = 2025 # 수질검사 조회 년도

In [4]:
# 행정구역 자료 경로 확인

AREA_PATH

'c:\\Users\\Administrator\\bigdata2026\\bigdata2026-basic\\TEST\\07_빅데이터수집시스템개발_김동욱\\input\\area.csv'

In [5]:
# 수질검사 저장 경로 확인

WATER_OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\bigdata2026-basic\\TEST\\07_빅데이터수집시스템개발_김동욱\\output\\water.csv'

In [6]:
# 행정구역 저장 경로 확인

AREA_OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\bigdata2026-basic\\TEST\\07_빅데이터수집시스템개발_김동욱\\output\\area.csv'

In [7]:
DB_URL = "postgresql://postgres:1234@localhost:5432/water_DB"

In [8]:
response = requests.get(BASE_URL, params={"serviceKey" : API_KEY, "searchDate" : YEAR})
response.raise_for_status()
print(response.raise_for_status)

<bound method Response.raise_for_status of <Response [200]>>

In [9]:
data = response.json()
data

{'rsMsg': {'statusCode': 'S', 'message': ''},
 'header': ['정수장',
  '구분',
  '항목',
  '1월',
  '2월',
  '3월',
  '4월',
  '5월',
  '6월',
  '7월',
  '8월',
  '9월',
  '10월',
  '11월',
  '12월'],
 'list': [{'name': '가창',
   'codenm': '정수1',
   'type': 'PH',
   'm1': '7.03',
   'm2': '7.08',
   'm3': '7.12',
   'm4': '7.12',
   'm5': '7.08',
   'm6': '7.08',
   'm7': '7.06',
   'm8': '7.01',
   'm9': '7.06',
   'm10': '7.09',
   'm11': '7.06',
   'm12': '7.06'},
  {'name': '가창',
   'codenm': '정수1',
   'type': '탁도',
   'm1': '0.06',
   'm2': '0.07',
   'm3': '0.06',
   'm4': '0.05',
   'm5': '0.05',
   'm6': '0.05',
   'm7': '0.06',
   'm8': '0.08',
   'm9': '0.08',
   'm10': '0.08',
   'm11': '0.07',
   'm12': '0.07'},
  {'name': '가창',
   'codenm': '정수1',
   'type': '잔류염소',
   'm1': '0.61',
   'm2': '0.6',
   'm3': '0.59',
   'm4': '0.57',
   'm5': '0.58',
   'm6': '0.58',
   'm7': '0.58',
   'm8': '0.58',
   'm9': '0.58',
   'm10': '0.6',
   'm11': '0.61',
   'm12': '0.6'},
  {'name': '가창',
   'codenm': '정수2',
   'type': 'PH',
   'm1': '7.11',
   'm2': '7.19',
   'm3': '7.17',
   'm4': '7.16',
   'm5': '7.07',
   'm6': '7.06',
   'm7': '7.12',
   'm8': '7.',
   'm9': '7.11',
   'm10': '7.24',
   'm11': '7.09',
   'm12': '7.14'},
  {'name': '가창',
   'codenm': '정수2',
   'type': '탁도',
   'm1': '0.06',
   'm2': '0.07',
   'm3': '0.07',
   'm4': '0.06',
   'm5': '0.06',
   'm6': '0.06',
   'm7': '0.06',
   'm8': '0.06',
   'm9': '0.07',
   'm10': '0.07',
   'm11': '0.05',
   'm12': '0.07'},
  {'name': '가창',
   'codenm': '정수2',
   'type': '잔류염소',
   'm1': '0.66',
   'm2': '0.65',
   'm3': '0.61',
   'm4': '0.59',
   'm5': '0.5',
   'm6': '0.58',
   'm7': '0.58',
   'm8': '0.6',
   'm9': '0.67',
   'm10': '0.66',
   'm11': '0.62',
   'm12': '0.65'},
  {'name': '매곡',
   'codenm': '정수1',
   'type': 'PH',
   'm1': '7.01',
   'm2': '7.01',
   'm3': '7.12',
   'm4': '7.04',
   'm5': '6.97',
   'm6': '6.91',
   'm7': '6.76',
   'm8': '6.77',
   'm9': '6.79',
   'm10': '6.76',
   'm11': '6.97',
   'm12': '7.2'},
  {'name': '매곡',
   'codenm': '정수1',
   'type': '탁도',
   'm1': '0.07',
   'm2': '0.08',
   'm3': '0.07',
   'm4': '0.07',
   'm5': '0.07',
   'm6': '0.07',
   'm7': '0.06',
   'm8': '0.08',
   'm9': '0.08',
   'm10': '0.06',
   'm11': '0.06',
   'm12': '0.07'},
  {'name': '매곡',
   'codenm': '정수1',
   'type': '잔류염소',
   'm1': '0.73',
   'm2': '0.74',
   'm3': '0.74',
   'm4': '0.74',
   'm5': '0.7',
   'm6': '0.7',
   'm7': '0.8',
   'm8': '0.81',
   'm9': '0.8',
   'm10': '0.78',
   'm11': '0.75',
   'm12': '0.7'},
  {'name': '매곡',
   'codenm': '정수2',
   'type': 'PH',
   'm1': '6.9',
   'm2': '6.95',
   'm3': '7.11',
   'm4': '7.01',
   'm5': '6.91',
   'm6': '6.85',
   'm7': '6.67',
   'm8': '6.75',
   'm9': '6.84',
   'm10': '6.83',
   'm11': '7.03',
   'm12': '7.32'},
  {'name': '매곡',
   'codenm': '정수2',
   'type': '탁도',
   'm1': '0.07',
   'm2': '0.07',
   'm3': '0.07',
   'm4': '0.05',
   'm5': '0.05',
   'm6': '0.06',
   'm7': '0.06',
   'm8': '0.09',
   'm9': '0.09',
   'm10': '0.07',
   'm11': '0.07',
   'm12': '0.06'},
  {'name': '매곡',
   'codenm': '정수2',
   'type': '잔류염소',
   'm1': '0.65',
   'm2': '0.69',
   'm3': '0.67',
   'm4': '0.71',
   'm5': '0.74',
   'm6': '0.73',
   'm7': '0.79',
   'm8': '0.82',
   'm9': '0.82',
   'm10': '0.79',
   'm11': '0.75',
   'm12': '0.69'},
  {'name': '고산',
   'codenm': '정수',
   'type': 'PH',
   'm1': '6.95',
   'm2': '6.94',
   'm3': '6.98',
   'm4': '7.',
   'm5': '7.01',
   'm6': '7.02',
   'm7': '7.01',
   'm8': '7.02',
   'm9': '6.95',
   'm10': '6.91',
   'm11': '6.99',
   'm12': '6.96'},
  {'name': '고산',
   'codenm': '정수',
   'type': '탁도',
   'm1': '0.05',
   'm2': '0.05',
   'm3': '0.05',
   'm4': '0.05',
   'm5': '0.05',
   'm6': '0.05',
   'm7': '0.05',
   'm8': '0.05',
   'm9': '0.06',
   'm10': '0.05',
   'm11': '0.05',
   'm12': '0.05'},
  {'name': '고산',
   'codenm': '정수',
   'type': '잔류염소',
   'm1': '0.57',
   'm2': '0.58',
   'm3': '0.61',
   'm4': '0.59',
   'm5': '0.59',
   'm6': '0.62',
   'm7': '0.6',
   'm8': '0.59',
   'm9': '0.6',
   'm10': '0.6',
   'm11': '0.7',
   'm12': '0.7'},
  {'name': '공산',
   'codenm': '정수',
   'type': 'PH',
   'm1': '7.45',
   'm2': '7.46',
   'm3': '7.39',
   'm4': '7.23',
   'm5': '7.15',
   'm6': '7.01',
   'm7': '6.83',
   'm8': '6.85',
   'm9': '6.92',
   'm10': '6.98',
   'm11': '7.08',
   'm12': '7.26'},
  {'name': '공산',
   'codenm': '정수',
   'type': '탁도',
   'm1': '0.06',
   'm2': '0.07',
   'm3': '0.07',
   'm4': '0.08',
   'm5': '0.09',
   'm6': '0.08',
   'm7': '0.08',
   'm8': '0.08',
   'm9': '0.08',
   'm10': '0.08',
   'm11': '0.07',
   'm12': '0.08'},
  {'name': '공산',
   'codenm': '정수',
   'type': '잔류염소',
   'm1': '0.71',
   'm2': '0.63',
   'm3': '0.63',
   'm4': '0.59',
   'm5': '0.69',
   'm6': '0.7',
   'm7': '0.82',
   'm8': '0.82',
   'm9': '0.84',
   'm10': '0.8',
   'm11': '0.76',
   'm12': '0.75'},
  {'name': '문산',
   'codenm': '정수',
   'type': 'PH',
   'm1': '7.33',
   'm2': '7.38',
   'm3': '7.17',
   'm4': '7.06',
   'm5': '6.94',
   'm6': '6.88',
   'm7': '6.9',
   'm8': '6.98',
   'm9': '6.98',
   'm10': '6.9',
   'm11': '6.84',
   'm12': '7.13'},
  {'name': '문산',
   'codenm': '정수',
   'type': '탁도',
   'm1': '0.05',
   'm2': '0.06',
   'm3': '0.07',
   'm4': '0.06',
   'm5': '0.05',
   'm6': '0.06',
   'm7': '0.07',
   'm8': '0.06',
   'm9': '0.06',
   'm10': '0.05',
   'm11': '0.04',
   'm12': '0.04'},
  {'name': '문산',
   'codenm': '정수',
   'type': '잔류염소',
   'm1': '0.6',
   'm2': '0.57',
   'm3': '0.59',
   'm4': '0.61',
   'm5': '0.65',
   'm6': '0.63',
   'm7': '0.76',
   'm8': '0.82',
   'm9': '0.88',
   'm10': '0.87',
   'm11': '0.74',
   'm12': '0.73'}]}

In [10]:
data["header"]

['정수장',
 '구분',
 '항목',
 '1월',
 '2월',
 '3월',
 '4월',
 '5월',
 '6월',
 '7월',
 '8월',
 '9월',
 '10월',
 '11월',
 '12월']

In [11]:
data["list"]

[{'name': '가창',
  'codenm': '정수1',
  'type': 'PH',
  'm1': '7.03',
  'm2': '7.08',
  'm3': '7.12',
  'm4': '7.12',
  'm5': '7.08',
  'm6': '7.08',
  'm7': '7.06',
  'm8': '7.01',
  'm9': '7.06',
  'm10': '7.09',
  'm11': '7.06',
  'm12': '7.06'},
 {'name': '가창',
  'codenm': '정수1',
  'type': '탁도',
  'm1': '0.06',
  'm2': '0.07',
  'm3': '0.06',
  'm4': '0.05',
  'm5': '0.05',
  'm6': '0.05',
  'm7': '0.06',
  'm8': '0.08',
  'm9': '0.08',
  'm10': '0.08',
  'm11': '0.07',
  'm12': '0.07'},
 {'name': '가창',
  'codenm': '정수1',
  'type': '잔류염소',
  'm1': '0.61',
  'm2': '0.6',
  'm3': '0.59',
  'm4': '0.57',
  'm5': '0.58',
  'm6': '0.58',
  'm7': '0.58',
  'm8': '0.58',
  'm9': '0.58',
  'm10': '0.6',
  'm11': '0.61',
  'm12': '0.6'},
 {'name': '가창',
  'codenm': '정수2',
  'type': 'PH',
  'm1': '7.11',
  'm2': '7.19',
  'm3': '7.17',
  'm4': '7.16',
  'm5': '7.07',
  'm6': '7.06',
  'm7': '7.12',
  'm8': '7.',
  'm9': '7.11',
  'm10': '7.24',
  'm11': '7.09',
  'm12': '7.14'},
 {'name': '가창',
  'codenm': '정수2',
  'type': '탁도',
  'm1': '0.06',
  'm2': '0.07',
  'm3': '0.07',
  'm4': '0.06',
  'm5': '0.06',
  'm6': '0.06',
  'm7': '0.06',
  'm8': '0.06',
  'm9': '0.07',
  'm10': '0.07',
  'm11': '0.05',
  'm12': '0.07'},
 {'name': '가창',
  'codenm': '정수2',
  'type': '잔류염소',
  'm1': '0.66',
  'm2': '0.65',
  'm3': '0.61',
  'm4': '0.59',
  'm5': '0.5',
  'm6': '0.58',
  'm7': '0.58',
  'm8': '0.6',
  'm9': '0.67',
  'm10': '0.66',
  'm11': '0.62',
  'm12': '0.65'},
 {'name': '매곡',
  'codenm': '정수1',
  'type': 'PH',
  'm1': '7.01',
  'm2': '7.01',
  'm3': '7.12',
  'm4': '7.04',
  'm5': '6.97',
  'm6': '6.91',
  'm7': '6.76',
  'm8': '6.77',
  'm9': '6.79',
  'm10': '6.76',
  'm11': '6.97',
  'm12': '7.2'},
 {'name': '매곡',
  'codenm': '정수1',
  'type': '탁도',
  'm1': '0.07',
  'm2': '0.08',
  'm3': '0.07',
  'm4': '0.07',
  'm5': '0.07',
  'm6': '0.07',
  'm7': '0.06',
  'm8': '0.08',
  'm9': '0.08',
  'm10': '0.06',
  'm11': '0.06',
  'm12': '0.07'},
 {'name': '매곡',
  'codenm': '정수1',
  'type': '잔류염소',
  'm1': '0.73',
  'm2': '0.74',
  'm3': '0.74',
  'm4': '0.74',
  'm5': '0.7',
  'm6': '0.7',
  'm7': '0.8',
  'm8': '0.81',
  'm9': '0.8',
  'm10': '0.78',
  'm11': '0.75',
  'm12': '0.7'},
 {'name': '매곡',
  'codenm': '정수2',
  'type': 'PH',
  'm1': '6.9',
  'm2': '6.95',
  'm3': '7.11',
  'm4': '7.01',
  'm5': '6.91',
  'm6': '6.85',
  'm7': '6.67',
  'm8': '6.75',
  'm9': '6.84',
  'm10': '6.83',
  'm11': '7.03',
  'm12': '7.32'},
 {'name': '매곡',
  'codenm': '정수2',
  'type': '탁도',
  'm1': '0.07',
  'm2': '0.07',
  'm3': '0.07',
  'm4': '0.05',
  'm5': '0.05',
  'm6': '0.06',
  'm7': '0.06',
  'm8': '0.09',
  'm9': '0.09',
  'm10': '0.07',
  'm11': '0.07',
  'm12': '0.06'},
 {'name': '매곡',
  'codenm': '정수2',
  'type': '잔류염소',
  'm1': '0.65',
  'm2': '0.69',
  'm3': '0.67',
  'm4': '0.71',
  'm5': '0.74',
  'm6': '0.73',
  'm7': '0.79',
  'm8': '0.82',
  'm9': '0.82',
  'm10': '0.79',
  'm11': '0.75',
  'm12': '0.69'},
 {'name': '고산',
  'codenm': '정수',
  'type': 'PH',
  'm1': '6.95',
  'm2': '6.94',
  'm3': '6.98',
  'm4': '7.',
  'm5': '7.01',
  'm6': '7.02',
  'm7': '7.01',
  'm8': '7.02',
  'm9': '6.95',
  'm10': '6.91',
  'm11': '6.99',
  'm12': '6.96'},
 {'name': '고산',
  'codenm': '정수',
  'type': '탁도',
  'm1': '0.05',
  'm2': '0.05',
  'm3': '0.05',
  'm4': '0.05',
  'm5': '0.05',
  'm6': '0.05',
  'm7': '0.05',
  'm8': '0.05',
  'm9': '0.06',
  'm10': '0.05',
  'm11': '0.05',
  'm12': '0.05'},
 {'name': '고산',
  'codenm': '정수',
  'type': '잔류염소',
  'm1': '0.57',
  'm2': '0.58',
  'm3': '0.61',
  'm4': '0.59',
  'm5': '0.59',
  'm6': '0.62',
  'm7': '0.6',
  'm8': '0.59',
  'm9': '0.6',
  'm10': '0.6',
  'm11': '0.7',
  'm12': '0.7'},
 {'name': '공산',
  'codenm': '정수',
  'type': 'PH',
  'm1': '7.45',
  'm2': '7.46',
  'm3': '7.39',
  'm4': '7.23',
  'm5': '7.15',
  'm6': '7.01',
  'm7': '6.83',
  'm8': '6.85',
  'm9': '6.92',
  'm10': '6.98',
  'm11': '7.08',
  'm12': '7.26'},
 {'name': '공산',
  'codenm': '정수',
  'type': '탁도',
  'm1': '0.06',
  'm2': '0.07',
  'm3': '0.07',
  'm4': '0.08',
  'm5': '0.09',
  'm6': '0.08',
  'm7': '0.08',
  'm8': '0.08',
  'm9': '0.08',
  'm10': '0.08',
  'm11': '0.07',
  'm12': '0.08'},
 {'name': '공산',
  'codenm': '정수',
  'type': '잔류염소',
  'm1': '0.71',
  'm2': '0.63',
  'm3': '0.63',
  'm4': '0.59',
  'm5': '0.69',
  'm6': '0.7',
  'm7': '0.82',
  'm8': '0.82',
  'm9': '0.84',
  'm10': '0.8',
  'm11': '0.76',
  'm12': '0.75'},
 {'name': '문산',
  'codenm': '정수',
  'type': 'PH',
  'm1': '7.33',
  'm2': '7.38',
  'm3': '7.17',
  'm4': '7.06',
  'm5': '6.94',
  'm6': '6.88',
  'm7': '6.9',
  'm8': '6.98',
  'm9': '6.98',
  'm10': '6.9',
  'm11': '6.84',
  'm12': '7.13'},
 {'name': '문산',
  'codenm': '정수',
  'type': '탁도',
  'm1': '0.05',
  'm2': '0.06',
  'm3': '0.07',
  'm4': '0.06',
  'm5': '0.05',
  'm6': '0.06',
  'm7': '0.07',
  'm8': '0.06',
  'm9': '0.06',
  'm10': '0.05',
  'm11': '0.04',
  'm12': '0.04'},
 {'name': '문산',
  'codenm': '정수',
  'type': '잔류염소',
  'm1': '0.6',
  'm2': '0.57',
  'm3': '0.59',
  'm4': '0.61',
  'm5': '0.65',
  'm6': '0.63',
  'm7': '0.76',
  'm8': '0.82',
  'm9': '0.88',
  'm10': '0.87',
  'm11': '0.74',
  'm12': '0.73'}]

In [12]:
len(data["list"])

21

In [13]:
df = pd.DataFrame(data["list"])
df.head()

,name,codenm,type,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12
0,가창,정수1,PH,7.03,7.08,7.12,7.12,7.08,7.08,7.06,7.01,7.06,7.09,7.06,7.06
1,가창,정수1,탁도,0.06,0.07,0.06,0.05,0.05,0.05,0.06,0.08,0.08,0.08,0.07,0.07
2,가창,정수1,잔류염소,0.61,0.6,0.59,0.57,0.58,0.58,0.58,0.58,0.58,0.6,0.61,0.6
3,가창,정수2,PH,7.11,7.19,7.17,7.16,7.07,7.06,7.12,7.,7.11,7.24,7.09,7.14
4,가창,정수2,탁도,0.06,0.07,0.07,0.06,0.06,0.06,0.06,0.06,0.07,0.07,0.05,0.07

In [14]:
# 데이터 가공 전 결측치 확인

null_counts = df.isnull().sum()
if null_counts.any():
    print("결측치 발견")
    print(null_counts[null_counts > 0])
else:
    print("결측치 없음")

결측치 없음

In [15]:
df.columns = data["header"]
df.head()

,정수장,구분,항목,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,가창,정수1,PH,7.03,7.08,7.12,7.12,7.08,7.08,7.06,7.01,7.06,7.09,7.06,7.06
1,가창,정수1,탁도,0.06,0.07,0.06,0.05,0.05,0.05,0.06,0.08,0.08,0.08,0.07,0.07
2,가창,정수1,잔류염소,0.61,0.6,0.59,0.57,0.58,0.58,0.58,0.58,0.58,0.6,0.61,0.6
3,가창,정수2,PH,7.11,7.19,7.17,7.16,7.07,7.06,7.12,7.,7.11,7.24,7.09,7.14
4,가창,정수2,탁도,0.06,0.07,0.07,0.06,0.06,0.06,0.06,0.06,0.07,0.07,0.05,0.07

In [16]:
# 월을 하나의 열로 바꾸기 위해 정리

id_cols = ["정수장", "구분", "항목"]
month_cols = [c for c in df.columns if "월" in c]

print(f"월별 컬럼 수 : {len(month_cols)}개")
print(f"월별 컬럼 목록 : {month_cols}")

월별 컬럼 수 : 12개
월별 컬럼 목록 : ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']

In [17]:
# 월별 데이터를 검사시기 컬럼을 생성해서 정리

df_1 = pd.melt(
    df,
    id_vars=id_cols,
    value_vars=month_cols,
    var_name="검사시기",
    value_name="측정값"
)

df_1.head()

  정수장   구분    항목 검사시기   측정값
0  가창  정수1    PH   1월  7.03
1  가창  정수1    탁도   1월  0.06
2  가창  정수1  잔류염소   1월  0.61
3  가창  정수2    PH   1월  7.11
4  가창  정수2    탁도   1월  0.06

In [18]:
# 검사시기에 조회년도 추가

df_1["검사시기"] = str(YEAR) + "년 " + df_1["검사시기"]

df_1.head()

  정수장   구분    항목      검사시기   측정값
0  가창  정수1    PH  2025년 1월  7.03
1  가창  정수1    탁도  2025년 1월  0.06
2  가창  정수1  잔류염소  2025년 1월  0.61
3  가창  정수2    PH  2025년 1월  7.11
4  가창  정수2    탁도  2025년 1월  0.06

In [19]:
# PH, 잔류염소, 탁도를 컬럼으로 변경

id2_cols = ["정수장", "구분", "검사시기"]

df_2 = df_1.pivot_table(
    index=id2_cols,
    columns="항목",
    values="측정값",
    aggfunc="first"
).reset_index()
df_2.columns.name = None

df_2.head()

  정수장   구분       검사시기    PH  잔류염소    탁도
0  가창  정수1  2025년 10월  7.09   0.6  0.08
1  가창  정수1  2025년 11월  7.06  0.61  0.07
2  가창  정수1  2025년 12월  7.06   0.6  0.07
3  가창  정수1   2025년 1월  7.03  0.61  0.06
4  가창  정수1   2025년 2월  7.08   0.6  0.07

In [20]:
# 검사시기를 다시 리스트로 정리

year_month = []

for i in month_cols:
    year_month.append(f"{YEAR}년 " + i)

year_month

['2025년 1월',
 '2025년 2월',
 '2025년 3월',
 '2025년 4월',
 '2025년 5월',
 '2025년 6월',
 '2025년 7월',
 '2025년 8월',
 '2025년 9월',
 '2025년 10월',
 '2025년 11월',
 '2025년 12월']

In [21]:
# 검사시기가 1월부터 순서대로 보이게 정리

df_2["검사시기"] = pd.Categorical(df_2["검사시기"], categories=year_month, ordered=True)
df_2 = df_2.sort_values(["정수장", "구분", "검사시기"]).reset_index(drop=True)

df_2.head()

  정수장   구분      검사시기    PH  잔류염소    탁도
0  가창  정수1  2025년 1월  7.03  0.61  0.06
1  가창  정수1  2025년 2월  7.08   0.6  0.07
2  가창  정수1  2025년 3월  7.12  0.59  0.06
3  가창  정수1  2025년 4월  7.12  0.57  0.05
4  가창  정수1  2025년 5월  7.08  0.58  0.05

In [22]:
# 컬럼 순서 재정리

df_water = df_2[["정수장", "구분", "PH", "탁도", "잔류염소", "검사시기"]]

df_water.head()

  정수장   구분    PH    탁도  잔류염소      검사시기
0  가창  정수1  7.03  0.06  0.61  2025년 1월
1  가창  정수1  7.08  0.07   0.6  2025년 2월
2  가창  정수1  7.12  0.06  0.59  2025년 3월
3  가창  정수1  7.12  0.05  0.57  2025년 4월
4  가창  정수1  7.08  0.05  0.58  2025년 5월

In [23]:
# 정리된 데이터프레임의 자료형 확인

df_water.dtypes

정수장          str
구분           str
PH           str
탁도           str
잔류염소         str
검사시기    category
dtype: object

In [24]:
# 정리된 데이터프레임에서 측정값을 실수형으로 형변환

if "PH" in df_water.columns:
    df_water["PH"] = pd.to_numeric(df_water["PH"], errors="coerce")

if "잔류염소" in df_water.columns:
    df_water["잔류염소"] = pd.to_numeric(df_water["잔류염소"], errors="coerce")

if "탁도" in df_water.columns:
    df_water["탁도"] = pd.to_numeric(df_water["탁도"], errors="coerce")

In [25]:
# 형변환 결과 확인

df_water.dtypes

정수장          str
구분           str
PH       float64
탁도       float64
잔류염소     float64
검사시기    category
dtype: object

In [26]:
# 가공이 종료된 데이터프레임 확인

df_water.head()

  정수장   구분    PH    탁도  잔류염소      검사시기
0  가창  정수1  7.03  0.06  0.61  2025년 1월
1  가창  정수1  7.08  0.07  0.60  2025년 2월
2  가창  정수1  7.12  0.06  0.59  2025년 3월
3  가창  정수1  7.12  0.05  0.57  2025년 4월
4  가창  정수1  7.08  0.05  0.58  2025년 5월

In [27]:
# 가공이 종료된 데이터프레임의 결측치 확인

null_counts = df_water.isnull().sum()
if null_counts.any():
    print("결측치 발견")
    print(null_counts[null_counts > 0])
else:
    print("결측치 없음")

결측치 없음

In [28]:
# 미리 작성해둔 행정구역별 정수장 파일 읽기

df_area = pd.read_csv(AREA_PATH)
df_area.head()

   구군  행정구역 정수장 급수분류
0  중구   동인동  매곡  전지역
1  중구   삼덕동  매곡  전지역
2  중구  성내1동  매곡  전지역
3  중구  성내2동  매곡  전지역
4  중구  성내3동  매곡  전지역

In [29]:
# 행정구역별 정수장 파일 결측치 확인

null_counts = df_area.isnull().sum()
if null_counts.any():
    print("결측치 발견")
    print(null_counts[null_counts > 0])
else:
    print("결측치 없음")

결측치 없음

In [30]:
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장"""
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)
    
    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text("SELECT version();")).fetchone()[0]
        print("PostgreSQL 연결 성공!")
        print(version[:80] + "...")

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=1000,
        method="multi",
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f"SELECT COUNT(*) FROM {table_name};")).fetchone()[0]

    print(f"{saved_count}행 저장 완료")
    print(f"DB : water_DB / table : {table_name}")

In [31]:
save_to_postgresql(df_water, DB_URL, "waterdb")

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
84행 저장 완료
DB : water_DB / table : waterdb

In [32]:
save_to_postgresql(df_area, DB_URL, "areadb")

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
155행 저장 완료
DB : water_DB / table : areadb

In [33]:
df_water.to_csv(WATER_OUTPUT_PATH, encoding="utf-8-sig", index=False)

print("CSV 저장 완료")
print(f"경로 : {WATER_OUTPUT_PATH}")
print(f"크기 : {len(df_water):,}행 × {len(df_water.columns)}열")

CSV 저장 완료
경로 : c:\Users\Administrator\bigdata2026\bigdata2026-basic\TEST\07_빅데이터수집시스템개발_김동욱\output\water.csv
크기 : 84행 × 6열

In [34]:
df_area.to_csv(AREA_OUTPUT_PATH, encoding="utf-8-sig", index=False)

print("CSV 저장 완료")
print(f"경로 : {AREA_OUTPUT_PATH}")
print(f"크기 : {len(df_area):,}행 × {len(df_area.columns)}열")

CSV 저장 완료
경로 : c:\Users\Administrator\bigdata2026\bigdata2026-basic\TEST\07_빅데이터수집시스템개발_김동욱\output\area.csv
크기 : 155행 × 4열