# 환경 설정

In [8]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

BASE_DIR = os.getcwd()
DATA_PATH = os.path.join(BASE_DIR, 'input', 'parkinglot_raw.csv')
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'parkinglot_long.csv')
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'

# 기본 문제

## 원본 데이터 확인

In [2]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [4]:
# 행, 열 개수 확인
df_raw.shape

(229, 27)

In [ ]:
# 컬럼명 확인
df_raw.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [ ]:
df_raw.dtypes

순번               int64
주차장관리번호            str
주차장명               str
주차장 유형             str
소재지지번주소            str
주차구획수            int64
급지구분             int64
부제시행구분             str
운영요일               str
평일운영시작시각           str
평일운영종료시각           str
토요일운영시작시각          str
토요일운영종료시각          str
공휴일운영시작시각          str
공유일운영종료시각          str
요금정보               str
주차기본시간           int64
주차기본요금           int64
추가단위시간           int64
추가단위요금           int64
1일주차권요금적용시간      int64
1일주차권적용시간        int64
월정기요금            int64
결제방법               str
관리기관명              str
경도             float64
위도             float64
dtype: object

## 새로운 DataFrame 만들기

In [12]:
# 주차장명, 소재지지번주소, 주차구획수 컬럼 선택
df_selected = df_raw[['주차장명', '소재지지번주소', '주차구획수']]
df_selected.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

## DB 저장

In [9]:
TABLE_NAME = 'parking_lot'

In [14]:
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL에 저장"""
    df_save = df.copy()

    # 문자열 컬럼 → str
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)
    
    # 엔진 생성
    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공')
        print(version[:80] + '...')

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name}')).fetchone()[0]
    print(f'저장 완료 {saved_count}행')
    print(f'DB : parkingdb / table : {table_name}')

In [ ]:
save_to_postgresql(df_selected, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 229행
DB : parkingdb / table : parking_lot

# 추가문제

In [42]:
df_add = df_raw[['주차장명', '소재지지번주소', '주차구획수']]
df_add.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

## 규모구분 컬럼 추가

In [43]:
def get_size(num):
    if num < 20:
        return '소형'
    elif num <= 50:
        return '중형'
    else:
        return '대형'
    
df_add['규모구분'] = df_add['주차구획수'].apply(get_size)
df_add.head()

        주차장명               소재지지번주소  주차구획수 규모구분
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형

## 동이름 컬럼 추가

In [44]:
temp = df_add['소재지지번주소'].str.split(' ')
temp

0      [대구광역시, 북구, 노원동3가, 191-1]
1         [대구광역시, 북구, 노원동3가, 14]
2        [대구광역시, 북구, 검단동, 745-2]
3          [대구광역시, 북구, 복현동, 573]
4       [대구광역시, 북구, 복현동, 606-34]
                 ...
224       [대구광역시, 북구, 산격동, 1393]
225      [대구광역시, 북구, 복현동, 439-1]
226    [대구광역시, 북구, 산격동, 1216-24]
227     [대구광역시, 북구, 구암동, 615-13]
228     [대구광역시, 북구, 구암동, 615-13]
Name: 소재지지번주소, Length: 229, dtype: object

In [46]:
df_add['동이름'] = [i[2] for i in df_add['소재지지번주소'].str.split(' ')]
df_add.head()

        주차장명               소재지지번주소  주차구획수 규모구분    동이름
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형  노원동3가
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형  노원동3가
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형    검단동
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형    복현동
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형    복현동

## DB 저장

In [47]:
save_to_postgresql(df_add, DB_URL, 'parking_lot_v2')

PostgreSQL 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 229행
DB : parkingdb / table : parking_lot_v2