In [ ]:
# xml 파싱용 라이브러리
# uv add lxml
# uv add xmltodict

### 한국산업기술진흥원_기술은행 수요기술 조회 서비스_GW

### 라이브러리 불러오기

In [2]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import requests
import xmltodict
import math
import time
import re # xml 파일 문자 검증용 라이브러리
from datetime import date

### API 키

In [3]:
load_dotenv()
API_KEY = os.getenv('NTB_API_KEY')

if API_KEY:
    print(f'key 확인 {API_KEY[:6]}...{API_KEY[-4:]}')

key 확인 a82ec1...e8ad

### API 연결 테스트

In [4]:
BASE_URL = 'https://apis.data.go.kr/B552536/tech_1/needtech'

In [5]:
response = requests.get(BASE_URL, params={
    'serviceKey':API_KEY,
    'pageNo': 3,
    'numOfRows':1000,
})
print(response.status_code)

200

In [6]:
content = response.text

In [7]:
# xml 이상 문자 삭제
clean_content = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F]", "", content)

In [8]:
# xml을 딕셔너리로 변경
data = xmltodict.parse(clean_content)
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'dmdtchNm': '범용 Simulator 개발 (가상 Machine)',
      'dmdtchNo': '00000002014',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '6개월이내',
      'hopetchSumnsfeCn': '? 기술 개요\r\n· 자동화 소프트웨어 기술로 산업용 자동화 설비에 대한 제어 및 영상처리에 특화된 기술력을 보유하고 있습니다.\r\n기술개요\r\n장비가 없는 상태에서 소프트웨어 개발이 병행되어야만하며 가상 Machine 역할을 하는\r\nSimulator가 요청되고 있습니다.\r\n자사진행내용\r\n특정장비, 특정부품에 맞는 Simulator 개발 및 통신기능만 확인할 수 있는 범용 Simulator \r\nPrototype 개발경험을 보유하고 있음에 따라,\r\n실제 장비처럼 동작되기 위해서는 Sequence 제어에 대한 기술니즈 있음',
      'keyword': '범용 simulat,가상 machine,유비샘,,',
      'rownum': '2001',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '기타',
      'tchlgyPccndCn': '산단공\r\n*지원센터컨설턴트',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '서울'},
     {'buyKindNm': '기술매매',
      'dmdtchNm': 'F1_WMDS(악성코드 유포 탐지 솔루션)',
      'dmdtchNo': '00000002015',
      'dmdtchPrgstCd': '신청',
      'hopepcEraCd': '9개월이내',
      'hopetchSumnsfeCn': '1.기술개요\r\n가. 기술개발 최종 목표 모습\r\n- 악성프로그램 유포코드 패턴 분석 기술개발로 유포지 탐지\r\n- 악성코드 유포사이트로의 접근 차단 기술 개발\r\n- ASP 서비스 모델 개발\r\n2. 자사에서 현재가지 진행된 내용\r\n가. 악성코드 유포패턴 분석기술\r\n- html 컨텐츠 내에 존재하는 악성코드 유포패턴을 분석해서 탐지 할 수 있는 기술 : 악성프로그램 유포코드에 사용되는 html tag의 패턴 담지\r\n-재로데이 취약점에 대한 사전대응이 가능한 기술\r\n나. 악성코드 유포 차단기술(개발중)\r\n- passive mode 기반 악성코드 유포사이트 접근차단기술 : 패킷 미러링 구성을 통한 악성코드 유포사이트 차단기술 \r\n- TCP Geader Reset Flag 이용\r\n- 사내 PC의 외부 홈페이지 접근으로 인한 악성코드 감염사고 차단\r\n다. ASP서비스 모델 개발\r\n- 서비스형태(ASP)의 제품 출시: 중/소기업고객을 위한 ASP서비스 형태의 제품',
      'keyword': '악성코드,솔루현,탐지,,',
      'rownum': '2002',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '산단공\r\n*지원센터 컨설턴트',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '서울'},
     {'buyKindNm': '기술매매,기술협력',
      'dmdtchNm': 'IOT 플랫폼 기술',
      'dmdtchNo': '00000002016',
      'dmdtchPrgstCd': '신청',
      'hopepcEraCd': '9개월이내',
      'hopetchSumnsfeCn': '1.개요 \r\n-IOT 플랫폼 기술\r\n-IOT 서비스 플랫폼 연동 기술\r\n-IOT 미들웨어\r\n2. 관련자사역량\r\n-다수의 IOT프로젝트 참여를 통한 플랫폼 관련지식 보유\r\n-다수의 M2M 프로젝트참여를 통한 관련 오하우 보유',
      'keyword': 'IOT,IOT 플랫폼 ,IOT 미들웨어,빅데이터,',
      'rownum': '2003',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '산단공\r\n*지원센터컨설턴트',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '서울'},
     {'buyKindNm': '기술매매,기술협력,기술지도',
      'dmdtchNm': '스크래치 HDD 복구 기술 개발',
      'dmdtchNo': '00000002017',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '9개월이내',
      'hopetchSumnsfeCn': '-미세가공기술/표면처리기술 \r\n-HDD구성품중 플리터 표면에 발생한 스크래치의 평판화\r\n\r\n-플래터 표면의 스크래치 상태 확인(교통대 공동장비 활용)\r\n-HDD 재 조립시 밸런스 회복 및 data reed 기술확보\r\n-클린룸 보유\r\n-확보된 지재권 없음',
      'keyword': 'hdd,복구,스크래치,,',
      'rownum': '2004',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '산단공\r\n*지원센터컨설턴트',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '충북'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '에센셜 오일을 이용한 비누제조',
      'dmdtchNo': '00000002018',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '- 에센셜 오일을 이용한 향기나는 비누 제조 희망',
      'keyword': '비누,향기비누,에센셜오일,,',
      'rownum': '2005',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '상담후 결정',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '실리콘 렌즈 설계 및 공정기술',
      'dmdtchNo': '00000002019',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': None,
      'keyword': '렌즈,실리콘,렌즈공정,,',
      'rownum': '2006',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '고효율 간접 증발식 냉각장치 관련 기술',
      'dmdtchNo': '00000002020',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '3개월이내',
      'hopetchSumnsfeCn': None,
      'keyword': '냉각장치,증발식,간접,,',
      'rownum': '2007',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '위치 측위 시스템 개발',
      'dmdtchNo': '00000002021',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '미아방지를 목적으로 기기를 이용한 이격거리 확인 및 음성통신을 통해 상태를 확인할 수 있는 제품 제작',
      'keyword': '위치 측위,미아방지,음성통신,,',
      'rownum': '2008',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '야콘 추출물을 이용한 향균용 기능성 식품개발',
      'dmdtchNo': '00000002022',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '3개월이내',
      'hopetchSumnsfeCn': '야콘 추출물 또는 분획물을 포함한 향균용 조성물',
      'keyword': '야콘,야콘 추출물 식품,향균용,,',
      'rownum': '2009',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '오픈 마켓 위탁 배송시스템',
      'dmdtchNo': '00000002023',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '비용 절감 및 효율성이 증대한 위탁 배송시스템',
      'keyword': '배송시스템,위탁배송,오픈마켓,,',
      'rownum': '2010',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '배송시스템 개선',
      'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '온실용 난방기에 장착 가능한 제습기 기술',
      'dmdtchNo': '00000002024',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '온실내 과습으로 인한 작물 피해를 방지하기 위한 온습조절장치의 필요',
      'keyword': '온실용 제습기,온습조절장치,온실난방기,,',
      'rownum': '2011',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '75L 급 Toroida LPG Tank 내압 최적화 설계',
      'dmdtchNo': '00000002025',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': None,
      'keyword': 'LPG탱크,압력용기,내압 최적화,,',
      'rownum': '2012',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매',
      'dmdtchNm': '아연도금강판의 내식성 향상을 위한 기술',
      'dmdtchNo': '00000002026',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '아연도금 강판의 내식성 향상을 위한 표면처리방법의 필요',
      'keyword': '아연도금 ,아연도금내식성,아연도금표면처리,,',
      'rownum': '2013',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '제품공정 개선',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '소형비행기 비행 안정화 알고리즘 기술',
      'dmdtchNo': '00000002027',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '소형비행체 기반의 다중센서를 이용한 구조물 안정성 검사를 위함\r\n장애물에 대한 충돌 방지 및 안전한 비행을 위함',
      'keyword': '비행안정화,소형비행기,드론,,',
      'rownum': '2014',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '드론 기반 무선 송,수신 시스템 개발 기술',
      'dmdtchNo': '00000002028',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '드론에서 취득된 영상 및 데이터를 무선 전송하는 기술\r\n지상의 검사자가 모니터를 통해 쉽게 판독 가능한 기술',
      'keyword': '무선 송수신 시스템,드론,데이터전송,,',
      'rownum': '2015',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '맑은 국화주 제조방법',
      'dmdtchNo': '00000002029',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '청주시 시화인 국화를 이용한 술 제조를 하고자 하는기업\r\n제품의 차별성을 위해 무색의 맑은 술 제조기술 필요',
      'keyword': '술,국화,맑은술,,',
      'rownum': '2016',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '하우스용 환풍기',
      'dmdtchNo': '00000002030',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '환풍기 모터의 작동유무에 따른 환기구 개폐조작을 하는 하우스용 환풍기',
      'keyword': '환풍기,하우스용환풍기,개폐조작,,',
      'rownum': '2017',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '제습, 가습 및 공기정화 겸용 복합기 개발 기술',
      'dmdtchNo': '00000002031',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '미세먼지, 대기오염의 심각성의 종래의 공기정화기나 가습기보다도 더 뛰어난 정화능력을 가진 복합기 개발',
      'keyword': '공기정화,제습,가습,,',
      'rownum': '2018',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '실내용 식물 재배 장치 개발',
      'dmdtchNo': '00000002032',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '직접 식물을 재배해 먹는 사람들의 증가로 손쉬운 식물 재배를 위한 장치 개발',
      'keyword': '식물재배장치,실내재배,실내용,,',
      'rownum': '2019',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '잔디 품종 개량을 위한 신기술',
      'dmdtchNo': '00000002033',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '지역 특산품인 잔디의 품종개량의 필요',
      'keyword': '잔디,품종,개량,,',
      'rownum': '2020',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '품종개량',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '함초를 이용한 건강음료 개발',
      'dmdtchNo': '00000002034',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '함초의 효능을 이용한 음료 개발',
      'keyword': '함초,건강음료,함초성분,,',
      'rownum': '2021',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '농수축산물 인증을 위한 플랫폼 개발',
      'dmdtchNo': '00000002035',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '먹거리에 대한 불안감 감소를 위한 스마트폰을 이용한 농수축산물 인증 플랫폼',
      'keyword': '품질인증,농수축산물,스마트폰,,',
      'rownum': '2022',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '프로그램 개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '매생이를 활요한 즉석 식품 개발',
      'dmdtchNo': '00000002036',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '몸에 좋은 매생이를 이용한 즉석 식품 개발',
      'keyword': '매생이,즉석요리,건조,,',
      'rownum': '2023',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매',
      'dmdtchNm': '건강 기능성 환제조 기술',
      'dmdtchNo': '00000002037',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '건강기능성 환 제조 기술 필요',
      'keyword': '건강기능식품,환,환제조,,',
      'rownum': '2024',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매',
      'dmdtchNm': 'Auto CAD 검도 솔루션 아키텍쳐 재설계 기술',
      'dmdtchNo': '00000002038',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': None,
      'keyword': 'Auto CAD ,검도 솔루션,아키텍쳐 재설계 ,,',
      'rownum': '2025',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매',
      'dmdtchNm': '표고버섯을 활용한 기능성 버섯소금 제조',
      'dmdtchNo': '00000002039',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': None,
      'keyword': '버섯소금,표고버섯,소금제조,,',
      'rownum': '2026',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '참바늘버섯 인공배양 방법',
      'dmdtchNo': '00000002040',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '일본에서 많이 소비되는 참바늘 버섯의 국내 판매 증대 예상으로 \r\n해당 버섯의 인공배양 방법 필요',
      'keyword': '참바늘버섯,인공배양,버섯,,',
      'rownum': '2027',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '황칠 성분이 들어있는 국수 제조방법',
      'dmdtchNo': '00000002041',
      'dmdtchPrgstCd': '컨설팅완료',
      'hopepcEraCd': '즉시',
      'hopetchSumnsfeCn': '황칠성분이 포함된 식품 제조\r\n한국인이 많이 먹는 국수에 황칠성분을 포함하여 신제품 개발',
      'keyword': '황칠,국수,첨가,,',
      'rownum': '2028',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '기술매매,라이센스',
      'dmdtchNm': '연결선 정리가 용이한 멀티탭 관련 기술',
      'dmdtchNo': '00000002042',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '6개월이내',
      'hopetchSumnsfeCn': '기존 전선 정리가 복잡했던 멀티탭의 불편한 점을 개선한 멀티탭 (전선 정리 용이)',
      'keyword': '멀티탭,선정리,환경개선,,',
      'rownum': '2029',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품개발',
      'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '전남'},
     {'buyKindNm': '라이센스',
      'dmdtchNm': 'batteng 관리 시스템 기술',
      'dmdtchNo': '00000002043',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '6개월이내',
      'hopetchSumnsfeCn': None,
      'keyword': 'batteng,관리,시스템,,',
      'rownum': '2030',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '기술이전 조건 추후 협의',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '부산'},
     {'buyKindNm': '라이센스',
      'dmdtchNm': '플라스틱 사출, 금형, 정밀가공(금속 및 플라스틱), CNC선반, MCT 밀링',
      'dmdtchNo': '00000002044',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '6개월이내',
      'hopetchSumnsfeCn': None,
      'keyword': '금형,정밀가공,,,',
      'rownum': '2031',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '기술이전 조건 추후 협의',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '부산'},
     {'buyKindNm': '라이센스',
      'dmdtchNm': '해양용 볼 밸브 관련 기술',
      'dmdtchNo': '00000002045',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '6개월이내',
      'hopetchSumnsfeCn': None,
      'keyword': '해양,벨브,,,',
      'rownum': '2032',
      'tchdlSpinsttNm': None,
      'tchlgyIndcprDtl': '신제품 개발',
      'tchlgyPccndCn': '기술이전 조건 추후 협의',
      'tcntrnCntrctDc': None,
      'tcntrnCntrctTy': None,
      'tcntrnFxamtTchfee': None,
      'tcntrnOdtfcndDc': None,
      'tcntrnOrdnrTchfee': None,
      'tpDmandCdNm': '부산'},
     {'buyKindNm': '라이센스',
      'dmdtchNm': '덕트 청소용 로봇',
      'dmdtchNo': '00000002046',
      'dmdtchPrgstCd': '컨설팅매칭',
      'hopepcEraCd': '6개월이내',
      'hopetchSumnsfeCn': None,
      'keyword': '청소용,로봇,,,',
      'rownum': '2033',

In [9]:
data['response']['body']['items']['item']

[{'dmdtchNm': '범용 Simulator 개발 (가상 Machine)',
  'dmdtchNo': '00000002014',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': '? 기술 개요\r\n· 자동화 소프트웨어 기술로 산업용 자동화 설비에 대한 제어 및 영상처리에 특화된 기술력을 보유하고 있습니다.\r\n기술개요\r\n장비가 없는 상태에서 소프트웨어 개발이 병행되어야만하며 가상 Machine 역할을 하는\r\nSimulator가 요청되고 있습니다.\r\n자사진행내용\r\n특정장비, 특정부품에 맞는 Simulator 개발 및 통신기능만 확인할 수 있는 범용 Simulator \r\nPrototype 개발경험을 보유하고 있음에 따라,\r\n실제 장비처럼 동작되기 위해서는 Sequence 제어에 대한 기술니즈 있음',
  'keyword': '범용 simulat,가상 machine,유비샘,,',
  'rownum': '2001',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '기타',
  'tchlgyPccndCn': '산단공\r\n*지원센터컨설턴트',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '서울'},
 {'buyKindNm': '기술매매',
  'dmdtchNm': 'F1_WMDS(악성코드 유포 탐지 솔루션)',
  'dmdtchNo': '00000002015',
  'dmdtchPrgstCd': '신청',
  'hopepcEraCd': '9개월이내',
  'hopetchSumnsfeCn': '1.기술개요\r\n가. 기술개발 최종 목표 모습\r\n- 악성프로그램 유포코드 패턴 분석 기술개발로 유포지 탐지\r\n- 악성코드 유포사이트로의 접근 차단 기술 개발\r\n- ASP 서비스 모델 개발\r\n2. 자사에서 현재가지 진행된 내용\r\n가. 악성코드 유포패턴 분석기술\r\n- html 컨텐츠 내에 존재하는 악성코드 유포패턴을 분석해서 탐지 할 수 있는 기술 : 악성프로그램 유포코드에 사용되는 html tag의 패턴 담지\r\n-재로데이 취약점에 대한 사전대응이 가능한 기술\r\n나. 악성코드 유포 차단기술(개발중)\r\n- passive mode 기반 악성코드 유포사이트 접근차단기술 : 패킷 미러링 구성을 통한 악성코드 유포사이트 차단기술 \r\n- TCP Geader Reset Flag 이용\r\n- 사내 PC의 외부 홈페이지 접근으로 인한 악성코드 감염사고 차단\r\n다. ASP서비스 모델 개발\r\n- 서비스형태(ASP)의 제품 출시: 중/소기업고객을 위한 ASP서비스 형태의 제품',
  'keyword': '악성코드,솔루현,탐지,,',
  'rownum': '2002',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '산단공\r\n*지원센터 컨설턴트',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '서울'},
 {'buyKindNm': '기술매매,기술협력',
  'dmdtchNm': 'IOT 플랫폼 기술',
  'dmdtchNo': '00000002016',
  'dmdtchPrgstCd': '신청',
  'hopepcEraCd': '9개월이내',
  'hopetchSumnsfeCn': '1.개요 \r\n-IOT 플랫폼 기술\r\n-IOT 서비스 플랫폼 연동 기술\r\n-IOT 미들웨어\r\n2. 관련자사역량\r\n-다수의 IOT프로젝트 참여를 통한 플랫폼 관련지식 보유\r\n-다수의 M2M 프로젝트참여를 통한 관련 오하우 보유',
  'keyword': 'IOT,IOT 플랫폼 ,IOT 미들웨어,빅데이터,',
  'rownum': '2003',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '산단공\r\n*지원센터컨설턴트',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '서울'},
 {'buyKindNm': '기술매매,기술협력,기술지도',
  'dmdtchNm': '스크래치 HDD 복구 기술 개발',
  'dmdtchNo': '00000002017',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '9개월이내',
  'hopetchSumnsfeCn': '-미세가공기술/표면처리기술 \r\n-HDD구성품중 플리터 표면에 발생한 스크래치의 평판화\r\n\r\n-플래터 표면의 스크래치 상태 확인(교통대 공동장비 활용)\r\n-HDD 재 조립시 밸런스 회복 및 data reed 기술확보\r\n-클린룸 보유\r\n-확보된 지재권 없음',
  'keyword': 'hdd,복구,스크래치,,',
  'rownum': '2004',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '산단공\r\n*지원센터컨설턴트',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '충북'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '에센셜 오일을 이용한 비누제조',
  'dmdtchNo': '00000002018',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '- 에센셜 오일을 이용한 향기나는 비누 제조 희망',
  'keyword': '비누,향기비누,에센셜오일,,',
  'rownum': '2005',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '상담후 결정',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '실리콘 렌즈 설계 및 공정기술',
  'dmdtchNo': '00000002019',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': None,
  'keyword': '렌즈,실리콘,렌즈공정,,',
  'rownum': '2006',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '고효율 간접 증발식 냉각장치 관련 기술',
  'dmdtchNo': '00000002020',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '3개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '냉각장치,증발식,간접,,',
  'rownum': '2007',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '위치 측위 시스템 개발',
  'dmdtchNo': '00000002021',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '미아방지를 목적으로 기기를 이용한 이격거리 확인 및 음성통신을 통해 상태를 확인할 수 있는 제품 제작',
  'keyword': '위치 측위,미아방지,음성통신,,',
  'rownum': '2008',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '야콘 추출물을 이용한 향균용 기능성 식품개발',
  'dmdtchNo': '00000002022',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '3개월이내',
  'hopetchSumnsfeCn': '야콘 추출물 또는 분획물을 포함한 향균용 조성물',
  'keyword': '야콘,야콘 추출물 식품,향균용,,',
  'rownum': '2009',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '오픈 마켓 위탁 배송시스템',
  'dmdtchNo': '00000002023',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '비용 절감 및 효율성이 증대한 위탁 배송시스템',
  'keyword': '배송시스템,위탁배송,오픈마켓,,',
  'rownum': '2010',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '배송시스템 개선',
  'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '온실용 난방기에 장착 가능한 제습기 기술',
  'dmdtchNo': '00000002024',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '온실내 과습으로 인한 작물 피해를 방지하기 위한 온습조절장치의 필요',
  'keyword': '온실용 제습기,온습조절장치,온실난방기,,',
  'rownum': '2011',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n* 전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '75L 급 Toroida LPG Tank 내압 최적화 설계',
  'dmdtchNo': '00000002025',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': None,
  'keyword': 'LPG탱크,압력용기,내압 최적화,,',
  'rownum': '2012',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매',
  'dmdtchNm': '아연도금강판의 내식성 향상을 위한 기술',
  'dmdtchNo': '00000002026',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '아연도금 강판의 내식성 향상을 위한 표면처리방법의 필요',
  'keyword': '아연도금 ,아연도금내식성,아연도금표면처리,,',
  'rownum': '2013',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '제품공정 개선',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '소형비행기 비행 안정화 알고리즘 기술',
  'dmdtchNo': '00000002027',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '소형비행체 기반의 다중센서를 이용한 구조물 안정성 검사를 위함\r\n장애물에 대한 충돌 방지 및 안전한 비행을 위함',
  'keyword': '비행안정화,소형비행기,드론,,',
  'rownum': '2014',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '드론 기반 무선 송,수신 시스템 개발 기술',
  'dmdtchNo': '00000002028',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '드론에서 취득된 영상 및 데이터를 무선 전송하는 기술\r\n지상의 검사자가 모니터를 통해 쉽게 판독 가능한 기술',
  'keyword': '무선 송수신 시스템,드론,데이터전송,,',
  'rownum': '2015',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '맑은 국화주 제조방법',
  'dmdtchNo': '00000002029',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '청주시 시화인 국화를 이용한 술 제조를 하고자 하는기업\r\n제품의 차별성을 위해 무색의 맑은 술 제조기술 필요',
  'keyword': '술,국화,맑은술,,',
  'rownum': '2016',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '하우스용 환풍기',
  'dmdtchNo': '00000002030',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '환풍기 모터의 작동유무에 따른 환기구 개폐조작을 하는 하우스용 환풍기',
  'keyword': '환풍기,하우스용환풍기,개폐조작,,',
  'rownum': '2017',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '제습, 가습 및 공기정화 겸용 복합기 개발 기술',
  'dmdtchNo': '00000002031',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '미세먼지, 대기오염의 심각성의 종래의 공기정화기나 가습기보다도 더 뛰어난 정화능력을 가진 복합기 개발',
  'keyword': '공기정화,제습,가습,,',
  'rownum': '2018',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '실내용 식물 재배 장치 개발',
  'dmdtchNo': '00000002032',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '직접 식물을 재배해 먹는 사람들의 증가로 손쉬운 식물 재배를 위한 장치 개발',
  'keyword': '식물재배장치,실내재배,실내용,,',
  'rownum': '2019',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '잔디 품종 개량을 위한 신기술',
  'dmdtchNo': '00000002033',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '지역 특산품인 잔디의 품종개량의 필요',
  'keyword': '잔디,품종,개량,,',
  'rownum': '2020',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '품종개량',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '함초를 이용한 건강음료 개발',
  'dmdtchNo': '00000002034',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '함초의 효능을 이용한 음료 개발',
  'keyword': '함초,건강음료,함초성분,,',
  'rownum': '2021',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '농수축산물 인증을 위한 플랫폼 개발',
  'dmdtchNo': '00000002035',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '먹거리에 대한 불안감 감소를 위한 스마트폰을 이용한 농수축산물 인증 플랫폼',
  'keyword': '품질인증,농수축산물,스마트폰,,',
  'rownum': '2022',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '프로그램 개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '매생이를 활요한 즉석 식품 개발',
  'dmdtchNo': '00000002036',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '몸에 좋은 매생이를 이용한 즉석 식품 개발',
  'keyword': '매생이,즉석요리,건조,,',
  'rownum': '2023',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매',
  'dmdtchNm': '건강 기능성 환제조 기술',
  'dmdtchNo': '00000002037',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '건강기능성 환 제조 기술 필요',
  'keyword': '건강기능식품,환,환제조,,',
  'rownum': '2024',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매',
  'dmdtchNm': 'Auto CAD 검도 솔루션 아키텍쳐 재설계 기술',
  'dmdtchNo': '00000002038',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': None,
  'keyword': 'Auto CAD ,검도 솔루션,아키텍쳐 재설계 ,,',
  'rownum': '2025',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매',
  'dmdtchNm': '표고버섯을 활용한 기능성 버섯소금 제조',
  'dmdtchNo': '00000002039',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': None,
  'keyword': '버섯소금,표고버섯,소금제조,,',
  'rownum': '2026',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '참바늘버섯 인공배양 방법',
  'dmdtchNo': '00000002040',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '일본에서 많이 소비되는 참바늘 버섯의 국내 판매 증대 예상으로 \r\n해당 버섯의 인공배양 방법 필요',
  'keyword': '참바늘버섯,인공배양,버섯,,',
  'rownum': '2027',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '황칠 성분이 들어있는 국수 제조방법',
  'dmdtchNo': '00000002041',
  'dmdtchPrgstCd': '컨설팅완료',
  'hopepcEraCd': '즉시',
  'hopetchSumnsfeCn': '황칠성분이 포함된 식품 제조\r\n한국인이 많이 먹는 국수에 황칠성분을 포함하여 신제품 개발',
  'keyword': '황칠,국수,첨가,,',
  'rownum': '2028',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '기술매매,라이센스',
  'dmdtchNm': '연결선 정리가 용이한 멀티탭 관련 기술',
  'dmdtchNo': '00000002042',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': '기존 전선 정리가 복잡했던 멀티탭의 불편한 점을 개선한 멀티탭 (전선 정리 용이)',
  'keyword': '멀티탭,선정리,환경개선,,',
  'rownum': '2029',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품개발',
  'tchlgyPccndCn': '협의후 결정\r\n*전남TP 기술이전센터 컨설팅',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '전남'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': 'batteng 관리 시스템 기술',
  'dmdtchNo': '00000002043',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': 'batteng,관리,시스템,,',
  'rownum': '2030',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '플라스틱 사출, 금형, 정밀가공(금속 및 플라스틱), CNC선반, MCT 밀링',
  'dmdtchNo': '00000002044',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '금형,정밀가공,,,',
  'rownum': '2031',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '해양용 볼 밸브 관련 기술',
  'dmdtchNo': '00000002045',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '해양,벨브,,,',
  'rownum': '2032',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '덕트 청소용 로봇',
  'dmdtchNo': '00000002046',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '청소용,로봇,,,',
  'rownum': '2033',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '천연 살충제 조성물 및 이를 이용한 살충방법',
  'dmdtchNo': '00000002047',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '살충제,천연,,,',
  'rownum': '2034',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신재품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '정밀수로용, 수형',
  'dmdtchNo': '00000002048',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '수로용,수형,,,',
  'rownum': '2035',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '유플렉스 스테인리스강, 용접봉 조성물',
  'dmdtchNo': '00000002049',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '스테인리스,용접봉,,,',
  'rownum': '2036',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '이종 소재의 철도 차량의 차륜 등',
  'dmdtchNo': '00000002050',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,
  'keyword': '철ㄷ,차륜,,,',
  'rownum': '2037',
  'tchdlSpinsttNm': None,
  'tchlgyIndcprDtl': '신제품 개발',
  'tchlgyPccndCn': '기술이전 조건 추후 협의',
  'tcntrnCntrctDc': None,
  'tcntrnCntrctTy': None,
  'tcntrnFxamtTchfee': None,
  'tcntrnOdtfcndDc': None,
  'tcntrnOrdnrTchfee': None,
  'tpDmandCdNm': '부산'},
 {'buyKindNm': '라이센스',
  'dmdtchNm': '방폭장비, 철의장 개폐장치, LNG 저장탱크',
  'dmdtchNo': '00000002051',
  'dmdtchPrgstCd': '컨설팅매칭',
  'hopepcEraCd': '6개월이내',
  'hopetchSumnsfeCn': None,

### 환경 설정

In [10]:
BASE_URL = 'https://apis.data.go.kr/B552536/tech_1/needtech'
ROWS_PER_PAGE = 1000
REQUEST_TIMEOUT = 10

### 저장경로

In [11]:
BASE_DIR = os.getcwd() #현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR,'NTB_db.csv')

In [12]:
data['response']['body']['totalCount']

'11231'

In [13]:
total_count = int(data['response']['body']['totalCount'])
total_pages = math.ceil(total_count/ ROWS_PER_PAGE)
print(f'{total_count:,}')
print(total_pages)

11,231
12

### 전체 데이터 수집

In [14]:
all_items = []

for page_no in range(1, total_pages+1):
    params = {
        'serviceKey':API_KEY,
        'pageNo': page_no,
        'numOfRows': ROWS_PER_PAGE,
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    clean_content = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F]", "", response.text)
    
    page_body = xmltodict.parse(clean_content)['response']['body']

    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지: 페이지 없음')
        continue

    page_items = page_body['items'].get('item', []) 

    if isinstance(page_items, dict):
        page_items = [page_items]

    all_items.extend(page_items)

    print(f'{page_no} / {total_pages} 페이지 수집 완료 --> 누적 {len(all_items):,}건')
    
    time.sleep(0.2)

print(f'전체 수집 완료 {len(all_items):,}건')

1 / 12 페이지 수집 완료 --> 누적 1,000건
2 / 12 페이지 수집 완료 --> 누적 2,000건
3 / 12 페이지 수집 완료 --> 누적 3,000건
4 / 12 페이지 수집 완료 --> 누적 4,000건
5 / 12 페이지 수집 완료 --> 누적 5,000건
6 / 12 페이지 수집 완료 --> 누적 6,000건
7 / 12 페이지 수집 완료 --> 누적 7,000건
8 / 12 페이지 수집 완료 --> 누적 8,000건
9 / 12 페이지 수집 완료 --> 누적 9,000건
10 / 12 페이지 수집 완료 --> 누적 10,000건
11 / 12 페이지 수집 완료 --> 누적 11,000건
12 / 12 페이지 수집 완료 --> 누적 11,231건
전체 수집 완료 11,231건

### 데이터 프레임 만들기

In [15]:
df_raw = pd.DataFrame(all_items)

print(f'데이터프레임의  : {df_raw.shape}')
print(f'컬럼 목록 : {df_raw.columns.tolist()}')

데이터프레임의  : (11231, 17)
컬럼 목록 : ['buyKindNm', 'dmdtchNm', 'dmdtchNo', 'dmdtchPrgstCd', 'hopepcEraCd', 'hopetchSumnsfeCn', 'keyword', 'rownum', 'tchdlSpinsttNm', 'tchlgyIndcprDtl', 'tchlgyPccndCn', 'tcntrnCntrctDc', 'tcntrnCntrctTy', 'tcntrnFxamtTchfee', 'tcntrnOdtfcndDc', 'tcntrnOrdnrTchfee', 'tpDmandCdNm']

In [16]:
df_raw.head()

,buyKindNm,dmdtchNm,dmdtchNo,dmdtchPrgstCd,hopepcEraCd,hopetchSumnsfeCn,keyword,rownum,tchdlSpinsttNm,tchlgyIndcprDtl,tchlgyPccndCn,tcntrnCntrctDc,tcntrnCntrctTy,tcntrnFxamtTchfee,tcntrnOdtfcndDc,tcntrnOrdnrTchfee,tpDmandCdNm
0,"기술매매,기술협력",콩 발효기술,00000000001,수요기업만족도체크,3개월이내,새로운 방식의 콩 식품 개발용 발효 종균,"콩,발효,,,",1,NaN,사업화,협의,NaN,NaN,NaN,NaN,NaN,서울
1,"라이센스,기술협력,기술지도","비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부 미백기술",00000000002,컨설팅완료,3개월이내,"1. 수요기술 개요\r\n비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부...","비목나무,추출물,분획물,화합물,피부미백",2,NaN,신제품 개발,화장품 소재 개발에 투입될 수 있는 기술 필요.\r\n관련 기술 개량 발명에 대한 ...,NaN,NaN,NaN,NaN,NaN,제주
2,"라이센스,기술협력,기술지도",경단구슬모자반 추출물을 활용한 알러지성 질환 개선기술,00000000003,컨설팅완료,3개월이내,1. 수요기술의 개요\r\n경단구슬모자반(Sargassum muticum) 추출물 ...,"경단구슬모자반,추출물,알러지성,질환,",3,NaN,신제품 개발,제품에 바로 적용할 수 있는 상용화기술 필요,NaN,NaN,NaN,NaN,NaN,제주
3,"라이센스,기술협력","홈쇼핑, 대형마트 등에서 유통이 가능한 생활용품",00000000004,컨설팅완료,3개월이내,"생활용품 중심의 아이디어 제품이 가능한 특허기술을 도입하고, 제품 디자인, 시제품 ...","디자인,제품화,유통,,",4,NaN,신규 아이디어 제품 양산 및 유통 협력,"기술협력을 통하여 제품 출시 및 유통에 따른 매출 발생시, 이익 공유",NaN,NaN,NaN,NaN,NaN,경기
4,"기술매매,기술협력,기술지도",콩을 활용한 응용식품,00000000005,컨설팅매칭,9개월이내,충북 소재 기업 중 콩을 활용한 새로운 형태의 식품에 대한 니즈가 있음\r\n- 콩...,"콩,대두,식품,,",5,NaN,신제품 개발,협의,NaN,NaN,NaN,NaN,NaN,충북

### 컬럼명 변경

In [17]:
COLUMN_RENAME = {
    'buyKindNm': '희망구매유형',
    'dmdtchNm': '수요기술명',
    'dmdtchNo': '수요기술번호',
    'dmdtchPrgstCd': '진행상태',
    'hopepcEraCd': '구매희망시기',
    'hopetchSumnsfeCn': '희망기술개요',
    'keyword': '키워드',
    'rownum': '순번',
    'tchdlSpinsttNm': '기술도입지원기관',
    'tchlgyIndcprDtl': '기술지표상세',
    'tchlgyPccndCn': '기술구매조건',
    'tcntrnCntrctDc': '기술이전계약설명',
    'tcntrnCntrctTy': '기술이전계약유형',
    'tcntrnFxamtTchfee': '정액기술료',
    'tcntrnOdtfcndDc': '기타계약조건',
    'tcntrnOrdnrTchfee': '경상기술료',
    'tpDmandCdNm': '기술센터지역'
}
df = df_raw.rename(columns=COLUMN_RENAME)

print(f'변경 후 컬럼 목록: {df.columns.to_list()}')

변경 후 컬럼 목록: ['희망구매유형', '수요기술명', '수요기술번호', '진행상태', '구매희망시기', '희망기술개요', '키워드', '순번', '기술도입지원기관', '기술지표상세', '기술구매조건', '기술이전계약설명', '기술이전계약유형', '정액기술료', '기타계약조건', '경상기술료', '기술센터지역']

### 파생 컬럼 추가

In [18]:
# 수집 일시 추가
df['수집일시'] = str(date.today())

In [19]:
df.head()

,희망구매유형,수요기술명,수요기술번호,진행상태,구매희망시기,희망기술개요,키워드,순번,기술도입지원기관,기술지표상세,기술구매조건,기술이전계약설명,기술이전계약유형,정액기술료,기타계약조건,경상기술료,기술센터지역,수집일시
0,"기술매매,기술협력",콩 발효기술,00000000001,수요기업만족도체크,3개월이내,새로운 방식의 콩 식품 개발용 발효 종균,"콩,발효,,,",1,NaN,사업화,협의,NaN,NaN,NaN,NaN,NaN,서울,2026-07-03
1,"라이센스,기술협력,기술지도","비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부 미백기술",00000000002,컨설팅완료,3개월이내,"1. 수요기술 개요\r\n비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부...","비목나무,추출물,분획물,화합물,피부미백",2,NaN,신제품 개발,화장품 소재 개발에 투입될 수 있는 기술 필요.\r\n관련 기술 개량 발명에 대한 ...,NaN,NaN,NaN,NaN,NaN,제주,2026-07-03
2,"라이센스,기술협력,기술지도",경단구슬모자반 추출물을 활용한 알러지성 질환 개선기술,00000000003,컨설팅완료,3개월이내,1. 수요기술의 개요\r\n경단구슬모자반(Sargassum muticum) 추출물 ...,"경단구슬모자반,추출물,알러지성,질환,",3,NaN,신제품 개발,제품에 바로 적용할 수 있는 상용화기술 필요,NaN,NaN,NaN,NaN,NaN,제주,2026-07-03
3,"라이센스,기술협력","홈쇼핑, 대형마트 등에서 유통이 가능한 생활용품",00000000004,컨설팅완료,3개월이내,"생활용품 중심의 아이디어 제품이 가능한 특허기술을 도입하고, 제품 디자인, 시제품 ...","디자인,제품화,유통,,",4,NaN,신규 아이디어 제품 양산 및 유통 협력,"기술협력을 통하여 제품 출시 및 유통에 따른 매출 발생시, 이익 공유",NaN,NaN,NaN,NaN,NaN,경기,2026-07-03
4,"기술매매,기술협력,기술지도",콩을 활용한 응용식품,00000000005,컨설팅매칭,9개월이내,충북 소재 기업 중 콩을 활용한 새로운 형태의 식품에 대한 니즈가 있음\r\n- 콩...,"콩,대두,식품,,",5,NaN,신제품 개발,협의,NaN,NaN,NaN,NaN,NaN,충북,2026-07-03

In [20]:
# 불필요한 순번 삭제
df = df.drop('순번', axis=1)
df.head()

,희망구매유형,수요기술명,수요기술번호,진행상태,구매희망시기,희망기술개요,키워드,기술도입지원기관,기술지표상세,기술구매조건,기술이전계약설명,기술이전계약유형,정액기술료,기타계약조건,경상기술료,기술센터지역,수집일시
0,"기술매매,기술협력",콩 발효기술,00000000001,수요기업만족도체크,3개월이내,새로운 방식의 콩 식품 개발용 발효 종균,"콩,발효,,,",NaN,사업화,협의,NaN,NaN,NaN,NaN,NaN,서울,2026-07-03
1,"라이센스,기술협력,기술지도","비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부 미백기술",00000000002,컨설팅완료,3개월이내,"1. 수요기술 개요\r\n비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부...","비목나무,추출물,분획물,화합물,피부미백",NaN,신제품 개발,화장품 소재 개발에 투입될 수 있는 기술 필요.\r\n관련 기술 개량 발명에 대한 ...,NaN,NaN,NaN,NaN,NaN,제주,2026-07-03
2,"라이센스,기술협력,기술지도",경단구슬모자반 추출물을 활용한 알러지성 질환 개선기술,00000000003,컨설팅완료,3개월이내,1. 수요기술의 개요\r\n경단구슬모자반(Sargassum muticum) 추출물 ...,"경단구슬모자반,추출물,알러지성,질환,",NaN,신제품 개발,제품에 바로 적용할 수 있는 상용화기술 필요,NaN,NaN,NaN,NaN,NaN,제주,2026-07-03
3,"라이센스,기술협력","홈쇼핑, 대형마트 등에서 유통이 가능한 생활용품",00000000004,컨설팅완료,3개월이내,"생활용품 중심의 아이디어 제품이 가능한 특허기술을 도입하고, 제품 디자인, 시제품 ...","디자인,제품화,유통,,",NaN,신규 아이디어 제품 양산 및 유통 협력,"기술협력을 통하여 제품 출시 및 유통에 따른 매출 발생시, 이익 공유",NaN,NaN,NaN,NaN,NaN,경기,2026-07-03
4,"기술매매,기술협력,기술지도",콩을 활용한 응용식품,00000000005,컨설팅매칭,9개월이내,충북 소재 기업 중 콩을 활용한 새로운 형태의 식품에 대한 니즈가 있음\r\n- 콩...,"콩,대두,식품,,",NaN,신제품 개발,협의,NaN,NaN,NaN,NaN,NaN,충북,2026-07-03

In [21]:
# 정보충실도 추가
cols = [
    "희망기술개요",
    "키워드",
    "기술구매조건",
    "기술이전계약유형"
]

df["정보충실도"] = df[cols].notna().sum(axis=1)
df.head()

,희망구매유형,수요기술명,수요기술번호,진행상태,구매희망시기,희망기술개요,키워드,기술도입지원기관,기술지표상세,기술구매조건,기술이전계약설명,기술이전계약유형,정액기술료,기타계약조건,경상기술료,기술센터지역,수집일시,정보충실도
0,"기술매매,기술협력",콩 발효기술,00000000001,수요기업만족도체크,3개월이내,새로운 방식의 콩 식품 개발용 발효 종균,"콩,발효,,,",NaN,사업화,협의,NaN,NaN,NaN,NaN,NaN,서울,2026-07-03,3
1,"라이센스,기술협력,기술지도","비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부 미백기술",00000000002,컨설팅완료,3개월이내,"1. 수요기술 개요\r\n비목나무 유래 추출물, 분획물 또는 화합물을 함유하는 피부...","비목나무,추출물,분획물,화합물,피부미백",NaN,신제품 개발,화장품 소재 개발에 투입될 수 있는 기술 필요.\r\n관련 기술 개량 발명에 대한 ...,NaN,NaN,NaN,NaN,NaN,제주,2026-07-03,3
2,"라이센스,기술협력,기술지도",경단구슬모자반 추출물을 활용한 알러지성 질환 개선기술,00000000003,컨설팅완료,3개월이내,1. 수요기술의 개요\r\n경단구슬모자반(Sargassum muticum) 추출물 ...,"경단구슬모자반,추출물,알러지성,질환,",NaN,신제품 개발,제품에 바로 적용할 수 있는 상용화기술 필요,NaN,NaN,NaN,NaN,NaN,제주,2026-07-03,3
3,"라이센스,기술협력","홈쇼핑, 대형마트 등에서 유통이 가능한 생활용품",00000000004,컨설팅완료,3개월이내,"생활용품 중심의 아이디어 제품이 가능한 특허기술을 도입하고, 제품 디자인, 시제품 ...","디자인,제품화,유통,,",NaN,신규 아이디어 제품 양산 및 유통 협력,"기술협력을 통하여 제품 출시 및 유통에 따른 매출 발생시, 이익 공유",NaN,NaN,NaN,NaN,NaN,경기,2026-07-03,3
4,"기술매매,기술협력,기술지도",콩을 활용한 응용식품,00000000005,컨설팅매칭,9개월이내,충북 소재 기업 중 콩을 활용한 새로운 형태의 식품에 대한 니즈가 있음\r\n- 콩...,"콩,대두,식품,,",NaN,신제품 개발,협의,NaN,NaN,NaN,NaN,NaN,충북,2026-07-03,3

In [22]:
df.sample(10)

,희망구매유형,수요기술명,수요기술번호,진행상태,구매희망시기,희망기술개요,키워드,기술도입지원기관,기술지표상세,기술구매조건,기술이전계약설명,기술이전계약유형,정액기술료,기타계약조건,경상기술료,기술센터지역,수집일시,정보충실도
2013,"기술매매,라이센스",소형비행기 비행 안정화 알고리즘 기술,00000002027,컨설팅완료,즉시,소형비행체 기반의 다중센서를 이용한 구조물 안정성 검사를 위함\r\n장애물에 대한 ...,"비행안정화,소형비행기,드론,,",NaN,신제품개발,협의후 결정\r\n*전남TP 기술이전센터 컨설팅,NaN,NaN,NaN,NaN,NaN,전남,2026-07-03,3
7520,"기술매매,라이센스,기술협력",기능성 에센스 및 마스크팩에 노화방지 효과를 개선할 수 있는 항산화 신소재,00000007534,컨설팅완료,6개월이내,기능성 에센스 및 마스크팩에 노화방지 효과를 개선할 수 있는 항산화 신소재,"화장품,노화방지,항산화,신소재,마스크팩",NaN,신제품개발,협의,NaN,NaN,NaN,NaN,NaN,인천,2026-07-03,3
9133,NaN,수질정화기술 및 감시기술,00000009147,컨설팅매칭,3개월이내,수질정화기술 및 감시기술,"수질,정화,감시 ,,",NaN,신제품개발,없음,NaN,NaN,NaN,NaN,NaN,전북,2026-07-03,3
7426,"기술매매,라이센스,기술협력,기술지도",Research and development for enhancing water r...,00000007440,컨설팅매칭,12개월이내,As wire harness of lighting system for auto in...,"wire,harness,water,resistance,",NaN,신제품 개발,중국기업\r\n충북테크노파크 기술거래촉진네트워크 발굴 기업임,NaN,NaN,NaN,NaN,NaN,충북,2026-07-03,3
2861,"기술매매,라이센스,기술협력,기술지도",나노 복합분말 제조 방법,00000002875,기술이전계약,3개월이내,1. 플라즈마 토치부를 작동시켜 열플라즈마를 발생시키는 단계에서 \r\n\r\n ...,"나노 ,복합분말,플라즈마,디스플레이 패널,",호서대학교 산학협력단,신제품 개발,협의에 의함,NaN,노하우이전,2000000,본 건은 특허양도로 기술이전 계약 체결이 완료됨.,0,충남,2026-07-03,4
11042,"기술매매,라이센스",180? 소형 돔 구축,00000011056,신청,12개월이내,프로젝트 두대를 활용한 엣지 브랜딩 기술\r\n108? 콘텐츠 개발\r\n키보드 스...,"소형 돔,키보드 스크린,,,",NaN,신제품개발,경기테크노파크 중재 알선에 따름,NaN,NaN,NaN,NaN,NaN,경기,2026-07-03,3
7747,기술매매,웹기반 데이터마이닝 (Web-based data mining),00000007761,컨설팅매칭,9개월이내,- 필요기술내용\r\n1. 데이터마이닝기법(상품명: Prospector(data m...,"데이터마이닝,웹서비스,,,",NaN,기술이전,기술이전,NaN,NaN,NaN,NaN,NaN,경기,2026-07-03,3
7008,"기술매매,기술협력",스마트 기저귀,00000007022,기술이전계약,12개월이내,"착용자의 대변 또는 소변을 검출하고, 착용자의 위치를 제공할 수 있는 스마트 기저귀...","스마트,기저귀,웨어러블,,",한국생산기술연구원,신제품 개발,협상 후 결정,NaN,통상실시권,30000000,NaN,0,경기,2026-07-03,4
1654,라이센스,압전소자 제조 및 응용기술,00000001668,컨설팅완료,12개월이내,전기에너지로부터 기계적 변형을 나타내는 압전 세라믹 소재의 에너지 변환특성(압전효과...,"에너지,압전소자,,,",NaN,기술보완,향후협의,NaN,NaN,NaN,NaN,NaN,광주,2026-07-03,3
7310,"기술매매,라이센스,기술협력,기술지도",친환경 물질을 이용한 비료 및 사료 개발,00000007324,컨설팅매칭,3개월이내,친환경 물질을 이용한 비료 및 사료 개발,"비료,사료,,,",NaN,신제품개발,협의,NaN,NaN,NaN,NaN,NaN,인천,2026-07-03,3

In [23]:
df.dtypes

희망구매유형        str
수요기술명         str
수요기술번호        str
진행상태          str
구매희망시기        str
희망기술개요        str
키워드           str
기술도입지원기관      str
기술지표상세        str
기술구매조건        str
기술이전계약설명      str
기술이전계약유형      str
정액기술료         str
기타계약조건        str
경상기술료         str
기술센터지역        str
수집일시          str
정보충실도       int64
dtype: object

In [24]:
df['기술센터지역'].value_counts()

기술센터지역
대구      1325
충남      1057
충북       998
광주       996
울산       941
전북       878
경기       841
부산       762
경북       741
경남       493
포항       412
서울       386
전남       338
대전       299
인천       256
강원       254
경기대진     198
제주        56
Name: count, dtype: int64

### PostSQL 설정

In [28]:
DB_URL = 'postgresql://postgres:1234@Localhost:5432/NTBdb'
TABLE_NAME = 'ntb_data'

print(f'csv 저장 경로 : {OUTPUT_PATH}')

csv 저장 경로 : c:\Users\Administrator\bigdata2026\fastapi\기술은행 수요기술 조회 서비스\output\NTB_db.csv

In [29]:
def save_to_postgresql(df, db_url, table_name):
    """
    DB 테이블로 저장
    """
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print(version[:80]+'...')

    # DATAFRAME을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize= 1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
        print(saved_count)

In [30]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
11231

### CSV 저장

In [31]:
df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('저장 완료')

저장 완료

### 최종 결과

In [32]:
print('='*80)
print('한국산업기술진흥원_기술은행 수요기술 조회 서비스_GW')
print('='*80)
print(f'수집 방식 : 공공데이터포털')
print(f'수집 건수 : {len(df):,}')
print(f'컬럼 수 : {len(df.columns)} 개')
print(f'수집 일시 : {df["수집일시"].iloc[0]}')
print(f'CSV 저장 위치 : {OUTPUT_PATH}')
print(f'DB 저장 위치 : NTBdb.{TABLE_NAME}')

if '기술센터지역' in df.columns:
    print('-'*60)
    print('기술센터지역 상위 5개')
    print(df['기술센터지역'].value_counts().head())

print('='*80)

================================================================================
한국산업기술진흥원_기술은행 수요기술 조회 서비스_GW
================================================================================
수집 방식 : 공공데이터포털
수집 건수 : 11,231
컬럼 수 : 18 개
수집 일시 : 2026-07-03
CSV 저장 위치 : c:\Users\Administrator\bigdata2026\fastapi\기술은행 수요기술 조회 서비스\output\NTB_db.csv
DB 저장 위치 : NTBdb.ntb_data
------------------------------------------------------------
기술센터지역 상위 5개
기술센터지역
대구    1325
충남    1057
충북     998
광주     996
울산     941
Name: count, dtype: int64
================================================================================