# 서울 종로구 아파트 매매 실거래가 API

In [1]:
import os
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env 파일에 API 키를 설정하세요')

API 키 로드 완료: 0f4cc2...0ab9

## API 확인

In [3]:
BASE_URL = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev'

In [4]:
response = requests.get(BASE_URL,
                        params={
                            'serviceKey':API_KEY,
                            'pageNo':1,
                            'numOfRows':100,
                            'LAWD_CD':11110,
                            'DEAL_YMD':202606,
                            '_type':'json'
                        })
response.raise_for_status()

In [5]:
response.json()

{'response': {'header': {'resultCode': '000', 'resultMsg': 'OK'},
  'body': {'items': {'item': [{'aptDong': ' ',
      'aptNm': '경희궁자이(4단지)',
      'aptSeq': '11110-2464',
      'bonbun': '0126',
      'bubun': '0000',
      'buildYear': 2017,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '100,000',
      'dealDay': 28,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 37.2635,
      'floor': 7,
      'jibun': 126,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '송월길',
      'roadNmBonbun': '00155',
      'roadNmBubun': '00000',
      'roadNmCd': 4100192,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': ' ',
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 18000,
      'umdNm': '교북동'},
     {'aptDong': ' ',
      'aptNm': '동대문맨션',
      'aptSeq': '11110-31',
      'bonbun': '0578',
      'bubun': '0005',
      'buildYear': 1973,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '51,500',
      'dealDay': 23,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 83.83,
      'floor': 6,
      'jibun': '578-5',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '창신길',
      'roadNmBonbun': '00020',
      'roadNmBubun': '00000',
      'roadNmCd': 4100453,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17400,
      'umdNm': '창신동'},
     {'aptDong': ' ',
      'aptNm': '두산',
      'aptSeq': '11110-34',
      'bonbun': '0232',
      'bubun': '0000',
      'buildYear': 1999,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '91,800',
      'dealDay': 22,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 59.95,
      'floor': 7,
      'jibun': 232,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '지봉로5길',
      'roadNmBonbun': '00007',
      'roadNmBubun': '00000',
      'roadNmCd': 4100390,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17400,
      'umdNm': '창신동'},
     {'aptDong': ' ',
      'aptNm': '흥인',
      'aptSeq': '11110-40',
      'bonbun': '0627',
      'bubun': '0021',
      'buildYear': 1997,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '57,700',
      'dealDay': 27,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 56.88,
      'floor': 2,
      'jibun': '627-21',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '창신길',
      'roadNmBonbun': '00131',
      'roadNmBubun': '00004',
      'roadNmCd': 4100453,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17400,
      'umdNm': '창신동'},
     {'aptDong': ' ',
      'aptNm': '롯데캐슬로잔',
      'aptSeq': '11110-2246',
      'bonbun': '0108',
      'bubun': '0000',
      'buildYear': 2009,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '201,000',
      'dealDay': 27,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 200.331,
      'floor': 1,
      'jibun': 108,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '평창문화로',
      'roadNmBonbun': '00156',
      'roadNmBubun': '00000',
      'roadNmCd': 3100023,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 18300,
      'umdNm': '평창동'},
     {'aptDong': ' ',
      'aptNm': '경희궁자이(2단지)',
      'aptSeq': '11110-2445',
      'bonbun': '0199',
      'bubun': '0000',
      'buildYear': 2017,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '230,000',
      'dealDay': 27,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 59.8547,
      'floor': 20,
      'jibun': 199,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '송월길',
      'roadNmBonbun': '00099',
      'roadNmBubun': '00000',
      'roadNmCd': 4100192,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': ' ',
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17900,
      'umdNm': '홍파동'},
     {'aptDong': ' ',
      'aptNm': '광화문스페이스본(101동~105동)',
      'aptSeq': '11110-2203',
      'bonbun': '0009',
      'bubun': '0000',
      'buildYear': 2008,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '210,000',
      'dealDay': 26,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 126.34,
      'floor': 1,
      'jibun': 9,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '사직로8길',
      'roadNmBonbun': '00004',
      'roadNmBubun': '00000',
      'roadNmCd': 4100135,
      'roadNmSeq': '03',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 11500,
      'umdNm': '사직동'},
     {'aptDong': ' ',
      'aptNm': '벽산블루밍평창힐스',
      'aptSeq': '11110-146',
      'bonbun': '0045',
      'bubun': '0000',
      'buildYear': 2004,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '160,000',
      'dealDay': 17,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 150.94,
      'floor': 5,
      'jibun': 45,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '평창문화로',
      'roadNmBonbun': '00118',
      'roadNmBubun': '00000',
      'roadNmCd': 3100023,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 18300,
      'umdNm': '평창동'},
     {'aptDong': ' ',
      'aptNm': '현대',
      'aptSeq': '11110-90',
      'bonbun': '0082',
      'bubun': '0000',
      'buildYear': 2000,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '159,917',
      'dealDay': 22,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 성동구',
      'excluUseAr': 114.9,
      'floor': 4,
      'jibun': 82,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '통일로',
      'roadNmBonbun': '00246',
      'roadNmBubun': '00020',
      'roadNmCd': 3000008,
      'roadNmSeq': '06',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 18700,
      'umdNm': '무악동'},
     {'aptDong': ' ',
      'aptNm': '종로중흥S클래스',
      'aptSeq': '11110-2339',
      'bonbun': '0202',
      'bubun': '0003',
      'buildYear': 2013,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '11,500',
      'dealDay': 15,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 19.466,
      'floor': 6,
      'jibun': '202-3',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': '26.06.30',
      'roadNm': '종로66길',
      'roadNmBonbun': '00028',
      'roadNmBubun': '00000',
      'roadNmCd': 4100372,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17500,
      'umdNm': '숭인동'},
     {'aptDong': ' ',
      'aptNm': '디팰리스',
      'aptSeq': '11110-2539',
      'bonbun': '0171',
      'bubun': '0000',
      'buildYear': 2020,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '500,000',
      'dealDay': 24,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 147.551,
      'floor': 9,
      'jibun': 171,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '새문안로2길',
      'roadNmBonbun': '00010',
      'roadNmBubun': '00000',
      'roadNmCd': 4100157,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 12100,
      'umdNm': '신문로2가'},
     {'aptDong': ' ',
      'aptNm': '경희궁자이(2단지)',
      'aptSeq': '11110-2445',
      'bonbun': '0199',
      'bubun': '0000',
      'buildYear': 2017,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '277,000',
      'dealDay': 16,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구, 서울 종로구',
      'excluUseAr': 84.9443,
      'floor': 7,
      'jibun': 199,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '송월길',
      'roadNmBonbun': '00099',
      'roadNmBubun': '00000',
      'roadNmCd': 4100192,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': ' ',
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17900,
      'umdNm': '홍파동'},
     {'aptDong': ' ',
      'aptNm': '명륜동주상복합아남아파트',
      'aptSeq': '11110-26',
      'bonbun': '0237',
      'bubun': '0000',
      'buildYear': 1999,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '89,500',
      'dealDay': 17,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 도봉구, 서울 마포구',
      'excluUseAr': 59.36,
      'floor': 3,
      'jibun': 237,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '혜화로3길',
      'roadNmBonbun': '00005',
      'roadNmBubun': '00000',
      'roadNmCd': 4100545,
      'roadNmSeq': '02',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17100,
      'umdNm': '명륜2가'},
     {'aptDong': ' ',
      'aptNm': '블루빌',
      'aptSeq': '11110-2450',
      'bonbun': '0243',
      'bubun': '0000',
      'buildYear': 2017,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '30,000',
      'dealDay': 22,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '직거래',
      'estateAgentSggNm': ' ',
      'excluUseAr': 42.25,
      'floor': 5,
      'jibun': 243,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': '26.06.23',
      'roadNm': '종로58가길',
      'roadNmBonbun': '00009',
      'roadNmBubun': '00000',
      'roadNmCd': 4100358,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17500,
      'umdNm': '숭인동'},
     {'aptDong': ' ',
      'aptNm': '창신이수',
      'aptSeq': '11110-42',
      'bonbun': '0023',
      'bubun': '0816',
      'buildYear': 2003,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '89,000',
      'dealDay': 18,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 84.5,
      'floor': 2,
      'jibun': '23-816',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '지봉로',
      'roadNmBonbun': '00087',
      'roadNmBubun': '00000',
      'roadNmCd': 3005007,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17400,
      'umdNm': '창신동'},
     {'aptDong': ' ',
      'aptNm': '두산',
      'aptSeq': '11110-34',
      'bonbun': '0232',
      'bubun': '0000',
      'buildYear': 1999,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '62,000',
      'dealDay': 8,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '직거래',
      'estateAgentSggNm': ' ',
      'excluUseAr': 59.95,
      'floor': 11,
      'jibun': 232,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '지봉로5길',
      'roadNmBonbun': '00007',
      'roadNmBubun': '00000',
      'roadNmCd': 4100390,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17400,
      'umdNm': '창신동'},
     {'aptDong': ' ',
      'aptNm': '명륜동주상복합아남아파트',
      'aptSeq': '11110-26',
      'bonbun': '0237',
      'bubun': '0000',
      'buildYear': 1999,
      'buyerGbn': '개인',
      'cdealDay': '26.06.23',
      'cdealType': 'O',
      'dealAmount': '89,500',
      'dealDay': 17,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 도봉구, 서울 마포구',
      'excluUseAr': 59.36,
      'floor': 3,
      'jibun': 237,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '혜화로3길',
      'roadNmBonbun': '00005',
      'roadNmBubun': '00000',
      'roadNmCd': 4100545,
      'roadNmSeq': '02',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17100,
      'umdNm': '명륜2가'},
     {'aptDong': ' ',
      'aptNm': '경희궁자이(2단지)',
      'aptSeq': '11110-2445',
      'bonbun': '0199',
      'bubun': '0000',
      'buildYear': 2017,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '273,000',
      'dealDay': 7,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구, 서울 종로구',
      'excluUseAr': 84.8359,
      'floor': 6,
      'jibun': 199,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '송월길',
      'roadNmBonbun': '00099',
      'roadNmBubun': '00000',
      'roadNmCd': 4100192,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': ' ',
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17900,
      'umdNm': '홍파동'},
     {'aptDong': ' ',
      'aptNm': '롯데캐슬천지인',
      'aptSeq': '11110-152',
      'bonbun': '0076',
      'bubun': '0000',
      'buildYear': 2004,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '124,000',
      'dealDay': 11,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 112.54,
      'floor': 13,
      'jibun': 76,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '종로',
      'roadNmBonbun': '00347',
      'roadNmBubun': '00000',
      'roadNmCd': 3100013,
      'roadNmSeq': 14,
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17500,
      'umdNm': '숭인동'},
     {'aptDong': ' ',
      'aptNm': '인왕산2차아이파크',
      'aptSeq': '11110-2417',
      'bonbun': '0088',
      'bubun': '0000',
      'buildYear': 2015,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '147,500',
      'dealDay': 6,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 84.0284,
      'floor': 13,
      'jibun': 88,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '통일로18길',
      'roadNmBonbun': '00034',
      'roadNmBubun': '00000',
      'roadNmCd': 4100482,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 18700,
      'umdNm': '무악동'},
     {'aptDong': ' ',
      'aptNm': '경희궁자이(2단지)',
      'aptSeq': '11110-2445',
      'bonbun': '0199',
      'bubun': '0000',
      'buildYear': 2017,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '264,500',
      'dealDay': 5,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 종로구',
      'excluUseAr': 84.8359,
      'floor': 17,
      'jibun': 199,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '송월길',
      'roadNmBonbun': '00099',
      'roadNmBubun': '00000',
      'roadNmCd': 4100192,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': ' ',
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17900,
      'umdNm': '홍파동'},
     {'aptDong': ' ',
      'aptNm': '창신쌍용1',
      'aptSeq': '11110-37',
      'bonbun': '0702',
      'bubun': '0000',
      'buildYear': 1992,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '62,000',
      'dealDay': 4,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '직거래',
      'estateAgentSggNm': ' ',
      'excluUseAr': 79.87,
      'floor': 13,
      'jibun': 702,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '동망산길',
      'roadNmBonbun': '00019',
      'roadNmBubun': '00000',
      'roadNmCd': 4100065,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17400,
      'umdNm': '창신동'},
     {'aptDong': ' ',
      'aptNm': '종로청계힐스테이트',
      'aptSeq': '11110-2234',
      'bonbun': '0766',
      'bubun': '0000',
      'buildYear': 2009,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '104,000',
      'dealDay': 3,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 성북구, 서울 종로구',
      'excluUseAr': 59.9426,
      'floor': 10,
      'jibun': 766,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '숭인동길',
      'roadNmBonbun': '00021',
      'roadNmBubun': '00000',
      'roadNmCd': 4100204,
      'roadNmSeq': '01',
      'roadNmSggCd': 11110,
      'roadNmbCd': 0,
      'sggCd': 11110,
      'slerGbn': '개인',
      'umdCd': 17500,
      'umdNm': '숭인동'}]},
   'numOfRows': 100,
   'pageNo': 1,
   'totalCount': 23}}}

In [6]:
data = response.json()
data['response']['body']['items']['item']

[{'aptDong': ' ',
  'aptNm': '경희궁자이(4단지)',
  'aptSeq': '11110-2464',
  'bonbun': '0126',
  'bubun': '0000',
  'buildYear': 2017,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '100,000',
  'dealDay': 28,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 37.2635,
  'floor': 7,
  'jibun': 126,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '송월길',
  'roadNmBonbun': '00155',
  'roadNmBubun': '00000',
  'roadNmCd': 4100192,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': ' ',
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 18000,
  'umdNm': '교북동'},
 {'aptDong': ' ',
  'aptNm': '동대문맨션',
  'aptSeq': '11110-31',
  'bonbun': '0578',
  'bubun': '0005',
  'buildYear': 1973,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '51,500',
  'dealDay': 23,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 83.83,
  'floor': 6,
  'jibun': '578-5',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '창신길',
  'roadNmBonbun': '00020',
  'roadNmBubun': '00000',
  'roadNmCd': 4100453,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17400,
  'umdNm': '창신동'},
 {'aptDong': ' ',
  'aptNm': '두산',
  'aptSeq': '11110-34',
  'bonbun': '0232',
  'bubun': '0000',
  'buildYear': 1999,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '91,800',
  'dealDay': 22,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 59.95,
  'floor': 7,
  'jibun': 232,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '지봉로5길',
  'roadNmBonbun': '00007',
  'roadNmBubun': '00000',
  'roadNmCd': 4100390,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17400,
  'umdNm': '창신동'},
 {'aptDong': ' ',
  'aptNm': '흥인',
  'aptSeq': '11110-40',
  'bonbun': '0627',
  'bubun': '0021',
  'buildYear': 1997,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '57,700',
  'dealDay': 27,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 56.88,
  'floor': 2,
  'jibun': '627-21',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '창신길',
  'roadNmBonbun': '00131',
  'roadNmBubun': '00004',
  'roadNmCd': 4100453,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17400,
  'umdNm': '창신동'},
 {'aptDong': ' ',
  'aptNm': '롯데캐슬로잔',
  'aptSeq': '11110-2246',
  'bonbun': '0108',
  'bubun': '0000',
  'buildYear': 2009,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '201,000',
  'dealDay': 27,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 200.331,
  'floor': 1,
  'jibun': 108,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '평창문화로',
  'roadNmBonbun': '00156',
  'roadNmBubun': '00000',
  'roadNmCd': 3100023,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 18300,
  'umdNm': '평창동'},
 {'aptDong': ' ',
  'aptNm': '경희궁자이(2단지)',
  'aptSeq': '11110-2445',
  'bonbun': '0199',
  'bubun': '0000',
  'buildYear': 2017,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '230,000',
  'dealDay': 27,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 59.8547,
  'floor': 20,
  'jibun': 199,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '송월길',
  'roadNmBonbun': '00099',
  'roadNmBubun': '00000',
  'roadNmCd': 4100192,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': ' ',
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17900,
  'umdNm': '홍파동'},
 {'aptDong': ' ',
  'aptNm': '광화문스페이스본(101동~105동)',
  'aptSeq': '11110-2203',
  'bonbun': '0009',
  'bubun': '0000',
  'buildYear': 2008,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '210,000',
  'dealDay': 26,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 126.34,
  'floor': 1,
  'jibun': 9,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '사직로8길',
  'roadNmBonbun': '00004',
  'roadNmBubun': '00000',
  'roadNmCd': 4100135,
  'roadNmSeq': '03',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 11500,
  'umdNm': '사직동'},
 {'aptDong': ' ',
  'aptNm': '벽산블루밍평창힐스',
  'aptSeq': '11110-146',
  'bonbun': '0045',
  'bubun': '0000',
  'buildYear': 2004,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '160,000',
  'dealDay': 17,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 150.94,
  'floor': 5,
  'jibun': 45,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '평창문화로',
  'roadNmBonbun': '00118',
  'roadNmBubun': '00000',
  'roadNmCd': 3100023,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 18300,
  'umdNm': '평창동'},
 {'aptDong': ' ',
  'aptNm': '현대',
  'aptSeq': '11110-90',
  'bonbun': '0082',
  'bubun': '0000',
  'buildYear': 2000,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '159,917',
  'dealDay': 22,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 성동구',
  'excluUseAr': 114.9,
  'floor': 4,
  'jibun': 82,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '통일로',
  'roadNmBonbun': '00246',
  'roadNmBubun': '00020',
  'roadNmCd': 3000008,
  'roadNmSeq': '06',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 18700,
  'umdNm': '무악동'},
 {'aptDong': ' ',
  'aptNm': '종로중흥S클래스',
  'aptSeq': '11110-2339',
  'bonbun': '0202',
  'bubun': '0003',
  'buildYear': 2013,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '11,500',
  'dealDay': 15,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 19.466,
  'floor': 6,
  'jibun': '202-3',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': '26.06.30',
  'roadNm': '종로66길',
  'roadNmBonbun': '00028',
  'roadNmBubun': '00000',
  'roadNmCd': 4100372,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17500,
  'umdNm': '숭인동'},
 {'aptDong': ' ',
  'aptNm': '디팰리스',
  'aptSeq': '11110-2539',
  'bonbun': '0171',
  'bubun': '0000',
  'buildYear': 2020,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '500,000',
  'dealDay': 24,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 147.551,
  'floor': 9,
  'jibun': 171,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '새문안로2길',
  'roadNmBonbun': '00010',
  'roadNmBubun': '00000',
  'roadNmCd': 4100157,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 12100,
  'umdNm': '신문로2가'},
 {'aptDong': ' ',
  'aptNm': '경희궁자이(2단지)',
  'aptSeq': '11110-2445',
  'bonbun': '0199',
  'bubun': '0000',
  'buildYear': 2017,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '277,000',
  'dealDay': 16,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구, 서울 종로구',
  'excluUseAr': 84.9443,
  'floor': 7,
  'jibun': 199,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '송월길',
  'roadNmBonbun': '00099',
  'roadNmBubun': '00000',
  'roadNmCd': 4100192,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': ' ',
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17900,
  'umdNm': '홍파동'},
 {'aptDong': ' ',
  'aptNm': '명륜동주상복합아남아파트',
  'aptSeq': '11110-26',
  'bonbun': '0237',
  'bubun': '0000',
  'buildYear': 1999,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '89,500',
  'dealDay': 17,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 도봉구, 서울 마포구',
  'excluUseAr': 59.36,
  'floor': 3,
  'jibun': 237,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '혜화로3길',
  'roadNmBonbun': '00005',
  'roadNmBubun': '00000',
  'roadNmCd': 4100545,
  'roadNmSeq': '02',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17100,
  'umdNm': '명륜2가'},
 {'aptDong': ' ',
  'aptNm': '블루빌',
  'aptSeq': '11110-2450',
  'bonbun': '0243',
  'bubun': '0000',
  'buildYear': 2017,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '30,000',
  'dealDay': 22,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '직거래',
  'estateAgentSggNm': ' ',
  'excluUseAr': 42.25,
  'floor': 5,
  'jibun': 243,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': '26.06.23',
  'roadNm': '종로58가길',
  'roadNmBonbun': '00009',
  'roadNmBubun': '00000',
  'roadNmCd': 4100358,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17500,
  'umdNm': '숭인동'},
 {'aptDong': ' ',
  'aptNm': '창신이수',
  'aptSeq': '11110-42',
  'bonbun': '0023',
  'bubun': '0816',
  'buildYear': 2003,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '89,000',
  'dealDay': 18,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 84.5,
  'floor': 2,
  'jibun': '23-816',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '지봉로',
  'roadNmBonbun': '00087',
  'roadNmBubun': '00000',
  'roadNmCd': 3005007,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17400,
  'umdNm': '창신동'},
 {'aptDong': ' ',
  'aptNm': '두산',
  'aptSeq': '11110-34',
  'bonbun': '0232',
  'bubun': '0000',
  'buildYear': 1999,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '62,000',
  'dealDay': 8,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '직거래',
  'estateAgentSggNm': ' ',
  'excluUseAr': 59.95,
  'floor': 11,
  'jibun': 232,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '지봉로5길',
  'roadNmBonbun': '00007',
  'roadNmBubun': '00000',
  'roadNmCd': 4100390,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17400,
  'umdNm': '창신동'},
 {'aptDong': ' ',
  'aptNm': '명륜동주상복합아남아파트',
  'aptSeq': '11110-26',
  'bonbun': '0237',
  'bubun': '0000',
  'buildYear': 1999,
  'buyerGbn': '개인',
  'cdealDay': '26.06.23',
  'cdealType': 'O',
  'dealAmount': '89,500',
  'dealDay': 17,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 도봉구, 서울 마포구',
  'excluUseAr': 59.36,
  'floor': 3,
  'jibun': 237,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '혜화로3길',
  'roadNmBonbun': '00005',
  'roadNmBubun': '00000',
  'roadNmCd': 4100545,
  'roadNmSeq': '02',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17100,
  'umdNm': '명륜2가'},
 {'aptDong': ' ',
  'aptNm': '경희궁자이(2단지)',
  'aptSeq': '11110-2445',
  'bonbun': '0199',
  'bubun': '0000',
  'buildYear': 2017,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '273,000',
  'dealDay': 7,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구, 서울 종로구',
  'excluUseAr': 84.8359,
  'floor': 6,
  'jibun': 199,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '송월길',
  'roadNmBonbun': '00099',
  'roadNmBubun': '00000',
  'roadNmCd': 4100192,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': ' ',
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17900,
  'umdNm': '홍파동'},
 {'aptDong': ' ',
  'aptNm': '롯데캐슬천지인',
  'aptSeq': '11110-152',
  'bonbun': '0076',
  'bubun': '0000',
  'buildYear': 2004,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '124,000',
  'dealDay': 11,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 112.54,
  'floor': 13,
  'jibun': 76,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '종로',
  'roadNmBonbun': '00347',
  'roadNmBubun': '00000',
  'roadNmCd': 3100013,
  'roadNmSeq': 14,
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17500,
  'umdNm': '숭인동'},
 {'aptDong': ' ',
  'aptNm': '인왕산2차아이파크',
  'aptSeq': '11110-2417',
  'bonbun': '0088',
  'bubun': '0000',
  'buildYear': 2015,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '147,500',
  'dealDay': 6,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 84.0284,
  'floor': 13,
  'jibun': 88,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '통일로18길',
  'roadNmBonbun': '00034',
  'roadNmBubun': '00000',
  'roadNmCd': 4100482,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 18700,
  'umdNm': '무악동'},
 {'aptDong': ' ',
  'aptNm': '경희궁자이(2단지)',
  'aptSeq': '11110-2445',
  'bonbun': '0199',
  'bubun': '0000',
  'buildYear': 2017,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '264,500',
  'dealDay': 5,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': 84.8359,
  'floor': 17,
  'jibun': 199,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '송월길',
  'roadNmBonbun': '00099',
  'roadNmBubun': '00000',
  'roadNmCd': 4100192,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': ' ',
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17900,
  'umdNm': '홍파동'},
 {'aptDong': ' ',
  'aptNm': '창신쌍용1',
  'aptSeq': '11110-37',
  'bonbun': '0702',
  'bubun': '0000',
  'buildYear': 1992,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '62,000',
  'dealDay': 4,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '직거래',
  'estateAgentSggNm': ' ',
  'excluUseAr': 79.87,
  'floor': 13,
  'jibun': 702,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '동망산길',
  'roadNmBonbun': '00019',
  'roadNmBubun': '00000',
  'roadNmCd': 4100065,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17400,
  'umdNm': '창신동'},
 {'aptDong': ' ',
  'aptNm': '종로청계힐스테이트',
  'aptSeq': '11110-2234',
  'bonbun': '0766',
  'bubun': '0000',
  'buildYear': 2009,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '104,000',
  'dealDay': 3,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 성북구, 서울 종로구',
  'excluUseAr': 59.9426,
  'floor': 10,
  'jibun': 766,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '숭인동길',
  'roadNmBonbun': '00021',
  'roadNmBubun': '00000',
  'roadNmCd': 4100204,
  'roadNmSeq': '01',
  'roadNmSggCd': 11110,
  'roadNmbCd': 0,
  'sggCd': 11110,
  'slerGbn': '개인',
  'umdCd': 17500,
  'umdNm': '숭인동'}]

In [7]:
data_items = data['response']['body']['items']['item']
data_items[0]

{'aptDong': ' ',
 'aptNm': '경희궁자이(4단지)',
 'aptSeq': '11110-2464',
 'bonbun': '0126',
 'bubun': '0000',
 'buildYear': 2017,
 'buyerGbn': '개인',
 'cdealDay': ' ',
 'cdealType': ' ',
 'dealAmount': '100,000',
 'dealDay': 28,
 'dealMonth': 6,
 'dealYear': 2026,
 'dealingGbn': '중개거래',
 'estateAgentSggNm': '서울 종로구',
 'excluUseAr': 37.2635,
 'floor': 7,
 'jibun': 126,
 'landCd': 1,
 'landLeaseholdGbn': 'N',
 'rgstDate': ' ',
 'roadNm': '송월길',
 'roadNmBonbun': '00155',
 'roadNmBubun': '00000',
 'roadNmCd': 4100192,
 'roadNmSeq': '01',
 'roadNmSggCd': 11110,
 'roadNmbCd': ' ',
 'sggCd': 11110,
 'slerGbn': '개인',
 'umdCd': 18000,
 'umdNm': '교북동'}

## 환경설정

In [8]:
BASE_DIR = os.getcwd()
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'apt_deal.csv')

In [9]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/aptapidb'
TABLE_NAME = 'apt_deal'

## 데이터프레임 생성

In [22]:
df_raw = pd.DataFrame(data_items)
df_raw.head()

,aptDong,aptNm,aptSeq,bonbun,bubun,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,...,roadNmBonbun,roadNmBubun,roadNmCd,roadNmSeq,roadNmSggCd,roadNmbCd,sggCd,slerGbn,umdCd,umdNm
0,,경희궁자이(4단지),11110-2464,0126,0000,2017,개인,,,"100,000",...,00155,00000,4100192,01,11110,,11110,개인,18000,교북동
1,,동대문맨션,11110-31,0578,0005,1973,개인,,,"51,500",...,00020,00000,4100453,01,11110,0,11110,개인,17400,창신동
2,,두산,11110-34,0232,0000,1999,개인,,,"91,800",...,00007,00000,4100390,01,11110,0,11110,개인,17400,창신동
3,,흥인,11110-40,0627,0021,1997,개인,,,"57,700",...,00131,00004,4100453,01,11110,0,11110,개인,17400,창신동
4,,롯데캐슬로잔,11110-2246,0108,0000,2009,개인,,,"201,000",...,00156,00000,3100023,01,11110,0,11110,개인,18300,평창동

In [23]:
df = df_raw[['aptNm', 'umdNm', 'buildYear', 'dealYear', 'dealMonth', 'dealDay', 'dealAmount', 'excluUseAr', 'floor']]
df.head()

,aptNm,umdNm,buildYear,dealYear,dealMonth,dealDay,dealAmount,excluUseAr,floor
0,경희궁자이(4단지),교북동,2017,2026,6,28,"100,000",37.2635,7
1,동대문맨션,창신동,1973,2026,6,23,"51,500",83.8300,6
2,두산,창신동,1999,2026,6,22,"91,800",59.9500,7
3,흥인,창신동,1997,2026,6,27,"57,700",56.8800,2
4,롯데캐슬로잔,평창동,2009,2026,6,27,"201,000",200.3310,1

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   aptNm       23 non-null     str
 1   umdNm       23 non-null     str
 2   buildYear   23 non-null     int64
 3   dealYear    23 non-null     int64
 4   dealMonth   23 non-null     int64
 5   dealDay     23 non-null     int64
 6   dealAmount  23 non-null     str
 7   excluUseAr  23 non-null     float64
 8   floor       23 non-null     int64
dtypes: float64(1), int64(5), str(3)
memory usage: 1.7 KB

In [25]:
COLUMN_NAME = {
    'aptNm':'단지명',
    'umdNm':'법정동',
    'buildYear':'건축년도',
    'dealYear':'계약년도',
    'dealMonth':'계약월',
    'dealDay':'계약일',
    'dealAmount':'거래금액',
    'excluUseAr':'전용면적',
    'floor':'층'
}
df = df.rename(columns=COLUMN_NAME)
df.head()

          단지명  법정동  건축년도  계약년도  계약월  계약일     거래금액      전용면적  층
0  경희궁자이(4단지)  교북동  2017  2026    6   28  100,000   37.2635  7
1       동대문맨션  창신동  1973  2026    6   23   51,500   83.8300  6
2          두산  창신동  1999  2026    6   22   91,800   59.9500  7
3          흥인  창신동  1997  2026    6   27   57,700   56.8800  2
4      롯데캐슬로잔  평창동  2009  2026    6   27  201,000  200.3310  1

In [26]:
df['층'].value_counts()

층
7     3
6     3
13    3
2     2
1     2
5     2
3     2
20    1
4     1
9     1
11    1
17    1
10    1
Name: count, dtype: int64

In [27]:
df['계약날짜'] = pd.to_datetime(
    df[['계약년도', '계약월', '계약일']].rename(columns={
        '계약년도':'year',
        '계약월':'month',
        '계약일':'day'
    })
).dt.date
df['건물연령'] = df['계약년도'] - df['건축년도']
df['거래금액'] = df['거래금액'].str.replace(',', '').astype(int)
df['거래금액'] = df['거래금액'] * 10000
df['평당가격'] = (df['거래금액'] / (df['전용면적'] / 3.3058)).round(1)
df.head()

,단지명,법정동,건축년도,계약년도,계약월,계약일,거래금액,전용면적,층,계약날짜,건물연령,평당가격
0,경희궁자이(4단지),교북동,2017,2026,6,28,1000000000,37.2635,7,2026-06-28,9,88714157.3
1,동대문맨션,창신동,1973,2026,6,23,515000000,83.8300,6,2026-06-23,53,20308803.5
2,두산,창신동,1999,2026,6,22,918000000,59.9500,7,2026-06-22,27,50620924.1
3,흥인,창신동,1997,2026,6,27,577000000,56.8800,2,2026-06-27,29,33534574.5
4,롯데캐슬로잔,평창동,2009,2026,6,27,2010000000,200.3310,1,2026-06-27,17,33168396.3

In [28]:
def floor_bin(f):
    if f <= 3:
        return '저층'
    elif f <= 9:
        return '중층'
    else:
        return '고층'
    
df['층구간'] = df['층'].apply(floor_bin)
df.head()

,단지명,법정동,건축년도,계약년도,계약월,계약일,거래금액,전용면적,층,계약날짜,건물연령,평당가격,층구간
0,경희궁자이(4단지),교북동,2017,2026,6,28,1000000000,37.2635,7,2026-06-28,9,88714157.3,중층
1,동대문맨션,창신동,1973,2026,6,23,515000000,83.8300,6,2026-06-23,53,20308803.5,중층
2,두산,창신동,1999,2026,6,22,918000000,59.9500,7,2026-06-22,27,50620924.1,중층
3,흥인,창신동,1997,2026,6,27,577000000,56.8800,2,2026-06-27,29,33534574.5,저층
4,롯데캐슬로잔,평창동,2009,2026,6,27,2010000000,200.3310,1,2026-06-27,17,33168396.3,저층

In [29]:
df.drop(columns=['계약년도', '계약월', '계약일'], inplace=True)
df.head()

,단지명,법정동,건축년도,거래금액,전용면적,층,계약날짜,건물연령,평당가격,층구간
0,경희궁자이(4단지),교북동,2017,1000000000,37.2635,7,2026-06-28,9,88714157.3,중층
1,동대문맨션,창신동,1973,515000000,83.8300,6,2026-06-23,53,20308803.5,중층
2,두산,창신동,1999,918000000,59.9500,7,2026-06-22,27,50620924.1,중층
3,흥인,창신동,1997,577000000,56.8800,2,2026-06-27,29,33534574.5,저층
4,롯데캐슬로잔,평창동,2009,2010000000,200.3310,1,2026-06-27,17,33168396.3,저층

In [30]:
df = df[['단지명', '법정동', '계약날짜', '거래금액', '평당가격', '전용면적', '층', '층구간', '건축년도', '건물연령']]
df.head()

,단지명,법정동,계약날짜,거래금액,평당가격,전용면적,층,층구간,건축년도,건물연령
0,경희궁자이(4단지),교북동,2026-06-28,1000000000,88714157.3,37.2635,7,중층,2017,9
1,동대문맨션,창신동,2026-06-23,515000000,20308803.5,83.8300,6,중층,1973,53
2,두산,창신동,2026-06-22,918000000,50620924.1,59.9500,7,중층,1999,27
3,흥인,창신동,2026-06-27,577000000,33534574.5,56.8800,2,저층,1997,29
4,롯데캐슬로잔,평창동,2026-06-27,2010000000,33168396.3,200.3310,1,저층,2009,17

## DB 저장

In [31]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)
            
    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공')
        print(version[:80] + '...')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
    print(f'저장 완료 : {saved_count}행')
    print(f'DB : aptapidb / table : {table_name}')

In [32]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 : 23행
DB : aptapidb / table : apt_deal

In [33]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('CSV 저장 완료')

CSV 저장 완료