In [2]:
import math
import os 
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [3]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env파일에 API키를 설정하세요.')

API 키 로드 완료: 6ea6e6...da70

In [4]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'

In [5]:
NODE_ID = 'DGB7011006700' # 동대구역

In [ ]:
# 1번
response = requests.get(BASE_URL, params={'serviceKey': API_KEY,
                        'nodeid': NODE_ID,
                        'pageNo': 1,
                        'numOfRows': 10,
                        '_type': 'json',
                        'cityCode': 22
                        })
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB4060003002',
      'routeno': '북구3',
      'routetp': '지선버스',
      'startnodenm': '노곡동'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000708002',
      'routeno': 708,
      'routetp': '간선버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '반야월역(3번출구)',
      'routeid': 'DGB3000805000',
      'routeno': 805,
      'routetp': '간선버스',
      'startnodenm': '달서아트센터앞'},
     {'endnodenm': '유통단지회차지',
      'routeid': 'DGB3000413001',
      'routeno': 413,
      'routetp': '간선버스',
      'startnodenm': '가창초등학교앞'},
     {'endnodenm': '동대구역',
      'routeid': 'DGB3001814000',
      'routeno': 8140,
      'routetp': '일반버스',
      'startnodenm': 'TBC건너'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB4060006000',
      'routeno': '북구6',
      'routetp': '지선버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '동대구역(2번출구)건너',
      'routeid': 'DGB3000650005',
      'routeno': 650,
      'routetp': '간선버스',
      'startnodenm': '다산(종점)'},
     {'endnodenm': '성보교통건너',
      'routeid': 'DGB2000002100',
      'routeno': '순환2-1',
      'routetp': '순환버스',
      'startnodenm': '성보교통앞'},
     {'endnodenm': '진밭골(종점)2',
      'routeid': 'DGB3000814001',
      'routeno': 814,
      'routetp': '간선버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB3000156000',
      'routeno': 156,
      'routetp': '간선버스',
      'startnodenm': '신덕마을입구건너'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 13}}}

In [ ]:
# 2번
route_list = data['response']['body']['items']['item']

if isinstance(route_list, dict):
    route_list = [route_list]
df = pd.DataFrame(route_list)
df.head()

    endnodenm        routeid routeno routetp  startnodenm
0   동호공영차고지건너  DGB4060003002     북구3    지선버스          노곡동
1   동호공영차고지건너  DGB3000708002     708    간선버스  북구 동호동(종점)1
2  반야월역(3번출구)  DGB3000805000     805    간선버스      달서아트센터앞
3     유통단지회차지  DGB3000413001     413    간선버스      가창초등학교앞
4        동대구역  DGB3001814000    8140    일반버스        TBC건너

In [8]:
df.columns

Index(['endnodenm', 'routeid', 'routeno', 'routetp', 'startnodenm'], dtype='str')

In [12]:
# 3번
bus_route = df[['routeno', 'routeid']]
bus_route.columns = ['노선번호','노선ID']
bus_route.head()

   노선번호           노선ID
0   북구3  DGB4060003002
1   708  DGB3000708002
2   805  DGB3000805000
3   413  DGB3000413001
4  8140  DGB3001814000

In [13]:
# 4번
bus_route['정류소ID'] = NODE_ID
bus_route.head()

   노선번호           노선ID          정류소ID
0   북구3  DGB4060003002  DGB7011006700
1   708  DGB3000708002  DGB7011006700
2   805  DGB3000805000  DGB7011006700
3   413  DGB3000413001  DGB7011006700
4  8140  DGB3001814000  DGB7011006700

In [14]:
# 5번
DB_URL = 'postgresql://postgres:1234@localhost:5432/busapidb'
TABLE_NAME = 'route_by_stop'

def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장하는 함수"""
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

In [18]:
save_to_postgresql(bus_route, DB_URL, TABLE_NAME)

In [19]:
# 심화 A
bus_route['정류소명'] = '동대구역'
bus_route.head()

   노선번호           노선ID          정류소ID  정류소명
0   북구3  DGB4060003002  DGB7011006700  동대구역
1   708  DGB3000708002  DGB7011006700  동대구역
2   805  DGB3000805000  DGB7011006700  동대구역
3   413  DGB3000413001  DGB7011006700  동대구역
4  8140  DGB3001814000  DGB7011006700  동대구역

In [20]:
save_to_postgresql(bus_route, DB_URL, TABLE_NAME)