In [2]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# 경로 설정
# ipynb 파일은 getcwd() 함수를 이용해서 파일 위치나 폴더 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

DATA_PATH = os.path.join(BASE_DIR, "input", "parking.csv") # 경로를 합쳤다.
DATA_PATH

OUTPUT_PATH = os.path.join(BASE_DIR, "output", "parking_new.csv")
OUTPUT_PATH

DB_URL = "postgresql://postgres:1234@localhost:5432/parkingdb"

df = pd.read_csv(DATA_PATH, encoding="cp949")

df_new = df[["주차장명", "소재지지번주소", "주차구획수", "요금정보"]]
df_new.head(20)

         주차장명               소재지지번주소  주차구획수 요금정보
0   3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   무료
1      3공단로인근     대구광역시 북구 노원동3가 14    329   무료
2      검단동로인근    대구광역시 북구 검단동 745-2     29   무료
3    경대로17길인근      대구광역시 북구 복현동 573     78   무료
4    경대로23길인근   대구광역시 북구 복현동 606-34      5   무료
5    경대로27길인근    대구광역시 북구 복현동 433-1      8   무료
6     경대로5길인근     대구광역시 북구 대현동 14-1     33   무료
7     경대로7길인근      대구광역시 북구 대현동 526     19   무료
8      경대북문건너   대구광역시 북구 산격동 1499-2     46   유료
9     경진로1길인근      대구광역시 북구 복현동 623     15   무료
10   경진로남1길인근    대구광역시 북구 복현동 436-1     17   무료
11      경진로인근      대구광역시 북구 복현동 623     92   무료
12   고성로34길인근    대구광역시 북구 고성동2가 130      9   무료
13   고성로37길인근      대구광역시 북구 고성동3가 2     57   무료
14  고성북로10길인근    대구광역시 북구 고성동3가 143     15   무료
15    고성북로1인근    대구광역시 북구 고성동3가 143     65   무료
16    고성북로2인근    대구광역시 북구 고성동3가 143     87   무료
17  관은동로32길인근   대구광역시 북구 읍내동 1295-6     27   무료
18  관음동로13길인근     대구광역시 북구 관음동 1346     43   무료
19  관음동로31길인근     대구광역시 북구 관음동 1240      6   무료

In [5]:
def size(x):
    if x < 20:
        return '소형'
    elif x < 50:
        return '중형'
    else:
        return '대형'

df_new['규모구분'] = df['주차구획수'].apply(size)

In [6]:
df_new.head(20)

         주차장명               소재지지번주소  주차구획수 요금정보 규모구분
0   3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   무료   소형
1      3공단로인근     대구광역시 북구 노원동3가 14    329   무료   대형
2      검단동로인근    대구광역시 북구 검단동 745-2     29   무료   중형
3    경대로17길인근      대구광역시 북구 복현동 573     78   무료   대형
4    경대로23길인근   대구광역시 북구 복현동 606-34      5   무료   소형
5    경대로27길인근    대구광역시 북구 복현동 433-1      8   무료   소형
6     경대로5길인근     대구광역시 북구 대현동 14-1     33   무료   중형
7     경대로7길인근      대구광역시 북구 대현동 526     19   무료   소형
8      경대북문건너   대구광역시 북구 산격동 1499-2     46   유료   중형
9     경진로1길인근      대구광역시 북구 복현동 623     15   무료   소형
10   경진로남1길인근    대구광역시 북구 복현동 436-1     17   무료   소형
11      경진로인근      대구광역시 북구 복현동 623     92   무료   대형
12   고성로34길인근    대구광역시 북구 고성동2가 130      9   무료   소형
13   고성로37길인근      대구광역시 북구 고성동3가 2     57   무료   대형
14  고성북로10길인근    대구광역시 북구 고성동3가 143     15   무료   소형
15    고성북로1인근    대구광역시 북구 고성동3가 143     65   무료   대형
16    고성북로2인근    대구광역시 북구 고성동3가 143     87   무료   대형
17  관은동로32길인근   대구광역시 북구 읍내동 1295-6     27   무료   중형
18  관음동로13길인근     대구광역시 북구 관음동 1346     43   무료   중형
19  관음동로31길인근     대구광역시 북구 관음동 1240      6   무료   소형

In [9]:
TABLE_NAME = "parking_lot2"

In [7]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장"""
    df_save = df.copy()

    # pandas 버전 차이에 따라 문자열 컬럼을 str로 정리
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str) # str로 형변환
    
    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text("SELECT version();")).fetchone()[0]
        print("PostgreSQL 연결 성공!")
        print(version[:80] + "...")

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=1000,
        method="multi",
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f"SELECT COUNT(*) FROM {table_name};")).fetchone()[0]

    print(f"{saved_count}행 저장 완료")
    print(f"DB : subwaydb / table : {table_name}")

In [10]:
# 함수 호출
save_to_postgresql(df_new, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
229행 저장 완료
DB : subwaydb / table : parking_lot2