In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# 경로설정
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking_pipeline'

In [2]:
DATA_PATH = os.path.join(BASE_DIR, 'input', '대구광역시 북구_공영주차장 운영 현황 및 현장 정보_20211123.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking_pipeline\\input\\대구광역시 북구_공영주차장 운영 현황 및 현장 정보_20211123.csv'

In [3]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'parking_raw.csv')

In [4]:
df_raw = pd.read_csv(DATA_PATH, encoding="cp949")
df_raw

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,225,154-2-000262,무지개공영주차장,노외,대구광역시 북구 산격동 1393,51,2,미시행,평일+토요일+공휴일,06:00:00,...,600,10,300,0,6000,100000,"현금, 신용카드",대구광역시 북구청,35.893295,128.608568
225,226,154-2-000263,복현장미공원 공영주차장,노외,대구광역시 북구 복현동 439-1,96,2,미시행,평일+토요일+공휴일,06:00:00,...,500,10,100,0,3000,50000,"현금, 카드",대구광역시 북구청,35.893368,128.617312
226,227,154-2-000264,산격4동공영주차장,노외,대구광역시 북구 산격동 1216-24,63,2,미시행,평일+토요일+공휴일,06:00:00,...,600,10,300,0,6000,100000,"현금, 카드",대구광역시 북구청,35.899004,128.606822
227,228,154-1-000265,운암지 공영주차장(노상),노상,대구광역시 북구 구암동 615-13,40,3,미시행,평일,09:00:00,...,400,10,200,0,4000,50000,"현금, 카드",대구광역시 북구청,35.931458,128.563546
228,229,154-2-000266,운암지 공영주차장(노외),노외,대구광역시 북구 구암동 615-13,140,3,미시행,평일,09:00:00,...,400,10,200,0,4000,50000,"현금, 카드",대구광역시 북구청,35.931458,128.563546

In [6]:
df_raw.shape

(229, 27)

In [7]:
df_raw.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [8]:
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [12]:
id_cols = ['주차장명', '소재지지번주소', '주차구획수']
df_long = pd.melt(
    df_raw,
    id_vars=id_cols
)

df_long = df_long.reset_index(drop=True)
df_long.head()

        주차장명               소재지지번주소  주차구획수 variable value
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6       순번     1
1     3공단로인근     대구광역시 북구 노원동3가 14    329       순번     2
2     검단동로인근    대구광역시 북구 검단동 745-2     29       순번     3
3   경대로17길인근      대구광역시 북구 복현동 573     78       순번     4
4   경대로23길인근   대구광역시 북구 복현동 606-34      5       순번     5

In [15]:
df_long = df_long.drop('variable',axis=1)
df_long = df_long.drop('value',axis=1)

In [16]:
df_long

               주차장명               소재지지번주소  주차구획수
0         3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1            3공단로인근     대구광역시 북구 노원동3가 14    329
2            검단동로인근    대구광역시 북구 검단동 745-2     29
3          경대로17길인근      대구광역시 북구 복현동 573     78
4          경대로23길인근   대구광역시 북구 복현동 606-34      5
...             ...                   ...    ...
5491       무지개공영주차장     대구광역시 북구 산격동 1393     51
5492   복현장미공원 공영주차장    대구광역시 북구 복현동 439-1     96
5493      산격4동공영주차장  대구광역시 북구 산격동 1216-24     63
5494  운암지 공영주차장(노상)   대구광역시 북구 구암동 615-13     40
5495  운암지 공영주차장(노외)   대구광역시 북구 구암동 615-13    140

[5496 rows x 3 columns]

In [22]:
# 규모 구분 컬럼 추가
df_series = df_long['주차구획수'].copy()
for i, col in enumerate(df_series):
    if col < 20:
        df_series[i] = 0
    elif col <= 50:
        df_series[i] = 1
    else:
        df_series[i] = 2

df_series

0       0
1       2
2       1
3       2
4       0
       ..
5491    2
5492    2
5493    2
5494    1
5495    2
Name: 주차구획수, Length: 5496, dtype: int64

In [23]:
df_long['규모구분'] = df_series.map({
    0:'소형',
    1:'중형',
    2:'대형'
})

df_long

               주차장명               소재지지번주소  주차구획수 규모구분
0         3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형
1            3공단로인근     대구광역시 북구 노원동3가 14    329   대형
2            검단동로인근    대구광역시 북구 검단동 745-2     29   중형
3          경대로17길인근      대구광역시 북구 복현동 573     78   대형
4          경대로23길인근   대구광역시 북구 복현동 606-34      5   소형
...             ...                   ...    ...  ...
5491       무지개공영주차장     대구광역시 북구 산격동 1393     51   대형
5492   복현장미공원 공영주차장    대구광역시 북구 복현동 439-1     96   대형
5493      산격4동공영주차장  대구광역시 북구 산격동 1216-24     63   대형
5494  운암지 공영주차장(노상)   대구광역시 북구 구암동 615-13     40   중형
5495  운암지 공영주차장(노외)   대구광역시 북구 구암동 615-13    140   대형

[5496 rows x 4 columns]

In [24]:
# 무료/유료 구분
df_raw['요금정보']

0      무료
1      무료
2      무료
3      무료
4      무료
       ..
224    유료
225    유료
226    유료
227    유료
228    유료
Name: 요금정보, Length: 229, dtype: str

In [26]:
df_long['fee_type'] = df_raw['요금정보']

df_long['fee_type'] = df_long['fee_type'].fillna('유료')

df_long

               주차장명               소재지지번주소  주차구획수 규모구분 fee_type
0         3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형       무료
1            3공단로인근     대구광역시 북구 노원동3가 14    329   대형       무료
2            검단동로인근    대구광역시 북구 검단동 745-2     29   중형       무료
3          경대로17길인근      대구광역시 북구 복현동 573     78   대형       무료
4          경대로23길인근   대구광역시 북구 복현동 606-34      5   소형       무료
...             ...                   ...    ...  ...      ...
5491       무지개공영주차장     대구광역시 북구 산격동 1393     51   대형       유료
5492   복현장미공원 공영주차장    대구광역시 북구 복현동 439-1     96   대형       유료
5493      산격4동공영주차장  대구광역시 북구 산격동 1216-24     63   대형       유료
5494  운암지 공영주차장(노상)   대구광역시 북구 구암동 615-13     40   중형       유료
5495  운암지 공영주차장(노외)   대구광역시 북구 구암동 615-13    140   대형       유료

[5496 rows x 5 columns]

In [28]:
# 동(洞) 이름 추출 컬럼 추가
df_series = df_long['소재지지번주소'].copy()

for i, col in enumerate(df_series):
    df_series[i]=col.split()[2]
df_series

0       노원동3가
1       노원동3가
2         검단동
3         복현동
4         복현동
        ...
5491      산격동
5492      복현동
5493      산격동
5494      구암동
5495      구암동
Name: 소재지지번주소, Length: 5496, dtype: str

In [29]:
df_long['동이름'] = df_series

df_long

               주차장명               소재지지번주소  주차구획수 규모구분 fee_type    동이름
0         3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형       무료  노원동3가
1            3공단로인근     대구광역시 북구 노원동3가 14    329   대형       무료  노원동3가
2            검단동로인근    대구광역시 북구 검단동 745-2     29   중형       무료    검단동
3          경대로17길인근      대구광역시 북구 복현동 573     78   대형       무료    복현동
4          경대로23길인근   대구광역시 북구 복현동 606-34      5   소형       무료    복현동
...             ...                   ...    ...  ...      ...    ...
5491       무지개공영주차장     대구광역시 북구 산격동 1393     51   대형       유료    산격동
5492   복현장미공원 공영주차장    대구광역시 북구 복현동 439-1     96   대형       유료    복현동
5493      산격4동공영주차장  대구광역시 북구 산격동 1216-24     63   대형       유료    산격동
5494  운암지 공영주차장(노상)   대구광역시 북구 구암동 615-13     40   중형       유료    구암동
5495  운암지 공영주차장(노외)   대구광역시 북구 구암동 615-13    140   대형       유료    구암동

[5496 rows x 6 columns]

In [33]:
# 선택한 데이터를 PostgreSQL parkingdb에 parking_lot이라는 이름의 테이블로 저장하시오.

# DB 연결
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'
TABLE_NAME = 'parking_lot'

def save_to_postgresql(df, db_url, tabel_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('연결')
        print(f'{version[:80]}')

    df_save.to_sql(
        name=tabel_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {tabel_name};')).fetchone()[0]

        print(saved_count)

In [34]:
# 함수 호출
save_to_postgresql(df_long, DB_URL, TABLE_NAME)

연결
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit
5496